prow/config/plugins.yaml

For this repo and office-hours repo too.

new: approve, lgtm, size, etc.

---

prow/config/plugins.yaml

new: add wip and dco plugins

---

prow/config/plugins.yaml

new: add lifecycle and avoid auto assign

---

prow/config/plugins.yaml

new: enable hold plugin

---

prow/config/plugins.yaml

new: automatic branch cleaning 

---

prow/cluster/branchprotector.yaml
prow/cluster/deck.yaml
prow/cluster/needs-rebase.yaml
prow/config/configs.yaml

Fixes #15 
Target repositories:
- test-infra
- office-hours
References:
- https://github.com/kubernetes/test-infra/blob/adb8ecf1cb55aa8a806fdfc2981e533e6410d42f/prow/cmd/branchprotector/README.md
- https://help.github.com/en/articles/about-protected-branches
---

branch protections

---

prow/config/configs.yaml
prow/config/plugins.yaml

Enable prow on Falco

---

prow/config/plugins.yaml

Fix indentation of missing comment sections

---

prow/config/configs.yaml

Branch protections for Falco

---

prow/config/configs.yaml

fix: work in progress label

---

prow/config/plugins.yaml

fix: config updater config path

---

prow/config/configs.yaml

fix: disable approving review count for now

---

prow/config/configs.yaml

enable branch protection mandatory checks

---

prow/cluster/tide.yaml
prow/config/configs.yaml

new: update tide

---

.gitignore
OWNERS
README.md

Signed-off-by: markyjackson <marky.r.jackson@gmail.com>

.gitignore update, adding to OWNERS and typo in README

---

prow/config/plugins.yaml

Since we are starting to have new, first-time, contributors this PR adds the `welcome` plugin! 🎉 
The welcome message is the default one. Ie.,
```
"Welcome @{{.AuthorLogin}}! It looks like this is your first PR to {{.Org}}/{{.Repo}} 🎉"
```

new: welcome plugin

---

prow/cluster/branchprotector.yaml
prow/config/configs.yaml
prow/config/plugins.yaml

new: enable prow on client-go

---

prow/config/configs.yaml
prow/config/plugins.yaml

new: prow configs and plugins for falco website repo

---

prow/config/plugins.yaml

Co-authored-byL Lorenzo Fontana <lo@linux.com>

update: needs kind for falco-website repo

---

prow/config/configs.yaml
prow/config/plugins.yaml

update(prow/config): rename office-hours to community

---

prow/config/configs.yaml
prow/config/plugins.yaml

Fixes #71 
Plugins:
approve
assign
blunderbuss
branchcleaner
cat
dco
help
hold
label
lifecycle
lgtm
require-matching-label
size
verify-owners
welcome
wip
Labels:
At least a "kind/*" label
master
rebase
must be "approved"
must have a "lgtm" review
commits must be signed-off
must NOT have "do-not-merge/*" labels
must NOT have "needs-rebase" label

Prow for .github repo

---

prow/config/configs.yaml
prow/config/plugins.yaml

Fixes #74 
**Plugins**:
approve
assign
blunderbuss
branchcleaner
dco
help
hold
label
lifecycle
lgtm
size
verify-owners
welcome
wip
**Labels**:
No enforcements.
**Protected branches**:
master
**Merging strategy**:
rebase
**PR checks & auto-merge (tide)**:
must be "approved"
must have a "lgtm" review
commits must be signed-off
must NOT have "do-not-merge/*" labels
must NOT have "needs-rebase" label

Prow for template-repository

---

prow/config/configs.yaml

fix(prow/config): branch protection for advocacy repo

---

prow/config/configs.yaml
prow/config/plugins.yaml

Enable poiana on client-rs

---

prow/config/configs.yaml

update: remove agent master from falco prow

---

prow/config/configs.yaml

update: approving review counter and checks

---

prow/config/configs.yaml

update: falco uses centos7

---

prow/config/plugins.yaml

update: adding help plugin to all repos

---

prow/config/configs.yaml
prow/config/plugins.yaml

new(prow/config): enable Prow for build-service repo

---

prow/config/plugins.yaml

fix(prow/config): missing build-service plugins

---

prow/config/configs.yaml
prow/config/plugins.yaml

new: build-service is now driverkit

---

prow/config/configs.yaml

new: driverkit checks for circleci

---

.circleci/config.yml

fix: workspace attach circleci

---

.circleci/config.yml

fix: circle image dependencies

---

.circleci/config.yml

fix: driverkit is the folder, not the reference

---

driverkit/config/dev/ubuntu_4.15.0-91-generic_92.yaml

new: prebuilt module for ubuntu ubuntu_4.15.0-91-generic_92 (dev driverversion)

---

.circleci/config.yml
driverkit/config/be1ea2d9482d0e6e2cb14a0fd7e08cbecf517f94/ubuntu_4.15.0-91-generic_92.yaml

use explicit driverkit image + ubuntu 4.15.0-91 config (be1ea2 driverversion)

---

prow/config/plugins.yaml

update(prow/config): add release-note to event-generator

---

.circleci/config.yml
driverkit/Makefile

new(dbg): failing logs artifacts

---

driverkit/config/a259b4bf49c3330d9ad6c3eed9eb1a31954259a6/debian_4.19.0-9-amd64_1.yaml
driverkit/config/a259b4bf49c3330d9ad6c3eed9eb1a31954259a6/debian_5.5.0-0.bpo.2-amd64_1.yaml
driverkit/config/a259b4bf49c3330d9ad6c3eed9eb1a31954259a6/debian_5.5.0-1-amd64_1.yaml
driverkit/config/a259b4bf49c3330d9ad6c3eed9eb1a31954259a6/debian_5.6.0-1-amd64_1.yaml
driverkit/config/a259b4bf49c3330d9ad6c3eed9eb1a31954259a6/ubuntu-generic_4.15.0-99-generic_100.yaml
driverkit/config/a259b4bf49c3330d9ad6c3eed9eb1a31954259a6/ubuntu-generic_4.4.0-179-generic_209.yaml
driverkit/config/a259b4bf49c3330d9ad6c3eed9eb1a31954259a6/ubuntu-generic_5.3.0-51-generic_44.yaml
driverkit/config/a259b4bf49c3330d9ad6c3eed9eb1a31954259a6/ubuntu-generic_5.4.0-28-generic_32.yaml
driverkit/config/a259b4bf49c3330d9ad6c3eed9eb1a31954259a6/ubuntu-generic_5.4.0-29-generic_33.yaml
driverkit/config/dev/debian_4.19.0-9-amd64_1.yaml
driverkit/config/dev/debian_5.5.0-0.bpo.2-amd64_1.yaml
driverkit/config/dev/debian_5.5.0-1-amd64_1.yaml
driverkit/config/dev/debian_5.6.0-1-amd64_1.yaml
driverkit/config/dev/ubuntu-generic_4.15.0-99-generic_100.yaml
driverkit/config/dev/ubuntu-generic_4.4.0-179-generic_209.yaml
driverkit/config/dev/ubuntu-generic_5.3.0-51-generic_44.yaml
driverkit/config/dev/ubuntu-generic_5.4.0-28-generic_32.yaml
driverkit/config/dev/ubuntu-generic_5.4.0-29-generic_33.yaml

New Falco drivers for newly released debian and ubuntu-generic kernels.

DBG updates 

---

prow/config/configs.yaml
prow/config/plugins.yaml

This PR adds @poiana (stop the drama!) to the [pdig](https://github.com/falcosecurity/pdig) repository.
Plugins:
- approve
- assign
- blunderbuss
- cat
- dco
- help
- hold
- label
- lifecycle
- lgtm
- <strike>release-note</strike> (not enabled atm since the repo needs PR templates)
- <strike>require-matching-label </strike> (not enabled atm since the repo needs PR templates)
- size
- welcome
- wip
Labels:
- <strike>At least a "kind/*" label</strike> (not enabled atm since the repo needs PR templates)
- master
- rebase
- must NOT have …

Prow setup for pdig

---

prow/config/configs.yaml
prow/config/plugins.yaml

Plugins:
- approve
- assign
- blunderbuss
- cat
- dco
- goose
- help
- hold
- label
- lifecycle
- lgtm
- <strike>release-note</strike> (not enabled atm since the repo needs PR templates)
- <strike>require-matching-label </strike> (not enabled atm since the repo needs PR templates)
- size
- welcome
- wip
Labels:
- <strike>At least a "kind/*" label</strike> (not enabled atm since the repo needs PR templates)
- master
- rebase

poiana for falcosecurity/charts

---

prow/config/configs.yaml

update(prow/config): protect `gh-pages` branch on `charts` repo

---

prow/config/configs.yaml

update(prow/config): required status checks for test-infra itself

---

README.md

docs: add deck url to readme

---

driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/amazonlinux2_4.14.186-146.268.amzn2.x86_64_1.yaml

https://github.com/falcosecurity/falco/issues/1345
Signed-off-by: Matt Krause <matt.krause411@gmail.com>

Issue#1345 missing eks kernel module

---

driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/amazonlinux2_4.14.192-147.314.amzn2.x86_64_1.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-aws_5.4.0-1021-aws_2.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/amazonlinux2_4.14.192-147.314.amzn2.x86_64_1.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-aws_5.4.0-1021-aws_2.yaml

Co-Authored-By: Leonardo Grasso <me@leonardograsso.com>

update: bump drivers to Aug 25th 2020

---

.circleci/config.yml

fix drivers cleanup (needs make)

---

prow/config/configs.yaml

musl (statically-linked) build job mandatory for Falco

---

driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-aws_5.4.0-1025-aws_25.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-aws_5.8.0-1005-aws_5.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-generic_5.8.0-19-generic_20.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-aws_5.4.0-1025-aws_25.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-aws_5.8.0-1005-aws_5.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-generic_5.8.0-19-generic_20.yaml

update(driverkit/config): new ubuntu prebuilt drivers

---

proposals/20200915-prow.md

I re-made the PR since I re-wrote history on rebase, and didn't want to clutter it up how to use DCO signing.

adding prow propsal .... new PR with signoff

---

driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-aws_4.15.0-1081-aws_85.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-aws_5.4.0-1023-aws_23.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-generic_4.15.0-116-generic_117.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-generic_5.4.0-46-generic_50.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-aws_4.15.0-1081-aws_85.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-aws_5.4.0-1023-aws_23.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-generic_4.15.0-116-generic_117.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-generic_5.4.0-46-generic_50.yaml

update(driverkit/config): drivers updated to September 18th 2020

---

driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/debian_4.19.0-11-amd64_1.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/debian_5.8.0-2-amd64_1.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-aws_4.15.0-1084-aws_88.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-aws_4.4.0-1115-aws_128.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-aws_5.4.0-1026-aws_26.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-generic_4.15.0-119-generic_120.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-generic_4.4.0-191-generic_221.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-generic_5.4.0-49-generic_53.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/debian_4.19.0-11-amd64_1.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/debian_5.8.0-2-amd64_1.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-aws_4.15.0-1084-aws_88.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-aws_4.4.0-1115-aws_128.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-aws_5.4.0-1026-aws_26.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-generic_4.15.0-119-generic_120.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-generic_4.4.0-191-generic_221.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-generic_5.4.0-49-generic_53.yaml

update(driverkit/config): bump drivers to September 23rd 2020

---

driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-generic_5.8.0-20-generic_21.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-generic_5.8.0-20-generic_21.yaml

- ubuntu-generic 5.8.0-20-generic-21

update(driverkit/config): drivers bump to september 24th 2020

---

OWNERS

As per the last Falco Infra WG Call, we welcome 🥳  @jonahjon and @maxgio92 in the test-infra maintainers!
Recap in the [mailing list](https://lists.cncf.io/g/cncf-falco-dev/message/170).

update(OWNERS): adding jonahjon and maxgio92

---

driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/amazonlinux2_4.14.198-152.320.amzn2.x86_64_1.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/amazonlinux2_4.14.198-152.320.amzn2.x86_64_1.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/amazonlinux2_4.14.198-152.320.amzn2.x86_64_1.yaml

Closes #191
Signed-off-by: Petr Michalec <pmichalec@ves.io>

add amazonlinux2_4.14.198-152.320

---

deploy.sh

Signed-off-by: Spencer Krum <nibz@spencerkrum.com>
Just a quick little update. Feel free to squash.

chore: small improvements to deploy script

---

proposals/20200925-admins.md

Signed-off-by: Spencer Krum <nibz@spencerkrum.com>

Proposal for Falco Infra Admins

---

driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/amazonlinux2_4.14.200-155.322.amzn2.x86_64_1.yaml
driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/amazonlinux_4.14.200-116.320.amzn1.x86_64_1.yaml
driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/debian_4.9.0-14-amd64_1.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/amazonlinux2_4.14.200-155.322.amzn2.x86_64_1.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/amazonlinux_4.14.200-116.320.amzn1.x86_64_1.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/debian_4.9.0-14-amd64_1.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/amazonlinux2_4.14.200-155.322.amzn2.x86_64_1.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/amazonlinux_4.14.200-116.320.amzn1.x86_64_1.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/debian_4.9.0-14-amd64_1.yaml

update(driverkit/config): bump drivers to October 30th

---

prow/config/configs.yaml

Protect Falco hotfix release branch (0.26.2)

---

config/jobs/lifecycle-bot/periodic-rotten.yaml

fix YAML indentation for periodic-rotten ProwJob

---

.circleci/config.yml
config/jobs/check-prow-config/check-prow-config.yaml
config/jobs/lifecycle-bot/periodic-close.yaml
config/jobs/lifecycle-bot/periodic-rotten.yaml
config/jobs/lifecycle-bot/periodic-stale.yaml
config/plugins.yaml
config/prow/check-config.yaml
tools/deploy_prow.sh

Fixes #12 
As per the title, this new presubmit ProwJob uses `checkconfig` tool to verify the Prow configs (if they changed).

presubmit check prow config

---

config/jobs/build-drivers/build-drivers.yaml

Add drivers build Prow jobs for all Linux distributions

Add build-drivers jobs for all distros

---

config/config.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/prow/branchprotector.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/plank.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/45eeca6478...061f85d859

Bump prow from v20201102-45eeca6478 to v20201124-061f85d859

---

config/config.yaml

falcosidekick: add required ci checks
/assign @leogr

falcosidekick: add required ci checks

---

config/config.yaml

charts: add required ci checks
fix partially: https://github.com/falcosecurity/charts/issues/156
/assign @leogr

prow: add required github status for charts repo

---

config/config.yaml
config/jobs/lifecycle-bot/periodic-rotten.yaml

Details in the issue below.
Fixes #238

Prow config fine-tuning

---

config/config.yaml
images/build-drivers/build-drivers.sh

Updating timeout for PR #225 
Closes Issue
#228

Upping timeout and closing issue #228

---

config/clusters/global.tf
config/clusters/iam.tf
config/jobs/build-drivers/build-drivers.yaml
config/prow/build-drivers-serviceaccount.yaml
images/build-drivers/build-drivers.sh

PR to test Driver S3 upload

---

config/config.yaml

Co-authored-by: Leonardo Di Donato <leodidonato@gmail.com>
Co-authored-by: Lorenzo Fontana <fontanalorenz@gmail.com>
See https://github.com/falcosecurity/falco-website/issues/338

update(config): set protected branch for the versioned website

---

driverkit/Makefile

fix(driverkit): check if publish folder needs to be synced

---

driverkit/Makefile
driverkit/README.md
images/autobump/autobump.sh

Adding readme change to kickoff jobs

---

config/jobs/update-maintainers/update-maintainers.yaml
images/update-maintainers/Makefile
images/update-maintainers/entrypoint.sh
images/update-maintainers/persons.json

- Make it commit as @poiana 
- Fix `entrypoint.sh` script
- Prepare support for `ghproxy`
- Correct the `entrypoint.sh` path in the job's YAML definition
- Build container without cache to force it to download and use the latest [leodido/maintainers-generator](https://github.com/leodido/maintainers-generator)

Refinements to update-maintainers periodic ProwJob

---

images/update-maintainers/persons.json

Blocked by https://github.com/falcosecurity/falcosidekick/pull/166
/hold

update(images/update-maintainers): add keisuke info to persons db

---

config/clusters/eks_variables.tf

For testing sidekick lambda integration with K8s.

adding Thomas for EKS cluster access

---

.circleci/config.yml

using alpine with git installed for terrascan

---

config/jobs/autobump/autobump.yaml
images/autobump/autobump.sh

Based off Leo's Update-maintainers script, trying to update Autobump to use Piona as the default bot.

updating autobump sciprt to call from piona

---

images/update-maintainers/persons.json

/kind documentation
/assign @leogr @leodido

update cpanato information

---

images/autobump/autobump.sh

removing GERRIT env's and script calls from autobump.sh

---

images/autobump/autobump.sh

Commit changes in K8s test-infra
https://github.com/kubernetes/test-infra/commit/37a45bba8ca1acbef74f635da3f0c5d4d34a477f

fixing upstream flag change from pr-creator

---

config/plugins.yaml

update(config): kilt doesn't use release note blocks

---

images/update-maintainers/persons.json

update(images/update-maintainers): add Frank's details (welcome!)

---

config/config.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/prow/branchprotector.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/plank.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/451988f24f...72696ce111

Bump prow from v20210205-451988f24f to v20210211-72696ce111

---

driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/amazonlinux2_4.14.219-161.340.amzn2.x86_64_1.yaml
driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/amazonlinux_4.14.219-119.340.amzn1.x86_64_1.yaml
driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/ubuntu-aws_4.4.0-1122-aws_136.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_4.14.219-161.340.amzn2.x86_64_1.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux_4.14.219-119.340.amzn1.x86_64_1.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/ubuntu-aws_4.4.0-1122-aws_136.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/amazonlinux2_4.14.219-161.340.amzn2.x86_64_1.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/amazonlinux_4.14.219-119.340.amzn1.x86_64_1.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-aws_4.4.0-1122-aws_136.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/amazonlinux2_4.14.219-161.340.amzn2.x86_64_1.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/amazonlinux_4.14.219-119.340.amzn1.x86_64_1.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-aws_4.4.0-1122-aws_136.yaml

Update driver configurations (2021-02-22)

---

config/jobs/build-libs/build-libs.yaml
config/jobs/build-prow-images/build-images.yaml
images/build-libs/Dockerfile
images/build-libs/Makefile
images/build-libs/build.sh

This PR aims to introduce an initial prow job for falcosecurity/libs CI, as per https://github.com/falcosecurity/libs/issues/9
If it works other similar jobs will be configured later.
Currently, just a draft.

new build-libs job for falcosecurity/libs

---

config/plugins.yaml

This should allow jobs to run on falcosecurity/libs
/cc @maxgio92

update(config): add trigger plugin for falcosecurity/libs

---

config/jobs/build-libs/build-libs.yaml

fix(config/lobs/build-libs): do not skip PR against master

---

config/config.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/prow/branchprotector.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/plank.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/445b85c368...c6b468b556

Bump prow from v20210218-445b85c368 to v20210226-c6b468b556

---

driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/ubuntu-aws_5.8.0-1025-aws_1.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/ubuntu-aws_5.8.0-1025-aws_1.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-aws_5.8.0-1025-aws_1.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-aws_5.8.0-1025-aws_1.yaml

Update driver configurations (2021-03-02)

---

tools/create_ecr.sh

Spot a missing repository creation for one of our ProwJob images.

create AWS ECR repository for test-infra/update-maintainers

---

driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/centos_4.18.0-240.1.1.el8_3.x86_64_1.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/centos_4.18.0-80.el8.x86_64_1.yaml

Signed-off-by: Jose Angel Santiago <>

Add Centos8 kernels

---

driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/debian_4.9.0-15-amd64_1.yaml
driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/debian_5.10.0-3-cloud-amd64_1.yaml
driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/ubuntu-generic_5.11.0-11-generic_12.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/debian_4.9.0-15-amd64_1.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/debian_5.10.0-3-cloud-amd64_1.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/ubuntu-generic_5.11.0-11-generic_12.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/debian_4.9.0-15-amd64_1.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/debian_5.10.0-3-cloud-amd64_1.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-generic_5.11.0-11-generic_12.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/debian_4.9.0-15-amd64_1.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/debian_5.10.0-3-cloud-amd64_1.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-generic_5.11.0-11-generic_12.yaml

Update driver configurations (2021-03-12)

---

config/config.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/prow/branchprotector.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/plank.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/67f589ad7c...2181a9e7d7

Bump prow from v20210312-67f589ad7c to v20210319-2181a9e7d7

---

config/clusters/eks_variables.tf

I'm opening this since I'd like to work on the Prow cluster in order to make it able to compile and pre-package ARM-based falco 🙏

update: add myself to EKS system:masters

---

images/update-falco-k8s-manifests/entrypoint.sh

fix(images/update-falco-k8s-manifests): correct GH_REPO

---

config/plugins.yaml

fix(config): make poiana approval comments reference our Prow instance

---

config/config.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/prow/branchprotector.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/plank.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/ad0e6d1480...1e772aaa42

Bump prow from v20210325-ad0e6d1480 to v20210401-1e772aaa42

---

OWNERS

Since in the last months my knowledge about test-infra and the tools involved grew and I now feel more confident, I would like to add myself to the owners' file. So I could help with PR reviews and other maintainer efforts.
Thanks!

update(OWNERS): add leogr

---

images/update-falco-k8s-manifests/entrypoint.sh

This should fix:
```
Error: kustomization file already exists
```
See [the job log](https://falco-prow-logs.s3.eu-west-1.amazonaws.com/logs/update-falco-k8s-manifests/1382227298756857856/build-log.txt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=ASIAUIOA5MU2I5VAQHNY%2F20210414%2Feu-west-1%2Fs3%2Faws4_request&X-Amz-Date=20210414T073721Z&X-Amz-Expires=600&X-Amz-Security-Token=FwoGZXIvYXdzEKH%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaDEAOfy%2Fa%2BTUj9U69lSKFBMKAebtImXLvzaxMLH%2BaUtssNdpBqUiE5EhB5Zggtsocnatp%2F9278lZKlmsd9g%2FVcavFmuaPfnPvnsrxXJhnrtCZ45XofTRdcvV7cHe78e4VjJyhzxEXV2mbwMwOLQwZSgLXoooephvOFcpAg9nNXwHnOWR9gCZLICXvl32C69zoYhKD%2Bg666eC0mKot7C9CIO5ommMOdBVTZqiuZqdpkrXuHkMmgVlT4drGm5TWe3bplsg6R5Uv88eo9dtde9sTlC0G0VL%2Br%2BwYMu4cjpxSFAoF8%2FNBHGRrmv%2FLofz31TUk6YBhHYegX1zwfZWK1jjPpUDWCxX%2F …

fix(images/update-falco-k8s-manifests): remove kustomization.yaml before recreating it

---

images/update-maintainers/persons.json

Update the persons DB to let @poiana fill the [maintainers.yaml](https://github.com/falcosecurity/.github/blob/master/maintainers.yaml).
Welcome again @sreedaum! And thank you so much for the Malayalam translation of the Falco website! 🥳 

update(images/update-maintainers): sreedaum info for maintainers.yaml generation

---

config/config.yaml

updating branch protection tag

---

images/update-maintainers/persons.json

update(images/update-maintainers): Kaizhe joined Aurora

---

images/update-maintainers/persons.json

Refs https://github.com/falcosecurity/.github/pull/44
This PR updates the details of @cpanato 
Co-authored-by: Carlos Panato <ctadeu@gmail.com>

update(images/update-maintainers): Carlos's company

---

driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/amazonlinux2_5.4.105-48.177.amzn2.x86_64_1.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_5.4.105-48.177.amzn2.x86_64_1.yaml

This should address https://github.com/falcosecurity/falco/issues/1618

Add newer Amazon kernel version from EKS

---

driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/amazonlinux2_5.4.105-48.177.amzn2.x86_64_1.yaml
driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/centos_3.10.0-1160.25.1.el7.x86_64_1.yaml
driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/ubuntu-aws_4.15.0-1100-aws_107.yaml
driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/ubuntu-aws_4.15.0-1101-aws_108.yaml
driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/ubuntu-aws_5.4.0-1046-aws_48.yaml
driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/ubuntu-aws_5.4.0-1047-aws_49.yaml
driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/ubuntu-aws_5.8.0-1031-aws_33.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_5.4.105-48.177.amzn2.x86_64_1.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/centos_3.10.0-1160.25.1.el7.x86_64_1.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/ubuntu-aws_4.15.0-1100-aws_107.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/ubuntu-aws_4.15.0-1101-aws_108.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/ubuntu-aws_5.4.0-1046-aws_48.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/ubuntu-aws_5.4.0-1047-aws_49.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/ubuntu-aws_5.8.0-1031-aws_33.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/centos_3.10.0-1160.25.1.el7.x86_64_1.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-aws_4.15.0-1100-aws_107.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-aws_4.15.0-1101-aws_108.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-aws_5.4.0-1046-aws_48.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-aws_5.4.0-1047-aws_49.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-aws_5.8.0-1031-aws_33.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/centos_3.10.0-1160.25.1.el7.x86_64_1.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-aws_4.15.0-1100-aws_107.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-aws_4.15.0-1101-aws_108.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-aws_5.4.0-1046-aws_48.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-aws_5.4.0-1047-aws_49.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-aws_5.8.0-1031-aws_33.yaml

Update driver configurations (2021-05-02)

---

tools/deploy_prow.sh

This PR should fix Secrets content needed for the PR status page.

fix(tools/deploy_prow.sh): fix pr-status secrets key

---

Makefile
config/clusters/ecr.tf
config/clusters/terraform_providers.tf
config/clusters/terraform_versions.tf
tools/terraform.Makefile

This PR fixes some issues on ECR policies and improves local development and testing UX for infrastructure as code.

Fix ECR repositories policies issues

---

driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/amazonlinux2_5.4.110-54.182.amzn2.x86_64_1.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_5.4.110-54.182.amzn2.x86_64_1.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/amazonlinux2_5.4.110-54.182.amzn2.x86_64_1.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/amazonlinux2_5.4.110-54.182.amzn2.x86_64_1.yaml

Hello,
reading older similar PRs, I thought perhaps this is the way to go in order to solve https://github.com/falcosecurity/falco/issues/1643 ?

Add new AmazonLinux2 EKS AMI kernel

---

config/config.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/prow/branchprotector.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/7d5e552c49...0713522bd8

Bump prow from v20210409-7d5e552c49 to v20210521-0713522bd8

---

config/config.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/prow/branchprotector.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/0713522bd8...84965e233e

Bump prow from v20210521-0713522bd8 to v20210526-84965e233e

---

config/config.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/prow/branchprotector.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/84965e233e...95cc9f4b68

Bump prow from v20210526-84965e233e to v20210604-95cc9f4b68

---

driverkit/config/13ec67ebd23417273275296813066e07cb85bc91/amazonlinux2_4.14.232-176.381.amzn2.x86_64_1.yaml
driverkit/config/13ec67ebd23417273275296813066e07cb85bc91/amazonlinux2_5.4.110-54.182.amzn2.x86_64_1.yaml
driverkit/config/13ec67ebd23417273275296813066e07cb85bc91/ubuntu-aws_5.8.0-1031-aws_33.yaml
driverkit/config/13ec67ebd23417273275296813066e07cb85bc91/ubuntu-generic_5.8.0-52-generic_59.yaml
driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/amazonlinux2_4.14.232-176.381.amzn2.x86_64_1.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_4.14.232-176.381.amzn2.x86_64_1.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/amazonlinux2_4.14.232-176.381.amzn2.x86_64_1.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/amazonlinux2_4.14.232-176.381.amzn2.x86_64_1.yaml

Update drivers (2021-05-27)

---

config/jobs/build-prow-images/publish-images.yaml
images/build.sh

This PR should prevent from publishing CI base images before approving the related PRs.
Fixes #421.

Fix images approval: publish after PR approval

---

config/clusters/storage.tf
config/clusters/terraform_state.tf

This PR should solve #423.
/cc @jonahjon

Fix storage terraform resource dependency cycle

---

config/config.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/prow/branchprotector.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/95cc9f4b68...402d3ba6b7

Bump prow from v20210604-95cc9f4b68 to v20210609-402d3ba6b7

---

config/plugins.yaml

Changing URL to try and fix https://github.com/falcosecurity/test-infra/issues/430

fixing issue for join url

---

config/clusters/TERRAFORM.md
config/clusters/terraform_versions.tf
tools/deploy_terraform.sh

Job failed
https://app.circleci.com/pipelines/github/falcosecurity/test-infra/968/workflows/c9866488-1a6e-4997-beb6-2cadabcd292b/jobs/3697
Updating versions of TF and provider to try and fix.

updating TF version CI broken

---

config/clusters/.terraform.lock.hcl
config/clusters/iam.tf
config/clusters/storage.tf
config/clusters/terraform_providers.tf
config/clusters/terraform_versions.tf
tools/deploy_terraform.sh

current CI is blocked, going to newest version on old state format.

fixing terraform version

---

config/jobs/recurring-ghissues/prow-eks-upgrade.yaml

test: set prow-eks-upgrade ghissue job to run monday morning

---

config/config.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/prow/branchprotector.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/402d3ba6b7...4b498df7d4

Bump prow from v20210609-402d3ba6b7 to v20210617-4b498df7d4

---

config/config.yaml

As per [website release instructions](https://github.com/falcosecurity/falco-website/blob/master/release.md#create-a-new-website-snapshot).

update(config): protect branch v0.28 of the falco-website

---

driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/ubuntu-generic_5.4.0-76-generic_85.yaml
driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/ubuntu-generic_5.8.0-57-generic_64.yaml
driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/ubuntu-generic_5.4.0-76-generic_85.yaml
driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/ubuntu-generic_5.8.0-57-generic_64.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/ubuntu-generic_5.4.0-76-generic_85.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/ubuntu-generic_5.8.0-57-generic_64.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-generic_5.4.0-76-generic_85.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-generic_5.8.0-57-generic_64.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-generic_5.4.0-76-generic_85.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-generic_5.8.0-57-generic_64.yaml

Update driver configurations (2021-06-22)

---

driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/centos_4.18.0-277.el8.x86_64_1.yaml
driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/centos_4.18.0-277.el8.x86_64_1.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/centos_4.18.0-277.el8.x86_64_1.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/centos_4.18.0-277.el8.x86_64_1.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/centos_4.18.0-277.el8.x86_64_1.yaml

cleaned PR
Signed-off-by: Matan Monitz <mmonitz@gmail.com>

add support for centos_4.18.0-277

---

driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_5.4.117-58.216.amzn2.x86_64_1.yaml

Signed-off-by: Yankee Maharjan <yankee.exe@gmail.com>

Amazon Linux 2 5.4.117-58.216.amzn2.x86_64 support

---

README.md

Signed-off-by: Mritunjay Sharma <mritunjaysharma394@gmail.com>

docs: fixes typo in README

---

config/config.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/prow/branchprotector.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/4b498df7d4...abd67550c2

Bump prow from v20210617-4b498df7d4 to v20210625-abd67550c2

---

config/clusters/TERRAFORM.md
config/clusters/eks.tf

Adding node group version bump since they are still on 1.17.
`v1.17.12-eks-7684af`

updating eks version 1.19

---

config/clusters/eks.tf

Update eks 118

---

config/clusters/eks.tf

Control Plane to 1.19 upgrade.

updating control plan to 119

---

driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/ubuntu-generic_5.4.0-77-generic_86.yaml
driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/ubuntu-generic_5.4.0-77-generic_86.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/ubuntu-generic_5.4.0-77-generic_86.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-generic_5.4.0-77-generic_86.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-generic_5.4.0-77-generic_86.yaml

Signed-off-by: Massimiliano Giovagnoli <massimiliano.giovagnoli.1992@gmail.com>

Add prebuilt drivers configs for ubuntu generic kernel 5.4.0-77 86

---

config/clusters/eks.tf

updating nodegroups to 1.19

---

config/config.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/prow/branchprotector.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/abd67550c2...3efe91b8cd

Bump prow from v20210625-abd67550c2 to v20210701-3efe91b8cd

---

driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/ubuntu-aws_4.15.0-1108-aws_115.yaml
driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/ubuntu-aws_5.11.0-1013-aws_1.yaml
driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/ubuntu-aws_5.4.0-1053-aws_55.yaml
driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/ubuntu-generic_4.15.0-150-generic_155.yaml
driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/ubuntu-generic_5.4.0-79-generic_88.yaml
driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/ubuntu-aws_4.15.0-1108-aws_115.yaml
driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/ubuntu-aws_5.11.0-1013-aws_1.yaml
driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/ubuntu-aws_5.4.0-1053-aws_55.yaml
driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/ubuntu-generic_4.15.0-150-generic_155.yaml
driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/ubuntu-generic_5.4.0-79-generic_88.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/ubuntu-aws_4.15.0-1108-aws_115.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/ubuntu-aws_5.11.0-1013-aws_1.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/ubuntu-aws_5.4.0-1053-aws_55.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/ubuntu-generic_4.15.0-150-generic_155.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/ubuntu-generic_5.4.0-79-generic_88.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-aws_4.15.0-1108-aws_115.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-aws_5.11.0-1013-aws_1.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-aws_5.4.0-1053-aws_55.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-generic_4.15.0-150-generic_155.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-generic_5.4.0-79-generic_88.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-aws_4.15.0-1108-aws_115.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-aws_5.11.0-1013-aws_1.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-aws_5.4.0-1053-aws_55.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-generic_4.15.0-150-generic_155.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-generic_5.4.0-79-generic_88.yaml

Update drivers (2021-07-07)

---

config/clusters/eks.tf

updating eks cluster to 1.20

---

config/config.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/prow/branchprotector.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/3efe91b8cd...f607a865fb

Bump prow from v20210701-3efe91b8cd to v20210709-f607a865fb

---

images/update-maintainers/persons.json

update(images/update-maintainers): my company

---

driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_4.14.238-182.421.amzn2.x86_64_1.yaml
driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux_4.14.238-125.421.amzn1.x86_64_1.yaml
driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/ubuntu-generic_5.13.0-12-generic_12.yaml
driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/amazonlinux2_4.14.238-182.421.amzn2.x86_64_1.yaml
driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/amazonlinux_4.14.238-125.421.amzn1.x86_64_1.yaml
driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/ubuntu-generic_5.13.0-12-generic_12.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_4.14.238-182.421.amzn2.x86_64_1.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux_4.14.238-125.421.amzn1.x86_64_1.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/ubuntu-generic_5.13.0-12-generic_12.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/amazonlinux2_4.14.238-182.421.amzn2.x86_64_1.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/amazonlinux_4.14.238-125.421.amzn1.x86_64_1.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-generic_5.13.0-12-generic_12.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/amazonlinux2_4.14.238-182.421.amzn2.x86_64_1.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/amazonlinux_4.14.238-125.421.amzn1.x86_64_1.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-generic_5.13.0-12-generic_12.yaml

Update drivers (2021-07-17)

---

config/config.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/prow/branchprotector.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/f607a865fb...430fa04d50

Bump prow from v20210709-f607a865fb to v20210716-430fa04d50

---

images/update-maintainers/persons.json

update(images/update-maintainers): Mark Lorenzo as independent

---

config/config.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/prow/branchprotector.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/430fa04d50...55eee17612

Bump prow from v20210716-430fa04d50 to v20210723-55eee17612

---

config/config.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/prow/branchprotector.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/55eee17612...5757a5d200

Bump prow from v20210723-55eee17612 to v20210730-5757a5d200

---

config/config.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/prow/branchprotector.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/5757a5d200...c95403cd67

Bump prow from v20210730-5757a5d200 to v20210806-c95403cd67

---

config/clusters/TERRAFORM.md
config/clusters/eks.tf
config/clusters/eks_variables.tf

Make ARM EKS Node Group scaling config customizable

---

config/config.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/prow/branchprotector.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/c95403cd67...c9ba83f08c

Bump prow from v20210806-c95403cd67 to v20210813-c9ba83f08c

---

driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_5.4.95-42.163.amzn2.x86_64_1.yaml

Add 5.4.95-42.163.amzn2.x86_64 to 17f5df52a7d9ed6bb12d3b1768460def84
Signed-off-by:  goroi <georgi.ivanov77@gmail.com>

Add 5.4.95-42.163.amzn2.x86_64 to 17f5df52a7d9ed6bb12d3b1768460def84

---

driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_5.4.105-48.177.amzn2.x86_64_1.yaml
driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/amazonlinux2_5.4.105-48.177.amzn2.x86_64_1.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_5.4.105-48.177.amzn2.x86_64_1.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/amazonlinux2_5.4.105-48.177.amzn2.x86_64_1.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/amazonlinux2_5.4.105-48.177.amzn2.x86_64_1.yaml

This is exact same as PR #479 just a signed off PR so we can close that one out.

creating signed PR for #479 to add EKS AMI support

---

driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_5.4.105-48.177.amzn2.x86_64_1.yaml
driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_5.4.95-42.163.amzn2.x86_64_1.yaml
driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/ubuntu-aws_5.11.0-1017-aws_18.yaml
driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/ubuntu-generic_4.15.0-156-generic_163.yaml
driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/ubuntu-generic_5.11.0-33-generic_35.yaml
driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/ubuntu-generic_5.4.0-83-generic_93.yaml
driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/amazonlinux2_5.4.105-48.177.amzn2.x86_64_1.yaml
driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/ubuntu-aws_5.11.0-1017-aws_18.yaml
driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/ubuntu-generic_4.15.0-156-generic_163.yaml
driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/ubuntu-generic_5.11.0-33-generic_35.yaml
driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/ubuntu-generic_5.4.0-83-generic_93.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_5.4.105-48.177.amzn2.x86_64_1.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/ubuntu-aws_5.11.0-1017-aws_18.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/ubuntu-generic_4.15.0-156-generic_163.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/ubuntu-generic_5.11.0-33-generic_35.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/ubuntu-generic_5.4.0-83-generic_93.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/amazonlinux2_5.4.105-48.177.amzn2.x86_64_1.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-aws_5.11.0-1017-aws_18.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-generic_4.15.0-156-generic_163.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-generic_5.11.0-33-generic_35.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-generic_5.4.0-83-generic_93.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/amazonlinux2_5.4.105-48.177.amzn2.x86_64_1.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-aws_5.11.0-1017-aws_18.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-generic_4.15.0-156-generic_163.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-generic_5.11.0-33-generic_35.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-generic_5.4.0-83-generic_93.yaml

Update driver configurations (2021-08-22)

---

config/config.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/prow/branchprotector.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/b81cb0bc7b...98f54bde95

Bump prow from v20210818-b81cb0bc7b to v20210827-98f54bde95

---

driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/centos_3.10.0-1160.41.1.el7.x86_64_1.yaml
driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/ubuntu-generic_5.11.0-34-generic_36.yaml
driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/ubuntu-generic_5.4.0-84-generic_94.yaml
driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/centos_3.10.0-1160.41.1.el7.x86_64_1.yaml
driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/ubuntu-generic_5.11.0-34-generic_36.yaml
driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/ubuntu-generic_5.4.0-84-generic_94.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/centos_3.10.0-1160.41.1.el7.x86_64_1.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/ubuntu-generic_5.11.0-34-generic_36.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/ubuntu-generic_5.4.0-84-generic_94.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/centos_3.10.0-1160.41.1.el7.x86_64_1.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-generic_5.11.0-34-generic_36.yaml
driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-generic_5.4.0-84-generic_94.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/centos_3.10.0-1160.41.1.el7.x86_64_1.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-generic_5.11.0-34-generic_36.yaml
driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-generic_5.4.0-84-generic_94.yaml

Update driver configurations (2021-09-02)

---

images/update-maintainers/persons.json

Signed-off-by: pablopez <pablo.lopezzaldivar@sysdig.com>
Hi, 
as requested here, I've updated the [file](https://github.com/falcosecurity/.github/pull/63) with my personal info.

auto-add to maintainers list

---

config/config.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/prow/branchprotector.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/98f54bde95...cf6e08b05f

Bump prow from v20210827-98f54bde95 to v20210903-cf6e08b05f

---

config/config.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/prow/branchprotector.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/cf6e08b05f...6c59eee681

Bump prow from v20210903-cf6e08b05f to v20210909-6c59eee681

---

config/config.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/prow/branchprotector.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/6c59eee681...7657ce97bf

Bump prow from v20210909-6c59eee681 to v20210916-7657ce97bf

---

config/config.yaml
config/jobs/build-plugins/build-plugins.yaml
config/plugins.yaml

Add support for falcosecurity/plugins repo in prow/poiana.

Add plugins jobs

---

config/jobs/build-plugin-sdk-go/build-plugin-sdk-go.yaml
config/jobs/build-plugins/build-plugins.yaml

As a reference, see https://github.com/falcosecurity/test-infra/tree/master/config/jobs#how-to-configure-new-jobs
cc @mstemm

fix plugin jobs paths (again)

---

config/config.yaml

As per [our process](https://github.com/falcosecurity/falco-website/blob/master/release.md#create-a-new-website-snapshot).

update(config): add protected branch for Falco website v0.29

---

config/config.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/prow/branchprotector.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/7657ce97bf...6cf1ab3b20

Bump prow from v20210916-7657ce97bf to v20211001-6cf1ab3b20

---

driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_5.10.68-62.173.amzn2.x86_64_1.yaml
driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/amazonlinux2_5.10.68-62.173.amzn2.x86_64_1.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_5.10.68-62.173.amzn2.x86_64_1.yaml

Signed-off-by: sttor <security@sttor.com>
Falco Amzn2 5.10.68-62.173 kernel module

Falco Amzn2 5.10.68-62.173 kernel module

---

driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/ubuntu-generic_5.4.0-90-generic_101.yaml
driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/ubuntu-generic_5.4.0-90-generic_101.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/ubuntu-generic_5.4.0-90-generic_101.yaml

Fixes https://github.com/falcosecurity/falco/issues/1789

feat(driverkit/config): support ubuntu-generic_5.4.0-90-generic_101

---

tools/deploy_terraform.sh

This PR will make the CI/CD scripts download the `required_version` of terraform, as specified in [config/clusters/terraform_versions.tf](https://github.com/falcosecurity/test-infra/blob/master/config/clusters/terraform_versions.tf).

ci(tools/deploy_terraform.sh): use terraform required version

---

config/config.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/prow/branchprotector.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/8c358bcb9d...bce61c7c4a

Bump prow from v20211008-8c358bcb9d to v20211111-bce61c7c4a

---

config/config.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/prow/branchprotector.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/bce61c7c4a...1147d04f59

Bump prow from v20211111-bce61c7c4a to v20211119-1147d04f59

---

images/update-maintainers/persons.json

Adding myself to the list, after recently becoming a maintainer of `falcosecurity/plugin-sdk-go`.

update(images/update-maintainers): auto-add jasondellaluce

---

images/update-maintainers/persons.json

chore(images/update-maintainers/persons.json): update maxgio92 company

---

driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_5.4.117-58.216.amzn2.x86_64_1.yaml
driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/amazonlinux2_5.4.117-58.216.amzn2.x86_64_1.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_5.4.117-58.216.amzn2.x86_64_1.yaml

Signed-off-by: Kaizhe Huang <khuang@aurora.tech>

add falco ko amazon linux2 2_5.4.117-58.216

---

driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_5.4.156-83.273.amzn2.x86_64_1.yaml
driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/amazonlinux2_5.4.156-83.273.amzn2.x86_64_1.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_5.4.156-83.273.amzn2.x86_64_1.yaml

Signed-off-by: Kaizhe Huang <khuang@aurora.tech>

Add kernel module for amazonlinux2_5.4.156-83.273

---

config/config.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/prow/branchprotector.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/1147d04f59...48cb2fc883

Bump prow from v20211119-1147d04f59 to v20211126-48cb2fc883

---

driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/ubuntu-generic_4.15.0-159-generic_167.yaml
driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/ubuntu-generic_4.15.0-159-generic_167.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/ubuntu-generic_4.15.0-159-generic_167.yaml

Signed-off-by: mathildeHermet <mathildehermet94260@gmail.com>

Add kernel Ubuntu-generic 4.15.0-159_167

---

config/config.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/prow/branchprotector.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/281e29a97a...dfd4c4dd7d

Bump prow from v20211203-281e29a97a to v20211210-dfd4c4dd7d

---

config/config.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/prow/branchprotector.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/dfd4c4dd7d...d20cd1c87e

Bump prow from v20211210-dfd4c4dd7d to v20211229-d20cd1c87e

---

images/update-maintainers/persons.json

update: persons.json

---

config/config.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/prow/branchprotector.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/d20cd1c87e...bf45c6e760

Bump prow from v20211229-d20cd1c87e to v20220107-bf45c6e760

---

images/update-maintainers/persons.json

update(persons): add fededp

---

config/jobs/build-plugins/build-plugins.yaml
images/build-plugins/build-and-publish.sh

Co-authored-by: Leonardo Grasso <me@leonardograsso.com>
This PR adds a Prow post-submit to `build-plugins` to publish release builds of Falco plugins everytime a new tag version gets tagged.

update: add plugin release distribution jobs

---

config/config.yaml
config/plugins.yaml

**NOTE: no jobs added as it is an header only library thus there is no need to build it.**

Add prow configs for falcosecurity/plugin-sdk-cpp

---

config/config.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/prow/branchprotector.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/bf45c6e760...25626d8ef5

Bump prow from v20220107-bf45c6e760 to v20220114-25626d8ef5

---

config/config.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/prow/branchprotector.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/25626d8ef5...8b2d5086e4

Bump prow from v20220114-25626d8ef5 to v20220121-8b2d5086e4

---

config/config.yaml

update(config): protect branch v0.30 for falco-website

---

config/config.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/prow/branchprotector.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/8b2d5086e4...eb56385920

Bump prow from v20220121-8b2d5086e4 to v20220128-eb56385920

---

driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_5.4.172-90.336.amzn2.x86_64_1.yaml
driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/amazonlinux2_5.4.172-90.336.amzn2.x86_64_1.yaml
driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/amazonlinux2_5.4.172-90.336.amzn2.x86_64_1.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_5.4.172-90.336.amzn2.x86_64_1.yaml

This PR adds support for amazonlinux2_5.4.172-90.336

Add config for amazonlinux2_5.4.172-90.336

---

driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_5.4.176-91.338.amzn2.x86_64_1.yaml
driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/amazonlinux2_5.4.176-91.338.amzn2.x86_64_1.yaml
driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/amazonlinux2_5.4.176-91.338.amzn2.x86_64_1.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_5.4.176-91.338.amzn2.x86_64_1.yaml

Simple PR adding support for kernel amazonlinux2_5.4.176-91.338

Add config for amazonlinux2_5.4.176-91.338

---

config/config.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/prow/branchprotector.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/eb56385920...e4574accfe

Bump prow from v20220128-eb56385920 to v20220211-e4574accfe

---

driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/ubuntu-generic_5.4.0-1069-azure_72.yaml
driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/ubuntu-generic_5.4.0-1069-azure_72.yaml
driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/ubuntu-generic_5.4.0-1069-azure_72.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/ubuntu-generic_5.4.0-1069-azure_72.yaml

Signed-off-by: PeterThomasAwen@ubuntu

adding new configuration files for 5.4.0-1069-azure_72

---

config/jobs/check-prow-config/check-prow-config.yaml
config/prow/branchprotector.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/e4574accfe...8b6a2593f3

Bump prow from v20220211-e4574accfe to v20220221-8b6a2593f3

---

images/build-libs/Dockerfile

fix(images): add libprotobuf-dev to deps in build-libs image

---

config/jobs/check-prow-config/check-prow-config.yaml
config/prow/branchprotector.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/8b6a2593f3...e131bfaf16

Bump prow from v20220221-8b6a2593f3 to v20220225-e131bfaf16

---

images/build-drivers/Dockerfile

This allows us to build the latest driver version (after driver versioning scheme modifications)

new(build): update driverkit to v0.6.0

---

config/jobs/peribolos/peribolos.yaml

Fix peribolos binary path and triggering conditions

---

config/jobs/build-libs/build-libs.yaml

fix(jobs): added tolerations to nodeSelector in build-libs-arm job

---

config/clusters/eks.tf
config/clusters/eks_variables.tf

Uniform EKS cluster version, enlarge ARM nodes fleet size, remove legacy users

---

driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_4.14.268-205.500.amzn2.x86_64_1.yaml
driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/amazonlinux2_4.14.268-205.500.amzn2.x86_64_1.yaml
driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/amazonlinux2_4.14.268-205.500.amzn2.x86_64_1.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_4.14.268-205.500.amzn2.x86_64_1.yaml
driverkit/config/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/amazonlinux2_4.14.268-205.500.amzn2.x86_64_1.yaml

Adding new driverkit for amazonlinux2
Related to [#652 ](https://github.com/falcosecurity/test-infra/issues/652)

Adding additional driverkit for amazonlinux2

---

config/config.yaml
config/jobs/arm-build/arm-build.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/jobs/lifecycle-bot/periodic-close.yaml
config/jobs/lifecycle-bot/periodic-rotten.yaml
config/jobs/lifecycle-bot/periodic-stale.yaml
config/jobs/peribolos/peribolos.yaml
config/prow/branchprotector.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/e131bfaf16...c635be23be

Bump prow from v20220225-e131bfaf16 to v20220317-c635be23be

---

driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_4.14.262-200.489.amzn2.x86_64_1.yaml
driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_5.10.82-83.359.amzn2.x86_64_1.yaml
driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_5.10.93-87.444.amzn2.x86_64_1.yaml
driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_5.10.96-90.460.amzn2.x86_64_1.yaml
driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/amazonlinux2_4.14.262-200.489.amzn2.x86_64_1.yaml
driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/amazonlinux2_5.10.82-83.359.amzn2.x86_64_1.yaml
driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/amazonlinux2_5.10.93-87.444.amzn2.x86_64_1.yaml
driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/amazonlinux2_5.10.96-90.460.amzn2.x86_64_1.yaml
driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/amazonlinux2_4.14.262-200.489.amzn2.x86_64_1.yaml
driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/amazonlinux2_5.10.82-83.359.amzn2.x86_64_1.yaml
driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/amazonlinux2_5.10.93-87.444.amzn2.x86_64_1.yaml
driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/amazonlinux2_5.10.96-90.460.amzn2.x86_64_1.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_4.14.262-200.489.amzn2.x86_64_1.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_5.10.82-83.359.amzn2.x86_64_1.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_5.10.93-87.444.amzn2.x86_64_1.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_5.10.96-90.460.amzn2.x86_64_1.yaml
driverkit/config/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/amazonlinux2_4.14.262-200.489.amzn2.x86_64_1.yaml
driverkit/config/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/amazonlinux2_5.10.82-83.359.amzn2.x86_64_1.yaml
driverkit/config/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/amazonlinux2_5.10.93-87.444.amzn2.x86_64_1.yaml
driverkit/config/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/amazonlinux2_5.10.96-90.460.amzn2.x86_64_1.yaml

Signed-off-by: Austin Brogle <abrogle@snapchat.com>
Adding in 4 additional AL2 kernels to be built for latest driver version shipped in 0.31.0 :)

Adding 4 additional al2 kernels

---

config/config.yaml
config/jobs/arm-build/arm-build.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/jobs/lifecycle-bot/periodic-close.yaml
config/jobs/lifecycle-bot/periodic-rotten.yaml
config/jobs/lifecycle-bot/periodic-stale.yaml
config/jobs/peribolos/peribolos.yaml
config/prow/branchprotector.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/c635be23be...1a1db3d5d8

Bump prow from v20220317-c635be23be to v20220318-1a1db3d5d8

---

config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/pushgateway.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

feat(config/prow): set initial guaranteed qos

---

config/jobs/build-drivers/rebuild-all-amazonlinux.yaml
config/jobs/build-drivers/rebuild-all-centos.yaml
config/jobs/build-drivers/rebuild-all-debian.yaml
config/jobs/build-drivers/rebuild-all-ubuntu-aws.yaml
config/jobs/build-drivers/rebuild-all-ubuntu-generic.yaml

fix(config/jobs/build-drivers): add missing resources for periodics

---

config/config.yaml
config/jobs/arm-build/arm-build.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/jobs/lifecycle-bot/periodic-close.yaml
config/jobs/lifecycle-bot/periodic-rotten.yaml
config/jobs/lifecycle-bot/periodic-stale.yaml
config/jobs/peribolos/peribolos.yaml
config/prow/branchprotector.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/1a1db3d5d8...547c14a0ca

Bump prow from v20220318-1a1db3d5d8 to v20220408-547c14a0ca

---

driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/centos_4.18.0-365.el8.x86_64_1.yaml
driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/centos_4.18.0-373.el8.x86_64_1.yaml
driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/centos_4.18.0-365.el8.x86_64_1.yaml
driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/centos_4.18.0-373.el8.x86_64_1.yaml
driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/centos_4.18.0-365.el8.x86_64_1.yaml
driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/centos_4.18.0-373.el8.x86_64_1.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/centos_4.18.0-365.el8.x86_64_1.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/centos_4.18.0-373.el8.x86_64_1.yaml
driverkit/config/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/centos_4.18.0-365.el8.x86_64_1.yaml
driverkit/config/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/centos_4.18.0-373.el8.x86_64_1.yaml

Adding configs for:
- 4.18.0-365.el8.x86_64
- 4.18.0-373.el8.x86_64

Add latest CentOS 8-Stream configs

---

config/config.yaml
config/jobs/arm-build/arm-build.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/jobs/lifecycle-bot/periodic-close.yaml
config/jobs/lifecycle-bot/periodic-rotten.yaml
config/jobs/lifecycle-bot/periodic-stale.yaml
config/jobs/peribolos/peribolos.yaml
config/prow/branchprotector.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/547c14a0ca...949f7bddd3

Bump prow from v20220408-547c14a0ca to v20220414-949f7bddd3

---

config/org.yaml

update(config/org.yaml): add Andreagit97

---

config/jobs/branchprotector/branchprotector.yaml

Fix config file path for branchprotector

---

images/update-maintainers/persons.json

update(persons): add Andrea Terzolo

---

config/config.yaml
config/jobs/arm-build/arm-build.yaml
config/jobs/branchprotector/branchprotector.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/jobs/lifecycle-bot/periodic-close.yaml
config/jobs/lifecycle-bot/periodic-rotten.yaml
config/jobs/lifecycle-bot/periodic-stale.yaml
config/jobs/peribolos/peribolos.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/949f7bddd3...6d355b2d97

Bump prow from v20220414-949f7bddd3 to v20220506-6d355b2d97

---

images/build-drivers/Dockerfile

update: updated driverkit to 0.8.0.

---

.circleci/config.yml

ci(circleci/terrascan): fix bin download url

---

images/update-maintainers/persons.json

Signed-off-by: Frederico Araujo <frederico.araujo@ibm.com>

update(persons): add Fred Araujo

---

images/update-maintainers/persons.json

Add Secureworks to persons.json

---

driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/ubuntu-generic_5.15.0-27-generic_28.yaml
driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/ubuntu-generic_5.15.0-27-generic_28.yaml
driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/ubuntu-generic_5.15.0-27-generic_28.yaml
driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/ubuntu-generic_5.15.0-27-generic_28.yaml
driverkit/config/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/ubuntu-generic_5.15.0-27-generic_28.yaml

Signed-off-by: Olivier Campeau <oli.campeau@gmail.com>

add ubuntu-generic_5.15.0-27-generic_28

---

images/update-maintainers/persons.json

Signed-off-by: TPT <terylt@ibm.com>
added Teryl to persons.json

update(persons): add Teryl Taylor

---

config/org.yaml

chore(config/org.yaml): add dwindsor as driverkit maintainer

---

config/jobs/update-dbg/update-dbg.yaml
driverkit/Makefile
driverkit/README.md
driverkit/utils/checkfiles
driverkit/utils/generate
driverkit/utils/scrape_and_generate
images/update-dbg/Dockerfile
images/update-dbg/Makefile
images/update-dbg/entrypoint.sh

Add job to generate configs from crawled kernels

---

config/jobs/build-prow-images/build-images.yaml
config/jobs/build-prow-images/publish-images.yaml

ci: add missing update-dbg image build and push jobs

---

config/config.yaml

See https://github.com/falcosecurity/falco/pull/1997

fix(config): update required_status_checks for Falco

---

config/jobs/update-falco-k8s-manifests/update-falco-k8s-manifests.yaml

fix(config/jobs): correct repo and branch for update-falco-k8s-manifests

---

config/jobs/build-prow-images/build-images.yaml
config/jobs/build-prow-images/publish-images.yaml
config/jobs/update-kernels/update-kernels.yaml
images/update-kernels/Dockerfile
images/update-kernels/Makefile
images/update-kernels/entrypoint.sh

new(job,images): ported kernel-crawler action to prow.

---

images/autobump/Dockerfile
images/update-dbg/Dockerfile
images/update-kernels/Dockerfile

update(images): updated prcreator images to golang 1.18.

---

config/clusters/ecr-iam.tf

cleanup(config): dropped reference to arm-build job.

---

config/org.yaml

Signed-off-by: <me@leonardograsso.com>

fix(config): correct wrong team binding for the libs-sdk-go repo

---

images/update-kernels/entrypoint.sh

fix(images): fix update-kernels image entrypoint python commands.

---

images/update-kernels/entrypoint.sh

fix(images): update-kernels entrypoint should use main branch.

---

driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/ubuntu-generic_5.4.0-100-generic_113.yaml
driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/ubuntu-generic_5.4.0-104-generic_118.yaml
driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/ubuntu-generic_5.4.0-105-generic_119.yaml
driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/ubuntu-generic_5.4.0-107-generic_121.yaml
driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/ubuntu-generic_5.4.0-109-generic_123.yaml
driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/ubuntu-generic_5.4.0-110-generic_124.yaml
driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/ubuntu-generic_5.4.0-113-generic_127.yaml
driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/ubuntu-generic_5.4.0-117-generic_132.yaml
driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/ubuntu-generic_5.4.0-91-generic_102.yaml
driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/ubuntu-generic_5.4.0-92-generic_103.yaml
driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/ubuntu-generic_5.4.0-94-generic_106.yaml
driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/ubuntu-generic_5.4.0-97-generic_110.yaml
driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/ubuntu-generic_5.4.0-99-generic_112.yaml

Signed-off-by: Vicente J. Jiménez Miras <vjjmiras@gmail.com>

20220610 - drivers for Ubuntu 20.04

---

config/org.yaml

update(config): update falco-maintainers team

---

driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/amazonlinux2_4.14.275-207.503.amzn2.x86_64_1.yaml
driverkit/config/39ae7d40496793cf3d3e7890c9bbdc202263836b/amazonlinux2_4.14.275-207.503.amzn2.x86_64_1.yaml
driverkit/config/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/amazonlinux2_4.14.275-207.503.amzn2.x86_64_1.yaml

Signed-off-by: MCBarzi <mcbarzi@github.com>

Adding new driverkit for amazonlinux2_4.14.275-207.503.amzn2.x86_64_1

---

config/org.yaml

See https://github.com/falcosecurity/libs/pull/480

update(config/org.yaml): add Molter73

---

images/update-maintainers/persons.json

Added Mauro Ezequiel Moltrasio (myself) to persons.json

update(persons): add Mauro Ezequiel Moltrasio

---

config/org.yaml

See https://github.com/falcosecurity/evolution/issues/154
/cc @maxgio92

update(config/org.yaml): archiving `template-repository` repo

---

config/org.yaml

See https://github.com/falcosecurity/evolution/issues/160

update(config/org.yaml): archiving `katacoda-scenarios`

---

config/org.yaml

See:
- https://github.com/falcosecurity/evolution/issues/161
- https://github.com/falcosecurity/evolution/issues/162
- https://github.com/falcosecurity/evolution/issues/164

update(config/org): archiving unmaintained repositories

---

config/config.yaml
config/jobs/branchprotector/branchprotector.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/jobs/lifecycle-bot/periodic-close.yaml
config/jobs/lifecycle-bot/periodic-rotten.yaml
config/jobs/lifecycle-bot/periodic-stale.yaml
config/jobs/peribolos/peribolos.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/cf42b99a12...38eaa13df1

Bump prow from v20220721-cf42b99a12 to v20220727-38eaa13df1

---

config/org.yaml
images/update-maintainers/persons.json

See https://github.com/falcosecurity/libs/pull/536#issuecomment-1207801577

update(config/org.yaml): add LucaGuerra

---

config/config.yaml
config/jobs/branchprotector/branchprotector.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/jobs/lifecycle-bot/periodic-close.yaml
config/jobs/lifecycle-bot/periodic-rotten.yaml
config/jobs/lifecycle-bot/periodic-stale.yaml
config/jobs/peribolos/peribolos.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/38eaa13df1...e0ec00dd27

Bump prow from v20220727-38eaa13df1 to v20220805-e0ec00dd27

---

driverkit/utils/build

Signed-off-by: Lyonel Martinez <lyonel.martinez@numberly.com>
you merged the previous a bit too fast :D

feat(driverkit-kube): Build utils can now run on kube

---

config/config.yaml

protect Falco `0.32.2` release branch

update(config.yaml): protect Falco `0.32.2` release branch

---

driverkit/config/2.0.0+driver/x86_64/amazonlinux2_5.4.204-113.362.amzn2.x86_64_1.yaml

adding to the missing 2.0.0 driver
Signed-off-by: Izak R [irivera007](mailto:irivera007@yahoo.com)

adding amazonlinux2_5.4.204-113.362.amzn2

---

config/config.yaml
config/jobs/branchprotector/branchprotector.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/jobs/lifecycle-bot/periodic-close.yaml
config/jobs/lifecycle-bot/periodic-rotten.yaml
config/jobs/lifecycle-bot/periodic-stale.yaml
config/jobs/peribolos/peribolos.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/e0ec00dd27...9414716697

Bump prow from v20220805-e0ec00dd27 to v20220812-9414716697

---

images/update-maintainers/persons.json

See https://github.com/falcosecurity/.github/issues/93

update(images/update-maintainers/persons.json): update `admiral0` affiliation

---

config/org.yaml

update(config/org): add core-maintainers team

---

config/org.yaml

update(config/org.yaml): add jasondellaluce to evolution-maintainers team

---

config/config.yaml
config/jobs/update-falco-k8s-manifests/update-falco-k8s-manifests.yaml
config/jobs/update-maintainers/update-maintainers.yaml
images/update-falco-k8s-manifests/entrypoint.sh
images/update-maintainers/entrypoint.sh

Also fix the update-maintainers job.
Fixes https://github.com/falcosecurity/evolution/issues/178
cc @jasondellaluce

update(evolution repo): switch to main branch

---

config/config.yaml
config/plugins.yaml

See https://github.com/falcosecurity/evolution/issues/178

Update default branch for special repos

---

config/plugins.yaml

update(config/plugins.yaml): kilt does not use release notes

---

config/config.yaml

fix(config): make `kernels` branch of kernel-crawler protected.

---

config/jobs/build-drivers/build-new-minikube.yaml
config/jobs/build-drivers/rebuild-all-minikube.yaml

This PR adds two new jobs to handle the minikube drivers.

update(config/jobs): add prow jobs for minikube drivers

---

images/update-maintainers/entrypoint.sh

fix(images/update-maintainers): correct `GH_REPO_BRANCH` default

---

config/org.yaml

See https://prow.falco.org/log?job=peribolos-post-submit&id=1565594745181310976

fix(config/org.yaml): remove empty fields

---

config/org.yaml

See https://prow.falco.org/log?job=peribolos-post-submit&id=1565617145339973632

fix(config/org.yaml): at least one merge strategy is needed

---

config/config.yaml
config/jobs/branchprotector/branchprotector.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/jobs/lifecycle-bot/periodic-close.yaml
config/jobs/lifecycle-bot/periodic-rotten.yaml
config/jobs/lifecycle-bot/periodic-stale.yaml
config/jobs/peribolos/peribolos.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/9414716697...5db9cf5fa2

Bump prow from v20220812-9414716697 to v20220901-5db9cf5fa2

---

config/org.yaml

update(config/org.yaml): add Andrea Terzolo as a Falco maintainer

---

images/update-kernels/entrypoint.sh

fix(images): fixed update_kernels image entrypoint paths.

---

config/jobs/update-kernels/update-kernels.yaml
images/update-kernels/entrypoint.sh

Always run crawler from main branch, because that's the only branch with actual code.
Before opening the PR, checkout the kernels branch.

fix(config,images): fixed update-kernels entrypoint.

---

config/config.yaml

This PR add some of the libs CI checks as required

update(config.yaml): set some libs CI checks as required

---

config/org.yaml

Signed-off-by: Lorenzo Susini <susinilorenzo1@gmail.com>
Required for https://github.com/falcosecurity/falcoctl/pull/137

update(config): add loresuso to org members

---

config/org.yaml

As per [falcoctl OWNERS](https://github.com/falcosecurity/falcoctl/blob/232920e03e9abdb19b3b22d9785fdf0f1d2d09e9/OWNERS#L2-L6)

update(org.yalm): sync falcoctl owners

---

images/update-kernels/entrypoint.sh

ci(update-kernels): increase verbosity

---

images/build-plugins/on-registry-changed.sh

fix(build-plugins/on-registry-changed.sh): correct checkout path

---

config/jobs/update-kernels/update-kernels.yaml

chore(config): change update-kernels job cron.

---

images/update-kernels/Dockerfile

update(images): bump kernel-crawler image tag.

---

config/config.yaml
config/jobs/branchprotector/branchprotector.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/jobs/lifecycle-bot/periodic-close.yaml
config/jobs/lifecycle-bot/periodic-rotten.yaml
config/jobs/lifecycle-bot/periodic-stale.yaml
config/jobs/peribolos/peribolos.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/5db9cf5fa2...08c3d7a2a6

Bump prow from v20220901-5db9cf5fa2 to v20221007-08c3d7a2a6

---

images/update-kernels/Dockerfile

update(images): bumped kernel-crawler image to 0.1.3.

---

config/config.yaml

update(config.yaml): protect Falco 0.33.0 branch

---

config/config.yaml
config/jobs/branchprotector/branchprotector.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/jobs/lifecycle-bot/periodic-close.yaml
config/jobs/lifecycle-bot/periodic-rotten.yaml
config/jobs/lifecycle-bot/periodic-stale.yaml
config/jobs/peribolos/peribolos.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/08c3d7a2a6...f54c8765a7

Bump prow from v20221007-08c3d7a2a6 to v20221014-f54c8765a7

---

config/org.yaml

https://github.com/kris-nova :point_right: https://github.com/krisnova
@krisnova :hugs:

fix(config/org.yaml): GH username changed

---

config/config.yaml

update(config.yaml): protect v0.32 website snapshot branch

---

config/jobs/update-drivers-website/update-drivers-website.yaml
images/update-drivers-website/Dockerfile
images/update-drivers-website/entrypoint.sh

I am still unsure about whether we will have proper `aws` secrets to push on s3 @maxgio92

fix(images): fixed update-drivers-website image build and run.

---

config/config.yaml

update(config): renamed master to main in event-generator.

---

config/jobs/build-drivers/build-new-ubuntu-azure.yaml
config/jobs/build-drivers/build-new-ubuntu-gcp.yaml
config/jobs/build-drivers/build-new-ubuntu-gke.yaml
config/jobs/build-drivers/rebuild-all-ubuntu-azure.yaml
config/jobs/build-drivers/rebuild-all-ubuntu-gcp.yaml
config/jobs/build-drivers/rebuild-all-ubuntu-gke.yaml

new(config): added ubuntu azure, gke, gcp flavors jobs.

---

config/config.yaml
config/jobs/branchprotector/branchprotector.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/jobs/lifecycle-bot/periodic-close.yaml
config/jobs/lifecycle-bot/periodic-rotten.yaml
config/jobs/lifecycle-bot/periodic-stale.yaml
config/jobs/peribolos/peribolos.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/f54c8765a7...f6c02074bb

Bump prow from v20221014-f54c8765a7 to v20221021-f6c02074bb

---

images/update-syscalls/Dockerfile

fix(images): fixed update-syscalls image deps.

---

images/update-kernels/Dockerfile

update(images): bump kernel-crawler image version.

---

config/config.yaml
config/jobs/branchprotector/branchprotector.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/jobs/lifecycle-bot/periodic-close.yaml
config/jobs/lifecycle-bot/periodic-rotten.yaml
config/jobs/lifecycle-bot/periodic-stale.yaml
config/jobs/peribolos/peribolos.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/f6c02074bb...a8625c1f93

Bump prow from v20221021-f6c02074bb to v20221028-a8625c1f93

---

config/org.yaml

Signed-off-by: Logan Bond <lbond@secureworks.com>

add EXONER4TED as org member

---

images/update-kernels/Dockerfile

update(images): bumped kernel-crawler to latest bugfix.

---

images/update-syscalls/Dockerfile

chore(images): moved syscalls-bumper under falcosecurity.

---

config/org.yaml

fix(config): add syscalls-bumper-maintainers section.

---

config/config.yaml
config/jobs/branchprotector/branchprotector.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/jobs/lifecycle-bot/periodic-close.yaml
config/jobs/lifecycle-bot/periodic-rotten.yaml
config/jobs/lifecycle-bot/periodic-stale.yaml
config/jobs/peribolos/peribolos.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/a8625c1f93...4497ace285

Bump prow from v20221028-a8625c1f93 to v20221104-4497ace285

---

images/update-kernels/Dockerfile

update(images): updated crawler to 0.4.3.

---

images/update-kernels/Dockerfile

update(images): updated kernel crawler to 0.4.4.

---

config/config.yaml
config/jobs/branchprotector/branchprotector.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/jobs/lifecycle-bot/periodic-close.yaml
config/jobs/lifecycle-bot/periodic-rotten.yaml
config/jobs/lifecycle-bot/periodic-stale.yaml
config/jobs/peribolos/peribolos.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/4497ace285...fe4f3e2158

Bump prow from v20221104-4497ace285 to v20221111-fe4f3e2158

---

config/config.yaml
config/jobs/branchprotector/branchprotector.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/jobs/lifecycle-bot/periodic-close.yaml
config/jobs/lifecycle-bot/periodic-rotten.yaml
config/jobs/lifecycle-bot/periodic-stale.yaml
config/jobs/peribolos/peribolos.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/fe4f3e2158...3815e13b72

Bump prow from v20221111-fe4f3e2158 to v20221117-3815e13b72

---

config/config.yaml

update(config): update protected branches for libs 0.9.2 / falco 0.33.1 release

---

images/update-syscalls/entrypoint.sh

chore(images): updated update-syscalls PR title.

---

config/org.yaml

Adding myself to the lib-maintainers after a [successful voting](https://github.com/falcosecurity/libs/pull/739#issuecomment-1333506651).
I am happy to join the team! Thanks.
Signed-off-by: Hendrik Brueckner <brueckner@de.ibm.com>

update(config/org.yaml): add hbrueckner as member to lib-maintainers

---

config/config.yaml

fix(config): fixed driverkit required_status_check.

---

config/org.yaml

chore(config): add fededp as test-infra-maintainers to org.

---

images/update-kernels/Dockerfile

update(images): updated kernel-crawler image to latest tag.

---

images/update-kernels/Dockerfile
images/update-kernels/entrypoint.sh

Added support for BottleRocket + dropped non-driverkit formats.

update(images): bump kernel-crawler to 0.5.0.

---

README.md
driverkit/README.md

This PR tries to improve the guide for contributing DBG configurations and link to it on the home of this repository.

Improve the driver configs contribution documentation

---

config/jobs/build-drivers/build-new-bottlerocket.yaml
config/jobs/build-drivers/rebuild-all-bottlerocket.yaml
images/build-drivers/Dockerfile

new(config): added build-drivers jobs for bottlerocket.

---

config/config.yaml
config/jobs/branchprotector/branchprotector.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/jobs/lifecycle-bot/periodic-close.yaml
config/jobs/lifecycle-bot/periodic-rotten.yaml
config/jobs/lifecycle-bot/periodic-stale.yaml
config/jobs/peribolos/peribolos.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/3815e13b72...5c7fbe528a

Bump prow from v20221117-3815e13b72 to v20221220-5c7fbe528a

---

config/config.yaml
config/jobs/branchprotector/branchprotector.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/jobs/lifecycle-bot/periodic-close.yaml
config/jobs/lifecycle-bot/periodic-rotten.yaml
config/jobs/lifecycle-bot/periodic-stale.yaml
config/jobs/peribolos/peribolos.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/5c7fbe528a...0de7d15106

Bump prow from v20221220-5c7fbe528a to v20230106-0de7d15106

---

config/clusters/eks_variables.tf

chore(config/clusters/eks): add fededp as prow eks admin user

---

images/update-rules-index/Dockerfile

The image publishing job should start upon any modification to the image, meaning this would be enough :)

update(images): trigger publish for update-rules-index

---

config/config.yaml

chore(config): set release/0.10.x as protected branch.

---

config/config.yaml
config/jobs/branchprotector/branchprotector.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/jobs/lifecycle-bot/periodic-close.yaml
config/jobs/lifecycle-bot/periodic-rotten.yaml
config/jobs/lifecycle-bot/periodic-stale.yaml
config/jobs/peribolos/peribolos.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/0de7d15106...8f2ffbe0d4

Bump prow from v20230106-0de7d15106 to v20230113-8f2ffbe0d4

---

config/clusters/eks_variables.tf

As per title. Thanks @maxgio92 and @FedeDP for your assistance!

new(eks): add luca.guerra to the EKS test-infra cluster

---

config/config.yaml

update(config): updated client-go required status check.

---

config/config.yaml

update(config): updated falco-exporter required status checks.

---

config/config.yaml

update(config): added event-generator required status checks.

---

config/org.yaml

update(org.yaml): add jasondellaluce to libs-maintainers

---

driverkit/Makefile

fix(driverkit): fixed dbg cleanup.

---

driverkit/Makefile

fix(dbg): remove cleanup targets overlap

---

config/plugins.yaml

Signed-off-by: Roberto Scolaro <roberto.scolaro21@gmail.com>

update(config): initial rules prow configuration

---

config/config.yaml
config/jobs/branchprotector/branchprotector.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/jobs/lifecycle-bot/periodic-close.yaml
config/jobs/lifecycle-bot/periodic-rotten.yaml
config/jobs/lifecycle-bot/periodic-stale.yaml
config/jobs/peribolos/peribolos.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/8f2ffbe0d4...5ca317e736

Bump prow from v20230113-8f2ffbe0d4 to v20230120-5ca317e736

---

config/config.yaml
config/plugins.yaml

* Added `milestone` plugin to falcoctl
* Added `test` as required status check to falcoct
/cc @leogr

chore: falcoctl plugins and config

---

config/config.yaml
config/jobs/branchprotector/branchprotector.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/jobs/lifecycle-bot/periodic-close.yaml
config/jobs/lifecycle-bot/periodic-rotten.yaml
config/jobs/lifecycle-bot/periodic-stale.yaml
config/jobs/peribolos/peribolos.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/5ca317e736...c2d8597baa

Bump prow from v20230120-5ca317e736 to v20230127-c2d8597baa

---

images/build-drivers/Dockerfile

update(images): updated driverkit to v0.11.1.

---

config/org.yaml

Signed-off-by: Vicente J. Jiménez Miras <vjjmiras@gmail.com>

update: adding vjjmiras to the members section of the org.yaml file

---

config/clusters/ecr.tf

This PR removes update-kernels job from ecr (see #987).

cleanup(config/clusters/ecr): removed update-kernels from ecr.

---

config/config.yaml

update(config): protect Falco release branch 0.34.0

---

config/config.yaml
config/jobs/branchprotector/branchprotector.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/jobs/lifecycle-bot/periodic-close.yaml
config/jobs/lifecycle-bot/periodic-rotten.yaml
config/jobs/lifecycle-bot/periodic-stale.yaml
config/jobs/peribolos/peribolos.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/c2d8597baa...2cc77b11a8

Bump prow from v20230127-c2d8597baa to v20230202-2cc77b11a8

---

config/config.yaml

update(config): protect falco-website branch v0.33

---

config/org.yaml

See https://github.com/falcosecurity/evolution/pull/248.

 fix(config): add incertum to the `core-maintainers` team

---

config/prow/cluster-autoscaler.yaml

part of https://github.com/kubernetes/k8s.io/issues/4780
/assign @leogr

update k8s registry domain

---

config/config.yaml

protect Falco `0.34.x` release branch

update(config): protect falco release branch

---

config/config.yaml
config/jobs/branchprotector/branchprotector.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/jobs/lifecycle-bot/periodic-close.yaml
config/jobs/lifecycle-bot/periodic-rotten.yaml
config/jobs/lifecycle-bot/periodic-stale.yaml
config/jobs/peribolos/peribolos.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/f319bbff04...1f9eebbd96

Bump prow from v20230209-f319bbff04 to v20230215-1f9eebbd96

---

config/config.yaml
config/jobs/branchprotector/branchprotector.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/jobs/lifecycle-bot/periodic-close.yaml
config/jobs/lifecycle-bot/periodic-rotten.yaml
config/jobs/lifecycle-bot/periodic-stale.yaml
config/jobs/peribolos/peribolos.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/1f9eebbd96...60dadd267c

Bump prow from v20230215-1f9eebbd96 to v20230224-60dadd267c

---

config/config.yaml
config/jobs/branchprotector/branchprotector.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/jobs/lifecycle-bot/periodic-close.yaml
config/jobs/lifecycle-bot/periodic-rotten.yaml
config/jobs/lifecycle-bot/periodic-stale.yaml
config/jobs/peribolos/peribolos.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/60dadd267c...d699058042

Bump prow from v20230224-60dadd267c to v20230303-d699058042

---

config/clusters/iam.tf

In order to allow for Falcosidekick to push its images to ECR via GitHub Actions, GHA needs appropriate permissions to access the falcosidekick public repo. This PR adds the necessary configuration to terraform.

new(tf): allow the falcosidekick repository to push to its own ECR repo

---

images/build-drivers/Dockerfile

update(images): update driverkit to latest version.

---

config/config.yaml
config/jobs/branchprotector/branchprotector.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/jobs/lifecycle-bot/periodic-close.yaml
config/jobs/lifecycle-bot/periodic-rotten.yaml
config/jobs/lifecycle-bot/periodic-stale.yaml
config/jobs/peribolos/peribolos.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/d699058042...adf0d41516

Bump prow from v20230303-d699058042 to v20230309-adf0d41516

---

config/prow/monitoring/grafana_ingress.yaml
config/prow/monitoring/prow_alertmanager.yaml
config/prow/monitoring/prow_prometheus.yaml

Fixes #1029 
/cc @FedeDP @cappellinsamuele @jasondellaluce

fix(config/prow/monitoring): set existent standard storageclass

---

config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/tide.yaml

/cc @jasondellaluce @FedeDP @cappellinsamuele 
Fixes #1027

feat(config/prow): expose metrics ports for prometheus servicemonitors

---

config/prow/kube-state-metrics_deployment.yaml
config/prow/kube-state-metrics_rbac.yaml
config/prow/kube-state-metrics_service.yaml

fix(config/prow): add kube-state-metrics deployment

---

.github/workflows/validate_manifests.yml

new(ci): added manifests validation ci

---

config/config.yaml
config/jobs/branchprotector/branchprotector.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/jobs/lifecycle-bot/periodic-close.yaml
config/jobs/lifecycle-bot/periodic-rotten.yaml
config/jobs/lifecycle-bot/periodic-stale.yaml
config/jobs/peribolos/peribolos.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

Included changes: https://github.com/kubernetes/test-infra/compare/adf0d41516...6d54c174f4

Bump prow from v20230309-adf0d41516 to v20230315-6d54c174f4

---

config/prow/monitoring/node-exporter_servicemonitors.yaml
config/prow/node-exporter_deployment.yaml
config/prow/node-exporter_rbac.yaml
config/prow/node-exporter_service.yaml

Added Prometheus Node-exporter to get hw cluster metrics.
Fixes #1036

new(config/prow): added prometheus node exporter

---

config/prow/monitoring/grafana_deployment.yaml

fix(config/prow/monitoring/nodes): mount missing grafana dashboard configmaps

---

config/prow/monitoring/grafana_deployment.yaml

Bumped Grafana version to enable node-exporter dashboards.

update(config/prow/monitoring): bumped grafana version

---

config/prow/monitoring/grafana_ingress.yaml

feat(prow/monitoring): expose grafana via https and wellknown hostname

---

config/org.yaml

Adding myself to the kernel-crawler org as requested by @FedeDP here: https://github.com/falcosecurity/kernel-crawler/pull/108#issuecomment-1494084818

adding EXONER4TED to kernel-crawler org

---

config/jobs/build-drivers/build-new-amazonlinux.yaml
config/jobs/build-drivers/build-new-bottlerocket.yaml
config/jobs/build-drivers/build-new-centos.yaml
config/jobs/build-drivers/build-new-debian.yaml
config/jobs/build-drivers/build-new-fedora.yaml
config/jobs/build-drivers/build-new-minikube.yaml
config/jobs/build-drivers/build-new-ubuntu-aws.yaml
config/jobs/build-drivers/build-new-ubuntu-azure.yaml
config/jobs/build-drivers/build-new-ubuntu-gcp.yaml
config/jobs/build-drivers/build-new-ubuntu-generic.yaml
config/jobs/build-drivers/build-new-ubuntu-gke.yaml

The star character makes the whole expression to matche even when the preceding match do not.
Fixes #1072

fix(config/jobs/build-drivers): set correct diff filename regex

---

.github/workflows/update-drivers-website.yml

This PR adds `update-drivers-website` pipeline. The job is currently managed by prow.

new(ci): added update-drivers-website gha.

---

config/config.yaml

This PR adds `run-tests` CI pipeline to the required status check on [plugin-sdk-go](https://github.com/falcosecurity/plugin-sdk-go) repo.

update(config/config.yaml): added run-tests ci job to plugin-sdk-go repo.

---

config/clusters/prow.tfvars

This PR extends both the `x86` and `arm64` autoscaling groups capacities.

chore(config/clusters/prow.tfvars): increased asg capacities.

---

tools/update-drivers-website/index.html
tools/update-drivers-website/updateDriversWebsite.go

Add the last update date in the top right corner + a clear search button in the driver list website

add last update date + clear search button

---

config/clusters/iam.tf

This is remarkably similar to the falcosidekick one, that's because it's what we need for https://github.com/falcosecurity/falco/pull/2501 . Will need to be merged after https://github.com/falcosecurity/test-infra/pull/1102 .

new(iam): add Falco ECR access

---

config/clusters/iam.tf

As per title, this is related to the new Falco GitHub Actions release/CI pipeline.
cc @FedeDP

new(iam): add Falco CloudFront access

---

config/clusters/iam.tf

oops :sweat_smile: 
cc @FedeDP @maxgio92

fix(iam): correct falco repository name

---

config/clusters/iam.tf

fix(iam): add falco-driver-loader and falco-no-driver ECR

---

config/jobs/build-drivers/build-new-almalinux.yaml
config/jobs/build-drivers/build-new-amazonlinux.yaml
config/jobs/build-drivers/build-new-bottlerocket.yaml
config/jobs/build-drivers/build-new-centos.yaml
config/jobs/build-drivers/build-new-debian.yaml
config/jobs/build-drivers/build-new-fedora.yaml
config/jobs/build-drivers/build-new-minikube.yaml
config/jobs/build-drivers/build-new-ubuntu-aws.yaml
config/jobs/build-drivers/build-new-ubuntu-azure.yaml
config/jobs/build-drivers/build-new-ubuntu-gcp.yaml
config/jobs/build-drivers/build-new-ubuntu-generic.yaml
config/jobs/build-drivers/build-new-ubuntu-gke.yaml

update(config/jobs/build-drivers): added tolerations to build-drivers jobs configurations.

---

config/jobs/build-drivers/build-new-almalinux.yaml
config/jobs/build-drivers/build-new-amazonlinux.yaml
config/jobs/build-drivers/build-new-bottlerocket.yaml
config/jobs/build-drivers/build-new-centos.yaml
config/jobs/build-drivers/build-new-debian.yaml
config/jobs/build-drivers/build-new-fedora.yaml
config/jobs/build-drivers/build-new-minikube.yaml
config/jobs/build-drivers/build-new-ubuntu-aws.yaml
config/jobs/build-drivers/build-new-ubuntu-azure.yaml
config/jobs/build-drivers/build-new-ubuntu-gcp.yaml
config/jobs/build-drivers/build-new-ubuntu-generic.yaml
config/jobs/build-drivers/build-new-ubuntu-gke.yaml

update(config/jobs/build-drivers): updated arm jobs tolerations for single AZ taint.

---

config/clusters/.terraform.lock.hcl
config/clusters/TERRAFORM.md
config/clusters/eks.tf
config/clusters/eks_variables.tf
config/clusters/terraform_versions.tf
config/jobs/build-drivers/build-new-almalinux.yaml
config/jobs/build-drivers/build-new-amazonlinux.yaml
config/jobs/build-drivers/build-new-bottlerocket.yaml
config/jobs/build-drivers/build-new-centos.yaml
config/jobs/build-drivers/build-new-debian.yaml
config/jobs/build-drivers/build-new-fedora.yaml
config/jobs/build-drivers/build-new-minikube.yaml
config/jobs/build-drivers/build-new-ubuntu-aws.yaml
config/jobs/build-drivers/build-new-ubuntu-gcp.yaml
config/jobs/build-drivers/build-new-ubuntu-generic.yaml
config/jobs/build-drivers/build-new-ubuntu-gke.yaml

> Note: this will re-create all the node groups, besides adding a new one deployed in single-AZ.
/cc @zuc @FedeDP @cappellinsamuele

feat(aws/eks): add new and move jobs nodes to single-az

---

tools/deploy_terraform.sh

fix(tools/deploy_terraform.sh): update bin download to current tf reqs

---

config/clusters/eks_variables.tf

update(config): update k8s to 1.21.

---

config/prow/arc/arm-runner.yaml

fix(config/prow/arc): add selection and tolerations for jobs on arm nodes

---

config/clusters/prow.tfvars

perf(config/clusters): tune node groups max horizontal capacity

---

config/jobs/build-drivers/build-new-amazonlinux.yaml

fix(jobs/build-drivers/al2023): add missing node tolerations

---

config/config.yaml

update: set release 0.11.x as protected

---

config/org.yaml

update(org): add incertum (Melissa Kilby) to rules and falco maintainers
rules repo https://github.com/falcosecurity/rules/pull/81
falco repo https://github.com/falcosecurity/falco/pull/2629

update(org): add incertum (Melissa Kilby) to rules and falco maintainers

---

config/config.yaml
config/org.yaml
config/plugins.yaml

/hold until the repo is donated.

new(config): add kernel-testing repo.

---

config/config.yaml

update(config): protect libs 0.12.x

---

config/config.yaml

This is part of our CI migration to GitHub actions.

update(config.yaml): switch required jobs from CircleCI to GHA for Falco

---

config/config.yaml

I'm struggling to figure out what the right nomenclature is for GitHub actions to properly match the required jobs by name. I tested these ones manually through the GH UI, so I hope this will be the last attempt.

update(config.yaml): right naming from required Falco jobs (2)

---

config/config.yaml

remove falcosidekick-ui checks, I'm replacing CircleCI by Github Actions and it blocks the PR

remove falcosidekick-ui checks

---

config/config.yaml

add checks for falcosidekick-ui with gha

add checks for falcosidekick-ui with gha

---

config/org.yaml

See: https://github.com/falcosecurity/evolution/issues/303

Update (org.yaml): add rohith as a member 

---

config/config.yaml

/hold until the end of the release

update: set release branch 0.13.x as protected

---

config/config.yaml

set some libs CI tests as required

update(config): set some libs CI tests as required

---

config/clusters/iam.tf

As per title.
ref missing permissions: https://github.com/falcosecurity/falcosidekick-ui/actions/runs/6174459638
cc @FedeDP @Issif

new(tf): add configuration for falcosidekick-ui

---

config/config.yaml
config/jobs/branchprotector/branchprotector.yaml
config/jobs/check-prow-config/check-prow-config.yaml
config/jobs/lifecycle-bot/periodic-close.yaml
config/jobs/lifecycle-bot/periodic-rotten.yaml
config/jobs/lifecycle-bot/periodic-stale.yaml
config/jobs/peribolos/peribolos.yaml
config/prow/crier.yaml
config/prow/deck.yaml
config/prow/ghproxy.yaml
config/prow/hook.yaml
config/prow/horologium.yaml
config/prow/needs-rebase.yaml
config/prow/prow-controller-manager.yaml
config/prow/sinker.yaml
config/prow/statusreconciler.yaml
config/prow/tide.yaml

gcr.io/k8s-prow/ changes: https://github.com/kubernetes/test-infra/compare/6d54c174f4...e9e5d470a5 (2023&#x2011;03&#x2011;15 → 2023&#x2011;09&#x2011;01)
/cc

Update Prow to v20230901-e9e5d470a5

---

config/config.yaml

As per title, following the release process

chore(config): protect v0.35 branch on falco-website

---

config/distribution/distribution.tf
config/distribution/files/index.html
config/distribution/files/s3-list.js

The current version of the s3-bucket-listing script does not display our bucket properly. Therefore we are going to vendor the previous commit in our repository, retaining the copyright notice of course.

update(distribution): vendor s3-bucket-listing

---

driverkit/config/4.0.0+driver/x86_64/ubuntu-generic_4.15.0-216-generic_227.yaml
driverkit/config/5.0.1+driver/x86_64/ubuntu-generic_4.15.0-216-generic_227.yaml
driverkit/config/6.0.1+driver/x86_64/ubuntu-generic_4.15.0-216-generic_227.yaml

add build config for ubuntu-generic_4.15.0-216-generic_227

new(driverkit/config): add build config for ubuntu-generic_4.15.0-216-generic_227

---

Makefile
config/prow/cert-manager.yaml
config/prow/monitoring/Makefile
config/prow/monitoring/mixins/Makefile
images/build-plugins/on-registry-changed.sh
images/update-dbg/entrypoint.sh
images/update-jobs/test.sh
images/update-maintainers/entrypoint.sh
images/update-rules-index/on-registry-changed.sh
prow/update-jobs/main.go
tools/clean_prowjobs.sh
tools/create_ecr.sh
tools/delete.sh
tools/delete_local_prowjob.sh
tools/deploy_prow.sh
tools/deploy_terraform.sh
tools/local_prowjob.sh
tools/push_all_images.sh
tools/update-drivers-website/updateDriversWebsite.go
tools/util.sh

See https://github.com/falcosecurity/evolution/issues/318

docs: add license headers and spdx id

---

config/org.yaml

See here: https://github.com/falcosecurity/kernel-testing/pull/72

update(config/org.yaml): add therealbobo as a member

---

config/config.yaml

follow up #1261
looks like needs to be the full name

fix status check

---

config/config.yaml

follow up #1262 
lets try again
/assign @leogr @LucaGuerra

update chart github check

---

config/org.yaml

As per title. Following from https://github.com/falcosecurity/falco-website/pull/1192

update(org): add myself as a falco-website member

---

config/config.yaml

new(config): updated libs required status checks.

---

config/org.yaml

See https://github.com/falcosecurity/evolution/issues/347
/hold for https://github.com/falcosecurity/kilt/pull/89

update(config): archiving `kilt`

---

config/config.yaml
config/org.yaml
config/plugins.yaml

See https://github.com/falcosecurity/evolution/issues/345

update(config): add falcosecurity/cncf-green-review-testing repo

---

config/config.yaml

This PR protects release branch 0.14.x

Protect branch 0.14.x

---

images/build-drivers/Dockerfile
images/update-dbg/Dockerfile

Update dbg-go to https://github.com/falcosecurity/dbg-go/releases/tag/v0.12.4

update(images): bumped dbg-go to latest release.

---

config/config.yaml

update(config): bumped event-generator required status checks.

---

driverkit/config/7.0.0+driver/aarch64/minikube_5.10.57_1_1.30.1.yaml
driverkit/config/7.0.0+driver/x86_64/minikube_5.10.57_1_1.30.0.yaml

trigger the build of minikube drivers

update(config): trigger the build of minikube drivers

---

config/config.yaml

docs(config): protect website v0.36 version

---

config/config.yaml

As per title. This is required to merge https://github.com/falcosecurity/falco/pull/3048

update(config): remove test-dev-packages (static) requirement

---

config/distribution/playground.tf
config/distribution/variables.tf

In order to publish on play.falco.org we need:
* An S3 bucket to publish the files (publicly readable)
* A Cloudfront Distribution to distribute them
* A valid TLS certificate
This PR adds everything that is needed

new(config): create distribution for play.falco.org

---

config/clusters/iam.tf

feat(iam): add infra reader role for gha oidc

---

config/org.yaml

See https://github.com/falcosecurity/plugins/pull/437
cc @FedeDP

update(org.yaml): adding sboschman to falcosecurity/plugins/k8saudit-gke

---

config/jobs/update-github-teams/peribolos-syncer-test-infra-pre-test.yaml

chore(config/jobs): set branch for update-github-teams test job

---

config/plugins.yaml

As per title, this allows the bot to change or update milestone

chore(config): add milestone plugin to falco-website

---

config/config.yaml

chore(config): protect Falco 0.38.x release branch

---

config/org.yaml

See https://github.com/falcosecurity/rules/pull/247

update(org.yaml): add darryk10 to rules-maintainers

---

config/config.yaml

update(config): protect website 0.37 branch

---

config/config.yaml

See https://github.com/falcosecurity/event-generator/issues/213

update(config): add protected branch to event-generator for GSoC2024

---

config/prow/alb_controller.yaml
config/prow/prowjob_custromresourcedefinition.yaml

Reverts falcosecurity/test-infra#1530

Revert "update(config/prow): update extensions version to v1"

---

config/org.yaml

See https://github.com/falcosecurity/falco/pull/3264

update(config/org.yaml): invite sgaist to falcosecurity GH org

---

config/org.yaml

See https://github.com/falcosecurity/falco/pull/3264

update(config/org.yaml): add sgaist to `falco` maintainers team

---

config/org.yaml

Adding myself as `falcoctl` and `core` maintainer after this PR was merged https://github.com/falcosecurity/falcoctl/pull/614
Thank you!

update(config/org.yaml): add loresuso to falcoctl and core maintainers

---

config/config.yaml

set format code job as required

update(config): set format code job as required

---

config/org.yaml

See https://github.com/falcosecurity/evolution/issues/403

update(config/org.yaml): add IgorEulalio

---

config/org.yaml

See https://github.com/falcosecurity/evolution/issues/405
/hold (waiting for other PRs)

update(config/org.yaml): add mrgian

---

config/org.yaml

as per title and vote in https://github.com/falcosecurity/plugins/pull/532

update(docs): add myself as plugins maintainer

---

OWNERS

Over the last couple of years I have contributed to this repo, especially with security/auth scripts. As a core maintainer, I would like to help with maintenance of this repo.

update(docs): add LucaGuerra as owner

---

config/config.yaml

Add the required checks for Falco Talon PRs

add config for falco-talon

---

config/applications/prometheus-operator-crds.yaml

This commit introduces a new argocd application that handles CRDS for prometheus operator.

new(app): prometheus operator crds

---

config/config.yaml
config/org.yaml
config/plugins.yaml

See https://github.com/falcosecurity/evolution/issues/423
/hold

update(config): add falco-rustlings repo

---

config/org.yaml

See https://github.com/falcosecurity/plugins/pull/554

update(config/org.yaml): add scraly

---

config/config.yaml

update(config): website branch protection for 0.39 snap

---

config/config.yaml

update(config): add required status check for plugin repo

---

config/config.yaml

new(config): add linting & integration pipeline as required for falcoctl repository

---

config/config.yaml

/hold until https://github.com/falcosecurity/libs/pull/2207 and https://github.com/falcosecurity/falco/pull/3482 are reviewed.

chore(config): update libs and falco repositories required checks.

---

config/config.yaml
config/org.yaml
config/plugins.yaml

See https://github.com/falcosecurity/evolution/issues/443
/hold for repo transfer

update(config): add falco-operator repo

---

config/applications/falco.yaml

Testing the latest features of the container and k8smeta plugins.

update(falco): use 0.41.0 preview of falco

---

config/org.yaml

update(config): correct core maintainers members list

---

config/org.yaml

remove incertum (Melissa Kilby)
@leogr

doc(org.yaml): move incertum (Melissa Kilby) to emeritus status

---

config/org.yaml

See https://github.com/falcosecurity/evolution/issues/420 :crying_cat_face:

update(config/org.yaml): archiving `falco-exporter`

---

config/org.yaml

See https://github.com/falcosecurity/libs/pull/2592

update(config): invite `geraldcombs` to the org
