falcosecurity/test-infra

prow/config/configs.yaml
Restrictions apply now to maintainers team.
Please notice that to be working this means that the @falcosecurity/maintainers team needs to explicitly have permissions on the repo for which we are enabling branch protection rules.
Same applies for review dismissal capabilitites.
=> Others branch protections

prow/config/plugins.yaml
=> update: change the self approval flag since the old one was deprecated

prow/config/configs.yaml
As shown in picture, when an external contributor (or anyone using a fork) does a PR the Travis branch check does not trigger so the PR can never be merged.
I disabled this check on Prow with this PR.
Also, that check just gets reported when the other Travis check passes (when it works) so it's not useful to have it in place.
=> fix: do not count on travis branch ci check

prow/config/plugins.yaml
The help plugin provides commands that add or remove the 'help wanted' and the 'good first issue' labels from issues.
Syntax:
```
/[remove-](help|good-first-issue)
```
=> new: enable help plugin

prow/config/configs.yaml, prow/config/plugins.yaml
This PR adds the Prow's configuration and plugins for [falcoctl](https://github.com/falcosecurity/falcoctl).
=> new: enable prow for falcoctl

prow/config/plugins.yaml
On the `falcoctl` and `client-go` repos we'll have the `/lint` command  if this get merged in.
This plugins lints the Go code.
=> new: add golint plugins to go-only repositories

prow/config/plugins.yaml
This PR simply adds the prow milestone plugin to falco (only) and gives the maintainer team the privileges to use the milestone slash commands.
=> new: milestone plugin for falco

prow/config/configs.yaml, prow/config/plugins.yaml
This PR adds PROW support to falco-exporter repository.
Plugins:
- approve
- assign
- blunderbuss
- cat
- dco
- golint
- help
- hold
- label
- lifecycle
- lgtm
- release-note
- require-matching-label
- size
- welcome
- wip
Labels:
- master
- rebase
PR checks & automerge (tide):
- commits must be signed-off
Fixes #63
=> PROW for falco-exporter

prow/config/configs.yaml, prow/config/plugins.yaml
Fixes #66 
This PR adds PROW support to the client-py repository.
Plugins:
- approve
- assign
- blunderbuss
- cat
- dco
- help
- hold
- label
- lifecycle
- lgtm
- release-note
- require-matching-label
- size
- welcome
- wip
Labels:
- master
- rebase
- commits must be signed-off
=> Prow for client-py

prow/config/configs.yaml, prow/config/plugins.yaml
Adding Prow for [falcosecurity/advocacy](https://github.com/falcosecurity/advocacy) repository.
Completes and fixes #69 
/cc @kris-nova 
Plugins:
approve
assign
blunderbuss
branchcleaner
cat
dco
help
hold
label
lifecycle
lgtm
require-matching-label
size
verify-owners
welcome
wip
Labels:
At least a "kind/*" label
master
rebase
must be "approved"
must have a "lgtm" review
commits must be signed-off
must NOT have "do-not-merge/*" labels
must NOT have "needs-rebase" label
=> Prow for advocacy repo

prow/Makefile, prow/cluster/branchprotector.yaml, prow/cluster/deck.yaml, prow/cluster/hook.yaml, prow/cluster/horologium.yaml, prow/cluster/needs-rebase.yaml, prow/cluster/plank.yaml, prow/cluster/sinker.yaml, prow/cluster/tide.yaml, prow/config/configs.yaml, prow/config/plugins.yaml
This PR does two things:
- adds retitle plugin (`/retitle` issues and PR also if they are closed)
- adds `docs-no-retest` plugin
- adds missing `cat` plugins (eg., `/meow` 😸)
- adds `dog` plugin 🐶
- adds `goose` plugin 🦆 
- updates prow components to 2019 02 02 version (to contain such plugins and to obtain fixes/features)
=> update prow images, add retitle, docs-no-retest plugins, cat, dog, goose

prow/config/configs.yaml, prow/config/plugins.yaml
See issue #68 for more details about the configs and plugins this PR puts in place for the cloud-native-security-hub* repositories.
I need @bencer and @nestorsalceda at least to take a look at this before merging.
Fixes #68.
=> prow for cloudnativesecurityhub* repos

prow/config/configs.yaml
=> update(prow/config): falco uses One Flow git branching model now, so poiana only needs to protect its master

.circleci/config.yml
This is step 3 as explained in PR #95 
Introduces the circleci config to automatically build drivers on PR merge.
=> build: driver build grid setup

prow/config/configs.yaml, prow/config/plugins.yaml
We just moved the new https://github.com/falcosecurity/event-generator by @leogr to the org.
This PR adds @poiana to it!
=> enable prow for event-generator

prow/config/configs.yaml, prow/config/plugins.yaml
As decided during [yesterday's community call](https://github.com/falcosecurity/community/blob/master/meeting-notes/2020-04-15.md), we're going to move out from the main Falco repository its `integrations/` directory.
Refs https://github.com/falcosecurity/falco/issues/1114
That directory contains example YAML for using Falco with Kubernetes, or other configs/installation means and examples.
Moving them into the https://github.com/falcosecurity/contrib repository means that such artifacts do not make officially part of any new upcoming Falco release.
But this does not mean they will be abandoned: the community will contribute and maintain them.
The first maintainer for such effort is:
- https://github.com/maxgio92 (already in the org and in the OWNERS file of `contrib` repo) 🙇 
Next steps: …
=> Prow for contrib repo

driverkit/config/96bd9bc560f67742738eb7255aeb4d03046b8045/amazonlinux2_4.14.177-139.253.amzn2.x86_64_1.yaml
The 4.14.177-139.253.amzn2.x86_64_1 version (amazon-eks-node-1.16-v20200507 (ami-05ac566a7ec2378db) is not available at https://dl.bintray.com/falcosecurity/driver/96bd9bc560f67742738eb7255aeb4d03046b8045/ and therefore the  community is not able to deploy falco-probe with eks-1.16 ami
Signed-off-by: Fahad Arshad <fahad.arshad@hobsons.com>
=> new: prebuild module for amazonlinux2 amzn2_4.14.177-139.253_1

driverkit/Makefile, driverkit/config/96bd9bc560f67742738eb7255aeb4d03046b8045/amazonlinux2_4.14.177-139.254.amzn2.x86_64_1.yaml, driverkit/config/96bd9bc560f67742738eb7255aeb4d03046b8045/ubuntu-aws_5.3.0-1019-aws_21.yaml, driverkit/config/96bd9bc560f67742738eb7255aeb4d03046b8045/ubuntu-aws_5.4.0-1011-aws_11.yaml, driverkit/config/96bd9bc560f67742738eb7255aeb4d03046b8045/ubuntu-generic_4.15.0-101-generic_102.yaml, driverkit/config/96bd9bc560f67742738eb7255aeb4d03046b8045/ubuntu-generic_5.3.0-53-generic_47.yaml, driverkit/config/96bd9bc560f67742738eb7255aeb4d03046b8045/ubuntu-generic_5.4.0-31-generic_35.yaml, driverkit/config/a259b4bf49c3330d9ad6c3eed9eb1a31954259a6/amazonlinux2_4.14.177-139.253.amzn2.x86_64_1.yaml, driverkit/config/a259b4bf49c3330d9ad6c3eed9eb1a31954259a6/amazonlinux2_4.14.177-139.254.amzn2.x86_64_1.yaml, driverkit/config/a259b4bf49c3330d9ad6c3eed9eb1a31954259a6/ubuntu-aws_5.3.0-1019-aws_21.yaml, driverkit/config/a259b4bf49c3330d9ad6c3eed9eb1a31954259a6/ubuntu-aws_5.4.0-1011-aws_11.yaml, driverkit/config/a259b4bf49c3330d9ad6c3eed9eb1a31954259a6/ubuntu-generic_4.15.0-101-generic_102.yaml, driverkit/config/a259b4bf49c3330d9ad6c3eed9eb1a31954259a6/ubuntu-generic_5.3.0-53-generic_47.yaml, driverkit/config/a259b4bf49c3330d9ad6c3eed9eb1a31954259a6/ubuntu-generic_5.4.0-31-generic_35.yaml, driverkit/utils/checkfiles, driverkit/utils/parseyaml
Introduced a script to checks:
- the config file names are correct - ie., `config/${driver_version}/${target}_${kernelrelease}_${kernelversion}.yaml`
- the kernel module driver name is correct. - ie., `falco_${target}_${kernelrelease}_${kernelversion}.ko`
- the eBPF probe driver name is correct - ie., `falco_${target}_${kernelrelease}_${kernelversion}.o`
Also, this PR, adds some new drivers for `ubuntu-aws`, `ubuntu-generic`, and `amazonlinux2`.
=> check drivers config conventions + new drivers

prow/config/configs.yaml, prow/config/plugins.yaml
This PR is related to https://github.com/falcosecurity/contrib/pull/24 about the renaming of the `contrib` repo to `evolution`.
Furthermore, it adds custom `kind/sandbox` etc. labels for it (as per https://github.com/falcosecurity/contrib/issues/14),
while at the same moment it also deletes custom `kind/pr` and `kind/issues` labels for https://github.com/falcosecurity/community (which ISSUE_TEMPLATEs do not use anymore).
=> contrib -> evolution

.circleci/config.yml, driverkit/Makefile
- Avoid duplicated .gitignore files for the CircleC workspaces to be merged without conflicts
- Rename failing.log files (for the same reason)
=> fix(driverkit): workspace during publish drivers must not contain file names with same name

.circleci/config.yml
put the CI branch filters (for driverkit/publish job) back to normal, ie. `master` branch.
=> Put the CI branch filters (for driverkit/publish job) back to master

prow/config/configs.yaml, prow/config/plugins.yaml
Depends on https://github.com/falcosecurity/falcosidekick/pull/65 and https://github.com/falcosecurity/falcosidekick/pull/64.
Fixes https://github.com/falcosecurity/test-infra/issues/146.
---
Plugins:
- approve
- assign
- blunderbuss
- cat
- dco
- golint
- goose
- help
- hold
- label
- lifecycle
- lgtm
- release-note
- require-matching-label
- size
- welcome
- wip
Labels:
- master
- rebase
=> Prow setup for falcosidekick

prow/config/configs.yaml, prow/config/plugins.yaml
This deletes the `release-note` plugin for https://github.com/falcosecurity/falcosidekick since @Issif expressed the desire to do not have it.
Fixes #149
=> remove release-note plugin for falcosidekick

driverkit/config/96bd9bc560f67742738eb7255aeb4d03046b8045/amazonlinux2_4.14.181-142.260.amzn2.x86_64_1.yaml
The 4.14.181-142.260.amzn2.x86_64_1 version (`/aws/service/eks/optimized-ami/1.15/amazon-linux-2/recommended/image_id` (ami-0f433dffa73f54ea2) is not available at https://dl.bintray.com/falcosecurity/driver/96bd9bc560f67742738eb7255aeb4d03046b8045/ and therefore the community is not able to deploy falco-probe with eks-1.15 ami
Signed-off-by: Fahad Arshad <fahad.arshad@hobsons.com>
=> new: prebuild module for amazonlinux2 amzn2_4.14.181-142.260_1

prow/config/configs.yaml
In an attempt to let @poiana push to `gh-pages` branch of `falcosecurity/charts` as per @leogr needs about the charts release process.
The idea here is to remove the need of (at least 1) reviewer on pull-requests.
Note that the `gh-pages` branch is still protected but users in `maintainers` and bot dedicated GitHub teams can still push to it.
As per branchprotector [docs](https://github.com/kubernetes/test-infra/tree/8c8546d74168a57d0a3d22b17d98eb09bbf70601/prow/cmd/branchprotector#scope) bool/int values should override (not merge) with parent hierarchical YAML keys.
=> override (and disable) the pull request reviews for falcosecurity/charts#gh-pages branch

prow/config/configs.yaml
The [falcosecurity/evolution](https://github.com/falcosecurity/evolution) repository has no CircleCI integration. Moreover, no status check is required.
Furthermore, since this check was introduced by https://github.com/falcosecurity/test-infra/commit/996f17d777045cadefb83707cebe636b0002b54f with message `new: driverkit checks for circleci`, I guess it was added in the wrong place by mistake, and `driverkit` is currently missing that.
=> update(prow/config): no status check for evolution repo

prow/config/plugins.yaml
Since both `event-generator` and `falco-exporter` (that I'm maintaining) are using goreleaser to handle the changelog ([here](https://github.com/falcosecurity/falco-exporter/releases/tag/v0.2.0) an example) I'd like to do not have the `release-note` block.
I believe the changelog based on the commit message is already enough to document changes of these two relatively small tools.
=> remove release-note plugin for event-generator and falco-exporter

prow/config/configs.yaml
As we discovered, [this setting]() is not enough to allow @poiana to push on a protected branch, since GH still requires that commits pass thru a PR.
For the reason above, and since @poiana is an admin user, with this PR we are disabling the enforcement of the restrictions for admins only on the `gh-pages` of https://github.com/falcosecurity/charts
The `enforce_admins` parameter description can be found here: https://developer.github.com/v3/repos/branches/#parameters-1
The reason why we need this in described in the [charts release.md doc](https://github.com/falcosecurity/charts/blob/master/release.md#circleci-workflow) and the action (that will be performed by @poiana) is coded [here](https://github.com/falcosecurity/charts/blob/c657933144fbfdf1bef9e12040492119128d98c8/.circleci/release.s …
=> update(prow/config): do not enforce restrictions for admins in `gh-pages` of `charts` repo

README.md, prow/cluster/saymyname.yaml, prow/config/plugins.yaml
For my talk at [KubeCon Europe 2020](https://sched.co/ZenU), I am prepping a custom Prow external plugin in order to show the audience how to create one and further extend the already awesome [Prow](https://github.com/kubernetes/test-infra/blob/master/prow) features.
So, I just made this last-minute attempt to create a plugin for our beloved @poiana that introduces the `/poiana` slash command.
With this PR, I add some YAML specs (🧶  YAML engineering!), and configure the abovementioned custom external plugin.
You can find its source code at https://github.com/leodido/saymyname-prow-plugin
=> New custom external Prow plugin (saymyname)

prow/config/plugins.yaml
They don't have to be in that list (look at needs-rebase for example).
=> fix(prow/config): remove external plugin from the list of prow plugins

.circleci/config.yml, driverkit/Makefile, driverkit/utils/cleanup
This PR introduces:
- a script into `driverkit/utils` that (given the bintray secret plus a list of driver versions to keep) queries bintray API to obtain all the existing driver versions and filter them out by keeping only the two driver versions specified as input
- a make command that calls the above script specifying the bintray secret and passes to it the driver versions currently in the `driverkit/config` directory
- adds to the CI a job (`drivers/cleanup`) that puts all the pieces together and runs on every merge into master
=> Automatic drivers cleanup

driverkit/Makefile, driverkit/utils/checkfiles, driverkit/utils/driverstats
This PR introduces an (initial) script to generate some numbers about the prebuilt drivers.
For now, it just aggregates the number of prebuilt eBPF probes and the number of prebuilt kernel modules we tentatively (in case they build successfully) ship for Falco.
Anyways, here there are some simple ideas that can be built on top of this skeleton script:
- segment the number of prebuilt drivers by driver version
- count the number of prebuilt drivers by distro
- count the number of prebuilt drivers by kernel release major
=> Initial stats command for the Drivers Build Grid

driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-aws_5.4.0-1024-aws_24.yaml, driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-aws_5.4.0-1024-aws_24.yaml
```
* Trying to download prebuilt module from https://dl.bintray.com/falcosecurity/driver/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/falco_ubuntu-aws_5.4.0-1024-aws_24.ko
curl: (22) The requested URL returned error: 404 Not Found
Download failed, consider compiling your own falco module and loading it or getting in touch with the Falco community
```
This should fix my issue.
=> new: prebuilt module for ubuntu-aws 5.4.0-1024-aws_24

proposals/20200915-prow.md, prow/config/configs.yaml, prow/config/plugins.yaml
This PR adds @poiana (stop the drama!) to the [pdig](https://github.com/falcosecurity/pdig) repository.
Plugins:
- approve
- assign
- blunderbuss
- cat
- dco
- dog 
- goose
- help
- hold
- label
- lifecycle
- lgtm
- release-note (needs PR templates to contain release-note block)
- require-matching-label (needs PR templates to contain /kind <label>)
- retitle
- size
- welcome
- wip
Labels:
- master
- rebase
=> Enable poiana for falcosecurity/kilt

config/jobs/lifecycle-bot/periodic-close.yaml, config/jobs/lifecycle-bot/periodic-rotten.yaml, config/jobs/lifecycle-bot/periodic-stale.yaml
Fixes #40 (where you can find detailed information about the resulting behavior of these 2 periodic `ProwJob`s.)
The lifecycle transitions are:
1. issue or PR becomes stale after 90 days of inactivity
2. stale issue or PR becomes rotten after 30 days of inactivity
3. rotten issues close after 30 days of inactivity
WIP because some points are still open:
=> lifecycle bot

config/jobs/build-drivers/build-drivers.yaml
We need to set a proper changes trigger for the drivers build jobs.
(Something to consider for the regex format in Prow job's `run_if_changed` is that negative look aheads are not supported in Golang).
=> Fix drivers build jobs triggers

.circleci/config.yml, config/jobs/autobump/autobump.yaml, config/jobs/build-drivers/build-drivers.yaml
1. Adding autobump.... need to figure out a way to make autobump DCO signoff the commit from pioana
2. Incrementing the build-drivers jobs so they don't ddos our others jobs running all at the same time.
=> adding autobump, and incrementing build-driver periodics

config/prow/deck.yaml
Add HTTP redirect to HTTPS when host is "prow.falco.org".
As implemented here: https://github.com/kubernetes/test-infra/pull/6122
=> Add https redirect to deck

config/config.yaml
Increase timeout in Plank default decoration, in order to enable driverkit jobs to complete.
=> Increase default job timeout from 3h to 6h

config/config.yaml
How noticed by working on PR #224 the timeout for (some) of the `ProwJob`s needs to be increased.
=> update(config): increase timeout for prowjobs

tools/deploy_terraform.sh
Switch from Terraform latest to 0.13.5 version.
Terraform 0.14.0 introduces incompatibilities with current code.
=> Pin Terraform v0.13.5 in CI/CD pipeline

config/config.yaml, config/jobs/check-prow-config/check-prow-config.yaml
Set the `check-prow-config` to always run and remove deployment jobs as required to report status on PRs.
=> Always run prow config check

config/jobs/update-jobs/update-jobs.yaml
Update-jobs should run on PR's getting merged, not on every commit on a PR. This is causing job contention issues, where an older PR #225 can update-jobs to an older backport and force jobs to run on newer PR's. #241 
https://prow.falco.org/log?job=update-jobs-pr&id=1334569592248340480
=> Switch update-jobs to postsubmit now that check-config works for PR

config/config.yaml, config/jobs/check-prow-config/check-prow-config.yaml, config/prow/branchprotector.yaml, config/prow/crier.yaml, config/prow/deck.yaml, config/prow/ghproxy.yaml, config/prow/hook.yaml, config/prow/horologium.yaml, config/prow/needs-rebase.yaml, config/prow/plank.yaml, config/prow/prow-controller-manager.yaml, config/prow/sinker.yaml, config/prow/statusreconciler.yaml, config/prow/tide.yaml
Included changes: https://github.com/kubernetes/test-infra/compare/061f85d859...de9ccc9ff1
=> Bump prow from v20201124-061f85d859 to v20201211-de9ccc9ff1

config/jobs/build-prow-images/build-images.yaml, images/publish.sh
Finally getting around to adding these much needed prow jobs. These jobs will build and publish the base prow images used by the other tests. 
Can utilize the `docker-dind` image used by build-drivers since it has docker-dind and awscli installed already.
=> adding in jobs and script to build images for prowjobs

.gitignore, config/jobs/build-prow-images/build-images.yaml, config/jobs/update-maintainers/update-maintainers.yaml, docs/local-testing.md, images/update-maintainers/Dockerfile, images/update-maintainers/Makefile, images/update-maintainers/entrypoint.sh, images/update-maintainers/persons.json, tools/delete_local_prowjob.sh, tools/local_prowjob.sh
This PR introduces:
- A ProwJob ("update-maintainers") that will periodically:
- check all the OWNERS files present in the **falcosecurity** organization (using [leodido/maintainers-generator](https://github.com/leodido/maintainers-generator))
- create  the current list of maintainers of all the Falco projects in a YAML file (using [leodido/maintainers-generator](https://github.com/leodido/maintainers-generator))
- open a PR towards **falcosecurity/.github** repository on the ([maintainers.yaml](https://github.com/falcosecurity/.github/blob/master/maintainers.yaml)) file, in case there are updates
- Improvements to the scripts inside `tools/` to run ProwJob locally
- Improvements to the guide to run ProwJob locally
TODOs:
=> update maintainers periodic prow job

config/config.yaml, config/jobs/check-prow-config/check-prow-config.yaml, config/prow/branchprotector.yaml, config/prow/crier.yaml, config/prow/deck.yaml, config/prow/ghproxy.yaml, config/prow/hook.yaml, config/prow/horologium.yaml, config/prow/needs-rebase.yaml, config/prow/plank.yaml, config/prow/prow-controller-manager.yaml, config/prow/sinker.yaml, config/prow/statusreconciler.yaml, config/prow/tide.yaml
Included changes: https://github.com/kubernetes/test-infra/compare/de9ccc9ff1...2de500de27
=> Bump prow from v20201211-de9ccc9ff1 to v20201217-2de500de27

driverkit/Makefile, driverkit/README.md, driverkit/utils/driverstats
Closes #250.
As for the related issue this PR enables to further filter Falco driver versions to pre-build by specifying both:
- Linux distribution
- Linux version
by enabling the `specific_target` Make target to accept a new parameter: `TARGET_KERNEL`.
This parameter as for `TARGET_DISTRO` is read from the environment and it accetps a Linux version in `<kernel_version>.<major_version>.<minor_version>` format.
For instance:
```bash
make -e TARGET_DISTRO=centos -e TARGET_KERNEL=3.10.0 specific_target
[...]
```
It introduces also a Make target `count_specific_target` to count the result of the filter as for the `TARGET_*` variables set.
For instance:
```bash
make -e TARGET_DISTRO=centos -e TARGET_KERNEL=3.10.0 count_specific_target
261
```
None.
=> Filter driver build targets also per kernel version

config/config.yaml, config/jobs/check-prow-config/check-prow-config.yaml, config/prow/branchprotector.yaml, config/prow/crier.yaml, config/prow/deck.yaml, config/prow/ghproxy.yaml, config/prow/hook.yaml, config/prow/horologium.yaml, config/prow/needs-rebase.yaml, config/prow/plank.yaml, config/prow/prow-controller-manager.yaml, config/prow/sinker.yaml, config/prow/statusreconciler.yaml, config/prow/tide.yaml
Included changes: https://github.com/kubernetes/test-infra/compare/2de500de27...15d664642a
=> Bump prow from v20201217-2de500de27 to v20201228-15d664642a

driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/debian_5.8.0-1-cloud-amd64_1.yaml, driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/debian_5.8.0-1-cloud-amd64_1.yaml, driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/debian_5.8.0-1-cloud-amd64_1.yaml, driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/debian_5.8.0-1-cloud-amd64_1.yaml
A user reported on slack that kernel 5.8.0-1-cloud-amd64 on debian 9 is
in use on Linode. No headers were found on the host.
Signed-off-by: Spencer Krum <nibz@spencerkrum.com>
=> new(driver): Add debian 5.8 for Linode Kubernetes

config/config.yaml, config/jobs/check-prow-config/check-prow-config.yaml, config/prow/branchprotector.yaml, config/prow/crier.yaml, config/prow/deck.yaml, config/prow/ghproxy.yaml, config/prow/hook.yaml, config/prow/horologium.yaml, config/prow/needs-rebase.yaml, config/prow/plank.yaml, config/prow/prow-controller-manager.yaml, config/prow/sinker.yaml, config/prow/statusreconciler.yaml, config/prow/tide.yaml
Included changes: https://github.com/kubernetes/test-infra/compare/15d664642a...eac8059329
=> Bump prow from v20201228-15d664642a to v20210108-eac8059329

images/build-drivers/Dockerfile, images/build-drivers/Makefile, images/build-drivers/build-drivers.sh
This PR updates the `falcosecurity/test-infra/build-drivers` container image that the `build-drivers-*` ProwJobs use to ship a bunch of prebuilt Falco drivers.
Such container image will now use [driverkit 0.3.0](https://github.com/falcosecurity/driverkit/releases/tag/v0.3.0) (mainly for shipping some prebuilt Falco drivers for GKE kernels).
=> Update driverkit to 0.3.0 (build-drivers-* prowjob)

images/update-jobs/Makefile, images/update-jobs/update-jobs.sh
Fixes #285 
The `update-jobs` go tool uses go modules now. The image needs to be updated accordingly.
=> Fix the update-jobs image and ProwJob

config/jobs/build-drivers/build-drivers.yaml
Build-drivers pre-submit were using the incorrect image tag.
=> updating build-drivers presubmit tags

config/jobs/update-jobs/update-jobs.yaml
Latest images are pushed on PR presubmit and jobs pick always latest version of them.
In example `update-jobs` lastest image is published from #292 but with neither the PR being accepted nor required new `prowjob` configurations put in place.
The stable version of `update-jobs` (the version before the #292 latest) container image has been tagged `stable` and `1.0.0`.
=> Pin update-jobs stable image until tests on latest pass

config/jobs/build-drivers/build-drivers.yaml, config/prow/build-drivers-serviceaccount.yaml
Looks like SA role had a typo in it, tested out with sleep pod, and uploads seemed to work now.
=> fixing SA typo, and adding to periodic

config/prow/update-jobs.yaml
RBAC wasn't working from the re-write.
`time="2021-02-02T15:00:04Z" 
level=fatal msg="while updating jobs: configmaps \"job-config\" is forbidden: User \"system:serviceaccount:test-pods:update-jobs\" cannot update resource \"configmaps\" in API group \"\" in the namespace \"default\""`
Changed RBAC to work properly, and periodic test looks like it passed using new RBAC.  https://prow.falco.org/view/s3/falco-prow-logs/logs/update-jobs-periodic/1356633460638224384
=> fixing rbac for update-jobs

config/config.yaml, config/jobs/check-prow-config/check-prow-config.yaml, config/prow/branchprotector.yaml, config/prow/crier.yaml, config/prow/deck.yaml, config/prow/ghproxy.yaml, config/prow/hook.yaml, config/prow/horologium.yaml, config/prow/needs-rebase.yaml, config/prow/plank.yaml, config/prow/prow-controller-manager.yaml, config/prow/sinker.yaml, config/prow/statusreconciler.yaml, config/prow/tide.yaml
Included changes: https://github.com/kubernetes/test-infra/compare/eac8059329...451988f24f
=> Bump prow from v20210108-eac8059329 to v20210205-451988f24f

config/config.yaml, config/plugins.yaml
As per the approved incubation request https://github.com/falcosecurity/evolution/issues/47, this PR adds the initial prow configuration for https://github.com/falcosecurity/falcosidekick-ui
/cc @leodido
=> update(config): initial `falcosidekick-ui` prow configuration

.circleci/config.yml
Run deploy jobs only from master branch, run scanning and validations without filtering.
=> Fix circleci jobs filtering

config/config.yaml
We are still double-checking the circle ci configuration, hold for now
/hold
=> update(config): add required status check for falcosidekick-ui

config/config.yaml
As per [docs](https://github.com/kubernetes/test-infra/blob/2abb7ff26579325f6a335990003f665755c96d7a/prow/cmd/tide/config.md#general-configuration) we need an URL for tide status contexts.
=> update(test-infra/config): add target URL for tide

config/config.yaml, config/plugins.yaml
This PR adds @poiana (stop the drama!) to the [libs](https://github.com/falcosecurity/libs) repository.
Plugins:
- approve
- assign
- blunderbuss
- cat
- dco
- dog
- goose
- help
- hold
- label
- lifecycle
- lgtm
- release-note
- require-matching-label
- retitle
- size
- welcome
- wip
Labels:
- master
- rebase
=> Configure Prow (@poiana) for falcosecurity/libs

config/config.yaml, config/jobs/check-prow-config/check-prow-config.yaml, config/prow/branchprotector.yaml, config/prow/crier.yaml, config/prow/deck.yaml, config/prow/ghproxy.yaml, config/prow/hook.yaml, config/prow/horologium.yaml, config/prow/needs-rebase.yaml, config/prow/plank.yaml, config/prow/prow-controller-manager.yaml, config/prow/sinker.yaml, config/prow/statusreconciler.yaml, config/prow/tide.yaml
Included changes: https://github.com/kubernetes/test-infra/compare/72696ce111...445b85c368
=> Bump prow from v20210211-72696ce111 to v20210218-445b85c368

tools/create_ecr.sh
An entry for creation of the `build-libs` OCI image repository on AWS ECR is added with this PR.
=> Add build-libs AWS ECR Repository

config/jobs/build-libs/build-libs.yaml
Add another test job similar to the previous one, but without the `-DUSE_BUNDLED_DEPS` build option.
Follow up #319, #321, and #322 
/cc @leodido 
/cc @maxgio92
=> update(config/jobs/build-libs): add build job with no bundled deps

config/config.yaml, config/jobs/check-prow-config/check-prow-config.yaml, config/prow/branchprotector.yaml, config/prow/crier.yaml, config/prow/deck.yaml, config/prow/ghproxy.yaml, config/prow/hook.yaml, config/prow/horologium.yaml, config/prow/needs-rebase.yaml, config/prow/plank.yaml, config/prow/prow-controller-manager.yaml, config/prow/sinker.yaml, config/prow/statusreconciler.yaml, config/prow/tide.yaml
Included changes: https://github.com/kubernetes/test-infra/compare/c6b468b556...350f3b2f2e
=> Bump prow from v20210226-c6b468b556 to v20210305-350f3b2f2e

config/clusters/ecr.tf, tools/deploy_terraform.sh
This PR will:
- declare the AWS ECR repositories used for the infra containers as code
- import the existing ones to the Terraform state, right before applying the code, of which plan should have desired state matching the actual one.
[Docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ecr_repository#import)
=> Import container image repositories to Terraform state

tools/deploy_prow.sh
This PR will inherit benefit from [PR](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/731) merged to driver repository.
In detail, all the driver components will now use multiarch container images. 
In the meantime I asked to push a new semantic versioning tag like `v0.9.1`.
=> Use multiarch AWS EBS CSI driver kustomization

config/config.yaml, config/jobs/check-prow-config/check-prow-config.yaml, config/prow/branchprotector.yaml, config/prow/crier.yaml, config/prow/deck.yaml, config/prow/ghproxy.yaml, config/prow/hook.yaml, config/prow/horologium.yaml, config/prow/needs-rebase.yaml, config/prow/plank.yaml, config/prow/prow-controller-manager.yaml, config/prow/sinker.yaml, config/prow/statusreconciler.yaml, config/prow/tide.yaml
Included changes: https://github.com/kubernetes/test-infra/compare/350f3b2f2e...67f589ad7c
=> Bump prow from v20210305-350f3b2f2e to v20210312-67f589ad7c

tools/deploy_terraform.sh
This PR removes the import step that was required to import AWS ECR repositories created imperatively into Terraform state to manage them declaratively.
This step in `tools/deploy_terraform.sh` is no longer required and needs to be removed to let Terraform manage resources with `apply`.
=> Remove OCI repositories import into TF state step

images/build-drivers/Dockerfile
Co-authored-by: Michele Zuccala <michele@zuccala.com>
I and @zuc just released driverkit v0.4.0 (read the CHANGELOG [here](https://github.com/falcosecurity/driverkit/releases/tag/v0.4.0), notably the support for AmazonLinux 2 `5.*` kernels).
This PR updates the `build-drivers-*` ProwJobs image in order to use this new version.
=> update(images/build-drivers): switch to use driverkit v0.4.0

config/jobs/update-falco-k8s-manifests/update-falco-k8s-manifests.yaml, images/update-falco-k8s-manifests/entrypoint.sh
This PR enable the image `update-falco-k8s-manifests` to `template` every Helm chart from `falcosecurity` Helm repository and push them to `evolution` repo.
It also adds two new jobs to generate and push manifests for `falco-exporter` and `falco-sidekick`.
=> Add jobs to push falco-exporter and falco-sidekick plain manifests from Helm charts

config/jobs/build-libs/build-libs.yaml
/hold
See https://github.com/falcosecurity/libs/pull/14
=> update(config/jobs/build-libs): add build job for WITH_CHISEL option

config/config.yaml, config/jobs/check-prow-config/check-prow-config.yaml, config/prow/branchprotector.yaml, config/prow/crier.yaml, config/prow/deck.yaml, config/prow/ghproxy.yaml, config/prow/hook.yaml, config/prow/horologium.yaml, config/prow/needs-rebase.yaml, config/prow/plank.yaml, config/prow/prow-controller-manager.yaml, config/prow/sinker.yaml, config/prow/statusreconciler.yaml, config/prow/tide.yaml
Included changes: https://github.com/kubernetes/test-infra/compare/2181a9e7d7...ad0e6d1480
=> Bump prow from v20210319-2181a9e7d7 to v20210325-ad0e6d1480

images/update-falco-k8s-manifests/Dockerfile, images/update-falco-k8s-manifests/entrypoint.sh
This PR updates the `update-falco-k8s-manifests` `ProwJob` image to include a base `Kustomization` file for components of which Kubernetes manifests are generated, in order to provide a version-zero support for users that use Kustomize to manage Kubernetes configurations.
So, in the end for who wants to manage his configurations with Kustomize will (from [evolution](https://github.com/falcosecurity/evolution) root folder):
```
kubectl apply -k deploy/kubernetes/falco
```
and who doesn't:
```
kubectl apply -f deploy/kubernetes/falco/templates
```
=> Generate Kustomizations for Falco ecosystem components

images/update-falco-k8s-manifests/Dockerfile
This PR fixes the path where Kustomize is installed to.
=> Fix Kustomize path in images/update-falco-k8s-manifests/dockerfile

config/config.yaml
As per [website release instructions](https://github.com/falcosecurity/falco-website/blob/master/release.md#create-a-new-website-snapshot).
This PR needs to be merged in after:
- Falco 0.28 released
- falco-website snapshot for Falco 0.27 created (branch v0.27)
/hold
=> update(config): protect branch v0.27 of the falco-website

config/plugins.yaml
Fixing issues by check-config
```
{"component":"unset","file":"prow/logrusutil/logrusutil.go:122","func":"k8s.io/test-infra/prow/logrusutil.ThrottledWarnf","level":"warning","msg":"plugins declaration uses a deprecated config style, see https://github.com/kubernetes/test-infra/issues/20631#issuecomment-787693609 for a migration guide","severity":"warning","time":"2021-04-16T18:57:57Z"}
{"component":"unset","file":"prow/cmd/checkconfig/main.go:82","func":"main.reportWarning","level":"warning","msg":"the following orgs or repos forbid the do-not-merge/release-note-label-needed label for merging but do not enable the release-note plugin: [repo: falcosecurity/kilt]","severity":"warning","time":"2021-04-16T18:57:57Z"}
```
=> Fixing Checkconfig warnings - Update plugin format, Kilt

config/plugins.yaml
Currently we are encountering an issue. The issue is that Tide is seeing an approval tag being applied to a PR in `falco` when it's gets a Github approval. However the repo requires 2 approvals so Tide is trying to merge the PR but branchprotector is stopping it, causing an endless cycle of merge attempts.
This is because in the `config.yml` we require 2 approvals for both the `falco` and the `libs` repo's.
```
falco:
required_pull_request_reviews:
required_approving_review_count: 2
```
This fix would only allow the approve label to be applied via an approver typing `/approve` when it has the required 2 reviews, and not by a single github review. 
Link to config in docs https://github.com/kubernetes/test-infra/blob/40c5a1d1b758201872804ec32 …
=> bug - fixing tide mis-match approval bug for falco and libs repos

config/prow/deck.yaml, tools/deploy_prow.sh
This PR introduces the PR status page.
This is accomplished by configuring OAuth so that Deck can access GH resources via API, on behalf of the authenticated Github identity.
Closes #23.
=> Configure Deck to get PR status from Github

config/clusters/storage.tf
This PR should fix and unblock syntax errors that now are blocking the CI/CD of the infrastructure.
/cc @jonahjon WDYT?
=> fix(config/clusters/storage.tf): s3 bucket lifecycle aws provider syntax

config/prow/deck.yaml
This PR aims to resolve an issue with PR status page configuration of OAuth and cookie.
In detail, the `--cookie-secret` flag argument of Deck command was missing.
=> fix(config/prow/deck.yaml): add required cookie secret path flag

images/docker-dind/Dockerfile
There are scripts (like [images/publish.sh](./images/publish.sh)) that reference the image built with this `Dockerfile`,
but they reference `awscli` v2 and this `Dockerfile` install version 1 via [deb package](https://packages.debian.org/buster/all/awscli), as for the Debian buster stable repository. This commit aligns its version as expected.
This PR aligns the `awscli` toolkit version as expected.
=> fix(images/docker-dind/Dockerfile): upgrade awscli to v2 according to usage

driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_5.4.110-54.189.amzn2.x86_64_1.yaml
Signed-off-by: ismail yenigul <ismailyenigul@gmail.com>
fix for  latest EKS worker instance kernel
```
2021-05-19T18:09:38.018964835Z * Setting up /usr/src links from host
2021-05-19T18:09:38.030239959Z * Running falco-driver-loader for: falco version=0.28.1, driver version=5c0b863ddade7a45568c0ac97d037422c9efb750
2021-05-19T18:09:38.031509119Z * Running falco-driver-loader with: driver=module, compile=yes, download=yes
2021-05-19T18:09:38.031836055Z * Unloading falco module, if present
2021-05-19T18:09:38.042065677Z * Trying to load a system falco module, if present
2021-05-19T18:09:38.044166061Z * Looking for a falco module locally (kernel 5.4.110-54.189.amzn2.x86_64)
2021-05-19T18:09:38.046529944Z * Trying to download a prebuilt falco module from …
```
=> amazonlinux2_5.4.110-54.189 config

tools/deploy_prow.sh
This PR adds [metrics-server](https://github.com/kubernetes-sigs/metrics-server) as pre requisite infra software, to collect resource metrics of test containers (and not only).
At first for sure I think we need it to better measure resource consumption of `ProwJob`s over time, to tune requests/limits and tailor underlying infrastructure where they'll be scheduled on.
This is in the direction of solving issues in scenarios like the one reported by #333.
=> Add metrics-server to collect resource metrics from test containers

config/clusters/TERRAFORM.md, config/clusters/terraform_versions.tf
This PR bumps the AWS Terraform provider version from 3.39.0 to 3.40.0, allowing increment of new patch versions.
Furthermore, this PR allows incrementing also the patch version of the Kubernetes Terraform provider. 
More on Terraform [version constraints](https://www.terraform.io/docs/language/expressions/version-constraints.html#version-constraint-syntax).
=> Bump Prow clusters' AWS Terraform provider version

.circleci/config.yml, config/clusters/eks.tf, tools/terraform.Makefile
This PR upgrades and locks the EKS Terraform module to v17.0.3 version without introducing disruption (see [commit](https://github.com/terraform-aws-modules/terraform-aws-eks/commit/6d7d6f6f5a26a4d3aee527d9ddd087f0fd8bdbe9) about the `name_prefix` introduction for Node Groups which causes to re-create the resources).
Furthermore, this PR adds two skip on infra scanning check, as I think they have a pretty low priority now. We can then improve there.
=> Upgrade EKS Terraform module to v17.0.3 without disruption

config/clusters/storage.tf
Seeing if we can adhere to this rego https://github.com/accurics/terrascan/blob/1027346ee6fb13c123e3695c34f5ef7c0fc815e9/pkg/policies/opa/rego/aws/aws_s3_bucket/s3EnforceUserACL.rego
Line 7 says ` not bucket.config.policy` so this should make it suceed.
=> Unblocking CI attempt by adhering to Rego.

.circleci/config.yml
The fix for the terrascan CI job was originally made by @jonahjon in #417
However, it's required by several PRs. Moving it here (in a dedicated PR) so we can then unblock all pending PRs.
=> terrascan fix

driverkit/config/13ec67ebd23417273275296813066e07cb85bc91/amazonlinux2_5.4.117-58.216.amzn2.x86_64_1.yaml, driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/amazonlinux2_5.4.117-58.216.amzn2.x86_64_1.yaml, driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/amazonlinux2_5.4.117-58.216.amzn2.x86_64_1.yaml, driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/amazonlinux2_5.4.117-58.216.amzn2.x86_64_1.yaml
Amazon released new EKS AMIs in the v20210526 tag using kernels
5.4.117-58.216.amzn2.x86_64 (for 1.19 and above) and
4.14.232-176.381.amzn2.x86_64 (for 1.18 and below). This PR is based on
previous PRs to this repo to resolve falco-driver-loader failing to
download drivers for these new AMIs.
https://github.com/awslabs/amazon-eks-ami/releases/tag/v20210526
=> Add support for v20210526 Amazon EKS AMIs

config/plugins.yaml
2 Changes
1. `require_self_approval: true` -> `require_self_approval: false`
RequireSelfApproval requires PR authors to explicitly approve their PRs.  This is redundant since PR authors approve the changes in the PR by default.
2.      `trusted_team_for_sticky_lgtm: test-infra-maintainers` 
This should eliminates the need to re-lgtm minor fixes/updates.
=> tweaking lgtm to reduce test-retriggering

.circleci/config.yml, config/clusters/security_groups.tf
Another Terrascan addition. We can't really scope these SG's to any /32 since we don't use a bastion host at the moment. Would rather install SSM agent daemon and remove this in the future for SSH access.
When reviewing the rules noticed they were scoped for other network ranges not in use so fixed that.
=> fixing terrascan, and tightning SG rules

config/jobs/recurring-ghissues/prow-eks-upgrade.yaml, images/ghissue/Dockerfile, images/ghissue/Makefile, images/ghissue/entrypoint.sh
This PR adds:
- a CI image to open Github issues thanks to [hcgatewood/ghissue](https://github.com/hcgatewood/ghissue)
- a periodic ProwJob that should open an issue to remind the Prow EKS cluster maintenance (like #370)
The `ghissue` container requires from the env:
- `GITHUB_TOKEN`
- `GH_ISSUE_TITLE`
- `GH_ISSUE_BODY`
and accepts from the env:
- `GH_ISSUE_TAGS`
- `GH_ISSUE_ASSIGNEE`
- `GH_ISSUE_ORG` (by default `falcosecurity`)
- `GH_ISSUE_REPO` (by default `test-infra`)
The periodic ProwJob is configured to run now June the 18th at 7 AM (as a first test). The right cron expression is now commented.
=> Add image and ProwJob to open recurring Github Issues

driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/ubuntu-generic_5.12.3-arch1-1_1.yaml, driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/ubuntu-generic_5.12.3-arch1-1_1.yaml, driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/ubuntu-generic_5.12.3-arch1-1_1.yaml, driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/ubuntu-generic_5.12.3-arch1-1_1.yaml, driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/ubuntu-generic_5.12.3-arch1-1_1.yaml
Signed-off-by: Gaurav Gahlot <gauravgahlot0107@gmail.com>
=> Add prebuilt drivers configs for ubuntu generic kernel 5.12.3-arch1-1 1

driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_5.4.129-62.227.amzn2.x86_64_1.yaml
Our EKS Nodes updated to this new AMI - amazon-eks-node-1.20-v20210720 - which goes looking for driver version 5.4.129-62.227.amzn2.x86_64_1
This PR adds that driver version
=> Add the most recent EKS AMI

config/config.yaml
This PR configures tide to wait for review being approved.
With this configuration of tide each PR in the query must have at least one
approved GitHub pull request review present for merge, to be put in the
PRs pool.
Note: this should respect what is set in
`required_pull_request_reviews.required_approving_review_count` branch
protection`s configuration.
This prevents from an inconsistency between `tide` and Github.
This inconsistency can be generated when `tide` queries for PRs without
considering Github review approvals.
So, when the query criteria match for tide, there still can be reviews
to be approved, and branch protection preventing from merge.
In this scenario `tide` could repeatedly try to merge the PR on Github
until exceeding the Github specific API rate limit.
This happened …
=> feat(config): configure tide to wait for review approved

config/prow/cluster-autoscaler.yaml
Cluster Autoscaler was older, and has throttling issues leading to crashes.... updating to new version.
=> updating cluster autoscaler

driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_5.4.91-41.139.amzn2.x86_64_1.yaml, driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_5.4.91-41.139.amzn2.x86_64_1.yaml
For EKS 1.19 with ami-081ce801565bbd64d (amazon-eks-node-1.19-v20210208).
=> Add slightly older (but still extant) AMI kernel version: 5.4.91-41.139.amzn2.x86_64

config/jobs/lifecycle-bot/periodic-close.yaml, config/jobs/lifecycle-bot/periodic-rotten.yaml, config/jobs/lifecycle-bot/periodic-stale.yaml
Lifecycle bot has been broken for a bit, adding in a tested fix for it.
https://prow.falco.org/job-history/s3/falco-prow-logs/logs/periodic-rotten
=> fixing prow lifecycle bot

config/distribution/.terraform.lock.hcl, config/distribution/README.md, config/distribution/containers.tf, config/distribution/distribution.tf, config/distribution/terraform_providers.tf, config/distribution/terraform_versions.tf
This PR
- extend the scope of the Falco [distribution infrastructure](https://github.com/falcosecurity/test-infra/tree/master/config/distribution) to artifacts from incubating projects
- delcares two new ECR repositories for [`falcosidekick`](https://github.com/falcosecurity/falcosidekick) and [`falcosidekick-ui`](https://github.com/falcosecurity/falcosidekick-ui).
This enables Falco Sidekick and Falco Sidekick UI to distribute OCI artifacts from AWS ECR in addition to Docker Hub.
/cc @jonahjon
=> Add ECR repositories for falcosidekick and falcosidekick-ui

config/distribution/containers.tf, config/distribution/distribution.tf
This PR introduces Terraform [protection from destroy](https://www.terraform.io/docs/language/meta-arguments/lifecycle.html#prevent_destroy) on the critical resources of the [`distribution`](https://github.com/falcosecurity/test-infra/tree/master/config/distribution) infrastructure.
/cc @jonahjon
=> ci: prevent critical resources from destroy

driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_5.4.141-67.229.amzn2.x86_64_1.yaml, driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/amazonlinux2_5.4.141-67.229.amzn2.x86_64_1.yaml, driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_5.4.141-67.229.amzn2.x86_64_1.yaml, driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/amazonlinux2_5.4.141-67.229.amzn2.x86_64_1.yaml, driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/amazonlinux2_5.4.141-67.229.amzn2.x86_64_1.yaml
Adding amazonlinux2_5.4.141-67.229.amzn2.x86_64 kernel to the list of pre-build modules.
=> Adding amazonlinux2_5.4.141-67.229.amzn2.x86_64 kernel to the list of pre-build modules.

driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_5.4.129-63.229.amzn2.x86_64_1.yaml, driverkit/config/2aa88dcf6243982697811df4c1b484bcbe9488a2/amazonlinux2_5.4.129-63.229.amzn2.x86_64_1.yaml, driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_5.4.129-63.229.amzn2.x86_64_1.yaml, driverkit/config/85c88952b018fdbce2464222c3303229f5bfcfad/amazonlinux2_5.4.129-63.229.amzn2.x86_64_1.yaml, driverkit/config/ae104eb20ff0198a5dcb0c91cc36c86e7c3f25c7/amazonlinux2_5.4.129-63.229.amzn2.x86_64_1.yaml
Forgot to add eBPF probe in previous [PR](https://github.com/falcosecurity/test-infra/pull/502/files)
=> Build eBPF modules for amazonlinux2_5.4.129-63.229.amzn2.x86_64_1.

.circleci/config.yml
New image doesn't work in CircleCI https://app.circleci.com/pipelines/github/falcosecurity/test-infra/1141/workflows/7dfdc83d-d69b-4a40-9498-8bb29a5f25eb/jobs/3989
Pinning to a more recent version until they fix latest.
=> Pinning image version for CircleCI job

config/config.yaml, config/jobs/build-plugin-sdk-go/build-plugin-sdk-go.yaml, config/plugins.yaml
This adds prow/poiana support for falcosecurity/plugin-sdk-go.
=> Add plugin sdk go jobs

config/jobs/build-plugin-sdk-go/build-plugin-sdk-go.yaml, config/jobs/build-plugins/build-plugins.yaml
Instead of using the local golang image, use golang:1.15. This matches
what's in go.mod for the plugins.
Also fix the command to use the the mount location for the code, as
a workingDir is set for the k8s job.
Signed-off-by: Mark Stemm <mark.stemm@gmail.com>
=> Fix build-plugins/build-plugin-sdk-go jobs

images/build-libs/Dockerfile
Moreover, pin debian:buster, following what was already done for falco: https://github.com/falcosecurity/falco/pull/1719/files
Note: automake is an explicit dep listed in our documentation: https://falco.org/docs/getting-started/source/;
moreover, automake installs autoconf as dep, but i decided to keep both.  
Finally, this should fix a build issue: https://github.com/falcosecurity/libs/pull/115, where `aclocal` executable was not found.
```
Co-authored-by: Leonardo Grasso <me@leonardograsso.com>
```
=> update: add automake dep to build-libs dockerfile

config/jobs/build-libs/build-libs.yaml
Note that BPF build is disabled because MINIMAL_BUILD does not support building bpf probe.
=> update(build-libs): test minimal libs build

driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/centos_5.4.0-80.90.2.el7.x86_64_1.yaml
Signed-off-by: Troy Pang <beactivepang@gmail.com>
=> Add eBPF probe support for CentOS 5.4.0-80.90.2.el7.x86_64

driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_5.4.149-73.259.amzn2.x86_64_1.yaml, driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_5.4.149-73.259.amzn2.x86_64_1.yaml
Ensuring the ebpf probe is built for this version of AmazonLinux 2. Was getting the following error:
```
* Trying to download a prebuilt eBPF probe from https://download.falco.org/driver/17f5df52a7d9ed6bb12d3b1768460def8439936d/falco_amazonlinux2_5.4.149-73.259.amzn2.x86_64_1.o
curl: (22) The requested URL returned error: 404
Unable to find a prebuilt falco eBPF probe
* Trying to compile the eBPF probe (falco_amazonlinux2_5.4.149-73.259.amzn2.x86_64_1.o)
```
=> Adding ebpf support for AmazonLinux 2 5.4.149-73.259

config/jobs/arm-build/arm-build.yaml
This commit fixes the following warning reported by `check-prow-config` job:
```json
{
"component": "unset",
"file": "prow/cmd/checkconfig/main.go:90",
"func": "main.reportWarning",
"level": "warning",
"msg": "the following jobs use the kubernetes provider but do not use the pod utilities: [arm-build-falco arm-build-falco-grpc]",
"severity": "warning",
"time": "2021-11-23T21:11:57Z"
}
```
See https://github.com/falcosecurity/test-infra/pull/559#pullrequestreview-814653036
/cc @maxgio92
=> fix(config/jobs): add pod utils to arm-build jobs

config/config.yaml
This commit fixes the following warning reported by the `check-prow-config` job:
```json
{
"component": "unset",
"file": "prow/cmd/checkconfig/main.go:90",
"func": "main.reportWarning",
"level": "warning",
"msg": "the following orgs or repos forbid the do-not-merge/release-note-label-needed label for merging but do not enable the release-note plugin: [repo: falcosecurity/katacoda-scenarios]",
"severity": "warning",
"time": "2021-11-23T21:11:57Z"
}
```
See https://github.com/falcosecurity/test-infra/pull/559#pullrequestreview-814653036
/cc @maxgio92
=> fix(config): katacoda-scenarios does not use `do-not-merge/release-note-label-needed label` label

images/autobump/Dockerfile, images/update-falco-k8s-manifests/Dockerfile, images/update-maintainers/Dockerfile
Image builders with golang:1.14 are currently failing:
```
../../ghproxy/ghcache/ghcache.go:277:36: undefined: os.ReadDir
note: module requires Go 1.16
```
This PR upgrade the golang version to fix the issue.
/cc @maxgio92 
/cc @leodido
=> update(images): upgrade base image to golang:1.17

driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_4.14.252-195.483.amzn2.x86_64_1.yaml, driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/amazonlinux2_4.14.252-195.483.amzn2.x86_64_1.yaml, driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_4.14.252-195.483.amzn2.x86_64_1.yaml
Adding support for kernel 4.14.252-195.483.amzn2.x86_64 to fix the following error:
`Trying to download a prebuilt falco module from https://download.falco.org/driver/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/falco_amazonlinux2_4.14.252-195.483.amzn2.x86_64_1.ko`
`curl: (22) The requested URL returned error: 404`
`Unable to find a prebuilt falco module`
Signed-off-by: Luciano Carranza <luchoc@gmail.com>
=> Add amazonlinux2_4.14.252-195.483 kernel support

images/update-maintainers/persons.json
Re-adding myself to the maintainers list. I was already added since https://github.com/falcosecurity/test-infra/pull/567, but my name was apparently removed by mistake in https://github.com/falcosecurity/test-infra/pull/568.
=> update(images/update-maintainers): re-add jasondellaluce

driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_4.14.256-197.484.amzn2.x86_64_1.yaml, driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/amazonlinux2_4.14.256-197.484.amzn2.x86_64_1.yaml, driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_4.14.256-197.484.amzn2.x86_64_1.yaml
Adding support for kernel 4.14.256-197.484.amzn2.x86_64 to fix the following error:
Trying to download a prebuilt falco module from https://download.falco.org/driver/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/falco_amazonlinux2_4.14.256-197.484.amzn2.x86_64_1.ko
curl: (22) The requested URL returned error: 404
Unable to find a prebuilt falco module
Signed-off-by: Luciano Carranza <luchoc@gmail.com>
=> Add amazonlinux2_4.14.256-197.484 kernel support

driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/centos_4.18.0-348.2.1.el8.x86_64_1.yaml, driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/centos_4.18.0-348.7.1.el8.x86_64_1.yaml, driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/centos_4.18.0-348.el8.x86_64_1.yaml, driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/centos_4.18.0-348.2.1.el8.x86_64_1.yaml, driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/centos_4.18.0-348.7.1.el8.x86_64_1.yaml, driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/centos_4.18.0-348.el8.x86_64_1.yaml, driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/centos_4.18.0-348.2.1.el8.x86_64_1.yaml, driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/centos_4.18.0-348.7.1.el8.x86_64_1.yaml, driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/centos_4.18.0-348.el8.x86_64_1.yaml
CentOS 8.5 was released on 2021-11-16.
Add the CentOS 8.5 configs to driverkit.
=> Add support for CentOS 8.5 configs

driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_4.14.252-195.483.amzn2.x86_64_1.yaml, driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_5.10.75-79.358.amzn2.x86_64_1.yaml, driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/amazonlinux2_4.14.252-195.483.amzn2.x86_64_1.yaml, driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/amazonlinux2_5.10.75-79.358.amzn2.x86_64_1.yaml, driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_4.14.252-195.483.amzn2.x86_64_1.yaml, driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_5.10.75-79.358.amzn2.x86_64_1.yaml
Signed-off-by: Miguel Veliz <mveliz@frame.io>
add amazonlinux2_4.14.252-195.483 and amazonlinux2_5.10.75-79.358 kernel and probe support.
Error:
Trying to download a prebuilt eBPF probe from https://download.falco.org/driver/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/falco_amazonlinux2_4.14.252-195.483.amzn2.x86_64_1.o curl: (22) The requested URL returned error: 404 Unable to find a prebuilt falco eBPF probe
And
Trying to download a prebuilt eBPF probe from https://download.falco.org/driver/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/falco_amazonlinux2_5.10.75-79.358.amzn2.x86_64_1.o curl: (22) The requested URL returned error: 404 Unable to find a prebuilt falco eBPF probe
=> add amazonlinux2_4.14.252-195.483 and amazonlinux2_5.10.75-79.358

driverkit/Makefile
This PR changes the way to check if `driverkit` is installed, and set up a default value. We faced this error in last pipelines when driverkit is not found:
```
DRIVERKIT= S3_DRIVERS_BUCKET="falco-distribution" S3_DRIVERS_KEY_PREFIX="driver" SKIP_EXISTING=true utils/build config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/amazonlinux2_4.14.256-197.484.amzn2.x86_64_1.yaml
unknown shorthand flag: 'c' in -c
```
If `DRIVERKIT` is empty, it creates a command `docker -c` and not `/path/driverkit docker -c`, however `-c` is not a valid argument for docker, this is why we get `unknown shorthand flag: 'c' in -c`.
=> fix issues when driverkit is missing

images/build-drivers/Makefile
Trying to fix https://github.com/falcosecurity/test-infra/pull/595
Most of our other builds use base images such as `golang` or `debian` so we didn't notice a lack of ECR login in the makefiles. Since this one uses a custom built image we needed an ECR login prior to build.
=> adding ecr login to Makefile for base image pull

config/jobs/build-plugins/build-plugins.yaml, images/build-plugins/build-and-publish.sh
This updates the `build-plugins` job to fix the regex used to match plugin names.
=> update: fix plugin name regex in build-plugins jobs

config/config.yaml, config/jobs/build-plugins/build-plugins.yaml, config/plugins.yaml, images/build-plugins/Dockerfile, images/build-plugins/build.sh, images/build-plugins/update-readme.sh
Co-authored-by: Leonardo Grasso <me@leonardograsso.com>
This adds the following in the `build-plugins` jobs:
- An additional check at presubmit that verifies the correctness of the `registry.yaml` plugin registry
- A post-submit job to automatically generate the `README.md` file everytime the plugin registry gets updated
=> update(build-plugins): automatically generate plugins readme and auto-check plugin registry

config/jobs/build-plugins/build-plugins.yaml
This attempt fixing the `build-plugins` postsubmit for readme autogeneration.
The issue has been detected in this job: https://prow.falco.org/view/s3/falco-prow-logs/logs/build-plugins-update-readme-postsubmit/1483775166877011968
=> fix(build-plugins): remove extra_refs from build-plugins-update-readme-postsubmit

driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_5.4.162-86.275.amzn2.x86_64_1.yaml
```
• Looking for a falco module locally (kernel 5.4.162-86.275.amzn2.x86_64)
• Trying to download a prebuilt falco module from https://download.falco.org/driver/5c0b863ddade7a45568c0ac97d037422c9efb750/falco_amazonlinux2_5.4.162-86.275.amzn2.x86_64_1.ko
curl: (22) The requested URL returned error: 404 
Unable to find a prebuilt falco module
```
=> Adds amazonlinux2_5.4.162-86.275.amzn2.x86_64_1

driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_4.14.256-197.484.amzn2.x86_64_1.yaml, driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/amazonlinux2_4.14.256-197.484.amzn2.x86_64_1.yaml, driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_4.14.256-197.484.amzn2.x86_64_1.yaml
Signed-off-by: Miguel Veliz <mveliz@frame.io>
Add 4.14.256-197.484.amzn2.x86_64 probe support
Error while using AWS image ID : ami-07f0ff31daafb95d1
```
Trying to download a prebuilt eBPF probe from https://download.falco.org/driver/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/falco_amazonlinux2_4.14.256-197.484.amzn2.x86_64_1.o
curl: (22) The requested URL returned error: 404
Unable to find a prebuilt falco eBPF probe
```
=> Add 4.14.256-197.484.amzn2.x86_64 probe support

images/build-plugins/update-readme.sh
Signed-off-by: Andrea Bonanno <andrea@bonanno.cloud>
This PR applies a fix to escape and properly print `/n` characters in `update-readme.sh`
=> fix(script): correctly escapes newline character

driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/amazonlinux2_5.4.162-86.275.amzn2.x86_64_1.yaml
Add support for new driver 5.4.162-86.275.amzn2.x86_64, due to failures during falco's installation, as it is trying to download a driver that doesn't exist. 
```
Setting up /usr/src links from host
* Running falco-driver-loader for: falco version=0.30.0, driver version=3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4
* Running falco-driver-loader with: driver=module, compile=yes, download=yes
* Unloading falco module, if present
* Trying to load a system falco module, if present
* Trying to download a prebuilt falco module from https://download.falco.org/driver/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/falco_amazonlinux2_5.4.162-86.275.amzn2.x86_64_1.ko
curl: (22) The requested URL returned error: 404 
Unable to find a prebuilt falco module
* Trying to dkms install falco module with GCC …
```
=> Add support for new driver 5.4.162-86.275.amzn2.x86_64

driverkit/utils/build
This fixes a stupid bug that I introduced with #524.
Basically `SKIP_EXISTING` wasn't actually honored because *There Are No Booleans In Bash™*
/cc @leogr @maxgio92 
=> Fix bash condition that prevented SKIP_EXISTING from actually being honored

driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_4.14.246-187.474.amzn2.x86_64_1.yaml, driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/amazonlinux2_4.14.246-187.474.amzn2.x86_64_1.yaml, driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/amazonlinux2_4.14.246-187.474.amzn2.x86_64_1.yaml, driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_4.14.246-187.474.amzn2.x86_64_1.yaml
This kernel already had a module defined, but no probe artifact. It compiles and runs the eBPF probe locally just fine, as far as I can tell.
=> Add amazonlinux2_4.14.246-187.474.amzn2.x86_64 BPF

config/jobs/arm-build/arm-build.yaml
```
Co-authored-by: Michele Zuccala <michele@zuccala.com>
```
Override default decoration config using arm64 images for utilities.
If this works, next steps:
* update autobump script to manage "-arm64" suffix
* add build-libs job to test on arm64
=> fix(arm-build): try to fix arm64 build job

config/config.yaml
It seems that @poiana forgot to bump some images here (#630) and this causes most Prow jobs to fail.
This PR fixes the issue.
/cc @FedeDP
/assign @leogr
=> fix(config): update pod utilities version to latest

images/build-libs/Dockerfile
Recently, https://github.com/falcosecurity/test-infra/pull/633 was merged, and now build-libs jobs actually tries to build libs using system deps.
This PR properly installs system deps in used image.
=> fix(images): fixed build-libs list of deps to build using system deps.

config/jobs/check-prow-config/check-prow-config.yaml
Since https://github.com/kubernetes/test-infra/pull/25384 got merged (and because we update docker tags in #638), this is now needed in order for `checkconfig` to work correctly.
/cc @leogr
/cc @maxgio92
=> Update checkconfig entrypoint binary name

config/config.yaml
We merged #638 even if pod utils weren't correctly bumped.
This PR fixes that, but we have to fix the script otherwise we will keep happening.
/cc @leogr 
/cc @maxgio92 
/cc @jonahjon
=> Manually update pod utils to v20220225-e131bfaf16

config/jobs/arm-build/arm-build.yaml, config/jobs/autobump/autobump.yaml, config/jobs/lifecycle-bot/periodic-close.yaml, config/jobs/lifecycle-bot/periodic-rotten.yaml, config/jobs/lifecycle-bot/periodic-stale.yaml, images/autobump/bump.sh
#626 introduced 2 problems:
- we lost ability to bump pod utilities (see #638 -> #641)
- we didn't start updating `-arm64` images because standard `sed` only understands POSIX Basic Regular Expressions (BRE) but not Extended Regular Expressions (ERE), and the `?` (on which #626 relied on) is a metacharacter in EREs, but not in BREs ¯\\_(ツ)_/¯
Additionally, this PR fixes #634.
/cc @maxgio92
=> fix(images/autobump): fix broken regex in autobump script

config/jobs/lifecycle-bot/periodic-close.yaml, config/jobs/lifecycle-bot/periodic-rotten.yaml, config/jobs/lifecycle-bot/periodic-stale.yaml, config/jobs/peribolos/peribolos.yaml
This PR:
- addresses issues like [this one](https://prow.falco.org/view/s3/falco-prow-logs/logs/periodic-stale/1501238969222828032) for `commenter` image
- prevents similar issues from happening in the future for `peribolos` image
/cc @maxgio92 
/cc @jonahjon 
=> Set correct entrypoint for k8s images used in jobs

config/prow/deck.yaml
Because of https://github.com/kubernetes/test-infra/pull/25119, deck static files path has changed.
This PR adapts our deck configuration accordingly.
See also https://github.com/kubernetes/test-infra/commit/d2cda07fef895e934499c9277ae4b995c4da962b#diff-d6f8aa32a45789914825e80f5abd962ee6051bb07b57460cd0a660eb86116c49R201-R202
/cc @maxgio92 
/cc @jonahjon 
=> Set proper logo URL for deck

driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/rocky_4.18.0-348.12.2.el8_5.x86_64_1.yaml, driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/rocky_4.18.0-348.2.1.el8_5.x86_64_1.yaml, driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/rocky_4.18.0-348.20.1.el8_5.x86_64_1.yaml, driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/rocky_4.18.0-348.7.1.el8_5.x86_64_1.yaml, driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/rocky_4.18.0-348.el8.0.2.x86_64_1.yaml, driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/rocky_4.18.0-348.12.2.el8_5.x86_64_1.yaml, driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/rocky_4.18.0-348.2.1.el8_5.x86_64_1.yaml, driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/rocky_4.18.0-348.20.1.el8_5.x86_64_1.yaml, driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/rocky_4.18.0-348.7.1.el8_5.x86_64_1.yaml, driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/rocky_4.18.0-348.el8.0.2.x86_64_1.yaml, driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/rocky_4.18.0-348.12.2.el8_5.x86_64_1.yaml, driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/rocky_4.18.0-348.2.1.el8_5.x86_64_1.yaml, driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/rocky_4.18.0-348.20.1.el8_5.x86_64_1.yaml, driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/rocky_4.18.0-348.7.1.el8_5.x86_64_1.yaml, driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/rocky_4.18.0-348.el8.0.2.x86_64_1.yaml, driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/rocky_4.18.0-348.12.2.el8_5.x86_64_1.yaml, driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/rocky_4.18.0-348.2.1.el8_5.x86_64_1.yaml, driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/rocky_4.18.0-348.20.1.el8_5.x86_64_1.yaml, driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/rocky_4.18.0-348.7.1.el8_5.x86_64_1.yaml, driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/rocky_4.18.0-348.el8.0.2.x86_64_1.yaml, driverkit/config/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/rocky_4.18.0-348.12.2.el8_5.x86_64_1.yaml, driverkit/config/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/rocky_4.18.0-348.2.1.el8_5.x86_64_1.yaml, driverkit/config/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/rocky_4.18.0-348.20.1.el8_5.x86_64_1.yaml, driverkit/config/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/rocky_4.18.0-348.7.1.el8_5.x86_64_1.yaml, driverkit/config/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/rocky_4.18.0-348.el8.0.2.x86_64_1.yaml
Adds configs for all Rocky Linux kernel drivers:
- 4.18.0-348.12.2.el8_5.x86_64
- 4.18.0-348.2.1.el8_5.x86_64
- 4.18.0-348.20.1.el8_5.x86_64
- 4.18.0-348.7.1.el8_5.x86_64
- 4.18.0-348.el8.0.2.x86_64
=> Add Rocky Linux kmod configs

images/build-drivers/Dockerfile
With the new driverkit release we want to upgrade test-infra https://github.com/falcosecurity/driverkit/releases/tag/v0.7.0
=> feat: upgrade driverkit to 0.7.0

images/update-maintainers/Dockerfile
This PR should fix the following error:
```
[0m[91m# k8s.io/test-infra/prow/config/secret
../../prow/config/secret/agent.go:73:19: syntax error: unexpected [, expecting (
../../prow/config/secret/reloader.go:27:30: syntax error: unexpected any, expecting ]
../../prow/config/secret/reloader.go:32:25: syntax error: unexpected (, expecting name or (
../../prow/config/secret/reloader.go:33:1: syntax error: non-declaration statement outside function body
../../prow/config/secret/reloader.go:35:31: syntax error: unexpected [, expecting comma or )
../../prow/config/secret/reloader.go:50:31: syntax error: unexpected [, expecting comma or )
../../prow/config/secret/reloader.go:52:2: syntax error: non-declaration statement outside function body
../../prow/config/secret/reloader.go:89:31: syntax …
```
=> build(images): upgrade base image to golang 1.18

driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_5.4.188-104.359.amzn2.x86_64_1.yaml, driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/amazonlinux2_5.4.188-104.359.amzn2.x86_64_1.yaml, driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/amazonlinux2_5.4.188-104.359.amzn2.x86_64_1.yaml, driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_5.4.188-104.359.amzn2.x86_64_1.yaml, driverkit/config/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/amazonlinux2_5.4.188-104.359.amzn2.x86_64_1.yaml
This PR adds the missing configuration for the Amazon Linux 2 5.4.188-104.359 kernel version.
- https://github.com/falcosecurity/test-infra/issues/680
=> Add missing AML2 5.4.188-104.359 kernel version

driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_5.4.190-107.353.amzn2.x86_64_1.yaml, driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/amazonlinux2_5.4.190-107.353.amzn2.x86_64_1.yaml, driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/amazonlinux2_5.4.190-107.353.amzn2.x86_64_1.yaml, driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_5.4.190-107.353.amzn2.x86_64_1.yaml, driverkit/config/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/amazonlinux2_5.4.190-107.353.amzn2.x86_64_1.yaml
This commit adds configuration files for a new AWS linux kernel version
5.4.190-107.353.
=> Add config for amazonlinux2_5.4.190-107.353

config/org.yaml
According to https://github.com/falcosecurity/falco-website/pull/562 I'm now allowed to review and approve the PR for falco-website, but without this change, my approval are not valid for poiana.
PS: I also added myself as maintainer of falcosidekick-ui, I'm the creator after all
=> add Issif as member for website

driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_5.10.102-99.473.amzn2.x86_64_1.yaml, driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_5.10.106-102.504.amzn2.x86_64_1.yaml, driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_5.10.109-104.500.amzn2.x86_64_1.yaml, driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_5.10.50-44.131.amzn2.x86_64_1.yaml, driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_5.10.59-52.142.amzn2.x86_64_1.yaml, driverkit/config/17f5df52a7d9ed6bb12d3b1768460def8439936d/amazonlinux2_5.10.62-55.141.amzn2.x86_64_1.yaml, driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/amazonlinux2_5.10.102-99.473.amzn2.x86_64_1.yaml, driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/amazonlinux2_5.10.106-102.504.amzn2.x86_64_1.yaml, driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/amazonlinux2_5.10.109-104.500.amzn2.x86_64_1.yaml, driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/amazonlinux2_5.10.50-44.131.amzn2.x86_64_1.yaml, driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/amazonlinux2_5.10.59-52.142.amzn2.x86_64_1.yaml, driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/amazonlinux2_5.10.62-55.141.amzn2.x86_64_1.yaml, driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/amazonlinux2_5.10.102-99.473.amzn2.x86_64_1.yaml, driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/amazonlinux2_5.10.106-102.504.amzn2.x86_64_1.yaml, driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/amazonlinux2_5.10.109-104.500.amzn2.x86_64_1.yaml, driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/amazonlinux2_5.10.50-44.131.amzn2.x86_64_1.yaml, driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/amazonlinux2_5.10.59-52.142.amzn2.x86_64_1.yaml, driverkit/config/3aa7a83bf7b9e6229a3824e3fd1f4452d1e95cb4/amazonlinux2_5.10.62-55.141.amzn2.x86_64_1.yaml, driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_5.10.102-99.473.amzn2.x86_64_1.yaml, driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_5.10.106-102.504.amzn2.x86_64_1.yaml, driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_5.10.109-104.500.amzn2.x86_64_1.yaml, driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_5.10.50-44.131.amzn2.x86_64_1.yaml, driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_5.10.59-52.142.amzn2.x86_64_1.yaml, driverkit/config/5c0b863ddade7a45568c0ac97d037422c9efb750/amazonlinux2_5.10.62-55.141.amzn2.x86_64_1.yaml, driverkit/config/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/amazonlinux2_5.10.102-99.473.amzn2.x86_64_1.yaml, driverkit/config/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/amazonlinux2_5.10.106-102.504.amzn2.x86_64_1.yaml, driverkit/config/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/amazonlinux2_5.10.109-104.500.amzn2.x86_64_1.yaml, driverkit/config/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/amazonlinux2_5.10.50-44.131.amzn2.x86_64_1.yaml, driverkit/config/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/amazonlinux2_5.10.59-52.142.amzn2.x86_64_1.yaml, driverkit/config/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/amazonlinux2_5.10.62-55.141.amzn2.x86_64_1.yaml
With the fix introduced in driverkit [#139](https://github.com/falcosecurity/driverkit/pull/139), we can now build amazonlinux2 5.10.x-series kernels and probes.
=> Add missing configs for amazonlinux2 5.10.* series

driverkit/config/319368f1ad778691164d33d59945e00c5752cd27/ubuntu-generic_5.4.0-117-generic_132.yaml
Fix configuration of driverkit for ubuntu-generic with kernel v5.4.0-117 for driver v319368f1ad778691164d33d59945e00c5752cd27
=> fix(driverkit-config): Fix configuration of driverkit for ubuntu driver

driverkit/Makefile, driverkit/utils/build, driverkit/utils/checkfiles
Moreover, improved checkfiles script to be more verbose when printing errors.
Finally, dropped unsupported artifactory publish target from driverkit makefile.
Extracted from #744
=> fix(driverkit): fixed utils/build arch_to_driverkit_arch() case statement

driverkit/utils/generate
=> chore(driverkit): skip arm64 config generation for old tree, as arm64 was unsupported

config/jobs/build-drivers/build-new-centos.yaml, config/jobs/build-drivers/build-new-ubuntu-aws.yaml, config/jobs/build-drivers/build-new-ubuntu-generic.yaml
Now, each kernelversion job only triggers for its kernelversion configs.
=> chore(configs): updated run-if-changed for dbg jobs splitted by major kernel version.

config/jobs/update-dbg/update-dbg.yaml
This allows us to better manage the cross dependency between the update-dbg and update-kernels jobs:
update-kernels will open the PR on kernel-crawler, and as soon as someone approves it (and then it gets merged),
the update-dbg job will trigger.
In the end, we are now able to eg:
* avoid triggering the update-dbg jobs should we don't want to, by just avoiding merging the update-kernels created PR on kernel-crawler repo
* trigger the update-dbg job as quick as possible by merging the kernel-crawler auto PR every week (thus triggering update-dbg weekly).
=> chore(config): run update-dbg job as soon as new kernel lists are merged in main in kernel-crawler repo

config/config.yaml
https://github.com/falcosecurity/falco/pull/2099 is introducing arm64 integration tests for Falco.
Open this one in wip to avoid forgetting :)
=> chore(config): added tests-integration-arm64 to Falco required_status _checks

config/plugins.yaml
Since we started tagging and releasing libs and drivers (see: https://github.com/falcosecurity/libs/releases), we may make a good use of the milestone plugin on the `libs` repo to define the roadmaps of each new release.
=> update(config): enable milestone plugin on falcosecurity/libs

OWNERS, config/OWNERS, config/jobs/OWNERS, config/jobs/build-drivers/OWNERS, config/prow/OWNERS
**What type of PR is this?**
/kind cleanup
/kind documentation
**Any specific area of the project related to this PR?**
**What this PR does / why we need it:**
For https://github.com/falcosecurity/evolution/issues/157, this PR moves inactive approvers (who had very little or zero contributions over the past 6 months) from approvers to `emeritus_approvers` in OWNERS.
**Which issue(s) this PR fixes:**
**Special notes for your reviewer:**
Opened this in favor of #751, as following up the suggestion of https://github.com/falcosecurity/test-infra/pull/751#pullrequestreview-1041853681.
=> update(OWNERS): move inactive approvers to emeritus_approvers

config/org.yaml
@gnosek is present in the to the `OWNERS` file (see [here](https://github.com/falcosecurity/kilt/blob/7c97c711c0d239b512c148dbd7c483b5a705fc9b/OWNERS#L5)) of the [kilt](https://github.com/falcosecurity/kilt) repository, but `config/org.yaml` does not reflect that.
This PR fixes this issue.
=> fix(config/org.yaml): add missing maintainer to `kilt`

config/org.yaml
So we can add him as a reviewer. See https://github.com/falcosecurity/falco/pull/2137
=> update(config/org.yaml): invite `darryk10` to the org

config/org.yaml
This PR synchs the [config/org.yaml](https://github.com/falcosecurity/test-infra/blob/master/config/org.yaml) with `OWNERS` files from all repositories and updates the repository status (ie. remove teams from archived repositories).
All details are in commits' messages.
=> bulk update and cleanup of config/org.yaml

images/update-kernels/Dockerfile
Installing the new kernel-crawler `pygit2` dep with `pip3 install` leads to 
```
Complete output from command python setup.py egg_info:
Failed building wheel for cffi
ERROR: Failed to build one or more wheels
/tmp/pip-build-env-vsds4ub9/lib/python3.7/site-packages/setuptools/installer.py:30: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
SetuptoolsDeprecationWarning,
Traceback (most recent call last):
File "/tmp/pip-build-env-vsds4ub9/lib/python3.7/site-packages/setuptools/installer.py", line 82, in fetch_build_egg
subprocess.check_call(cmd)
File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', …
```
=> fix(images): fixed deps for update-kernels image.

config/org.yaml
Required for https://github.com/falcosecurity/falco-website/pull/661.
=> update(config/org.yaml): add vjjmiras to org members

config/plugins.yaml
This fixes the org teams mapping for the milestone plugin, which have not been updated after the recent org.yaml updates, and prevented the `/milestone` command to be used in all repos for non-admin maintainers.
=> fix(config/plugins.yaml): enable maintainers team for milestone plugin

driverkit/Makefile, driverkit/utils/generate, driverkit/utils/scrape_and_generate
This PR adds the necessary bits to generate the `config` files for minikube. When running `scrape_and_generate` script with the appropriate input it will generate config files containing something similar to:
```yaml
kernelversion: 1_1.26.0
kernelrelease: 5.10.57
target: minikube
architecture: amd64
output:
module: output/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/falco_minikube_5.10.57_1_1.26.0.ko
probe: output/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/falco_minikube_5.10.57_1_1.26.0.o
kernelconfigdata: Q09ORklHX0ZBTk9USUZZPXkKQ09ORklHX0tQUk9CRV9FVkVO...
```
The `kernel-crawler` has already been updated falcosecurity/kernel-crawler#31 as well as `driverkit` falcosecurity/driverkit#189. 
Furthermore this PR tries to simplify how `kernel_version` and `kernel_release` are handled in `generate` …
=> Add support for minikube drivers

driverkit/config/39ae7d40496793cf3d3e7890c9bbdc202263836b/amazonlinux2_5.4.204-113.362.amzn2.x86_64_1.yaml, driverkit/config/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/amazonlinux2_5.4.204-113.362.amzn2.x86_64_1.yaml
This commit adds configuration files for a new AWS linux kernel version
5.4.204-113.36
Signed-off-by: arminioa <arminio.andrei@gmail.com>
=> chore: config for amazonlinux2_5.4.204-113.362

driverkit/config/2.0.0+driver/x86_64/debian_5.10.0-0.bpo.15-amd64_1.yaml, driverkit/config/39ae7d40496793cf3d3e7890c9bbdc202263836b/debian_5.10.0-0.bpo.15-amd64_1.yaml, driverkit/config/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/debian_5.10.0-0.bpo.15-amd64_1.yaml
This PR adds ebpf object file and kernel module support for kernel v5.10.0-0.bpo.15, architecture
`x86_64`.
Using falco in DigitalOcean Kubernetes managed service (DOKS) v1.21.14.do-1 requires
`5.10.0-0.bpo.15-amd64` driver support. Error encountered during setup:
```
* Setting up /usr/src links from host
* Running falco-driver-loader for: falco version=0.31.1, driver version=b7eb0dd65226a8dc254d228c8d950d07bf3521d2
* Running falco-driver-loader with: driver=bpf, compile=yes, download=yes
* Mounting debugfs
* Trying to download a prebuilt eBPF probe from https://download.falco.org/driver/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/falco_debian_5.10.0-0.bpo.15-amd64_1.o
curl: (22) The requested URL returned error: 404
Unable to find a prebuilt falco eBPF probe
* Trying to compile the eBPF …
```
=> chore: add drivers support for kernel-5.10.0-0.bpo.15 x86_64

config/plugins.yaml
Having the release-note block is cumbersome for falcoctl (especially in its current status), so disabling it.
=> update(config/plugins): disable release-note for falcoctl

driverkit/utils/generate
generate kernel from release and version, generate release and version from kernel.
Signed-off-by: Lyonel Martinez <lyonel.martinez@numberly.com>
A previous update messed up a bit with params, getting exit due to at least one of `TARGET_KERNEL`/`TARGET_KERNEL_RELEASE`/`TARGET_KERNEL_VERSION` that was not set.
Bringing back some old functions to make it more breaking proof.
If `TARGET_KERNEL` is set, but not the release or version, we extract them from `TARGET_KERNEL`.
if `TARGET_KERNEL` is not set, we compute it with the release and version.
=> fix(utils-generate): Bringing back the compute functions

images/build-drivers/Dockerfile
```
Signed-off-by: Aldo Lacuku <aldo@lacuku.eu>
```
Bump driverkit version to 0.9.6. 
For more info check the driverkit changelog: https://github.com/falcosecurity/driverkit/releases/tag/v0.9.6
=> update(images): bump driverkit version to 0.9.6

config/jobs/update-dbg/update-dbg.yaml, driverkit/utils/scrape_and_generate, images/update-kernels/entrypoint.sh
Current `update-dbg` job is using `run_if_changed` key that is not available for postsubmits job (https://github.com/kubernetes/test-infra/blob/master/prow/jobs.md), thus it is not triggered.
To workaround this issue, we let `update-kernels` job open a PR targeting `kernels` branch on kernel-crawler; then, `update-dbg` will run for merge to that branch.
kernel-crawler `kernels` branch will only have arch subfolders with their lists, and will be protected.
=> fix(config,driverkit,images): fix kernel-crawler -> test-infra dbg automation

config/plugins.yaml
This fixes the `update-dbg` job that is currently not being triggered correctly.
/cc @FedeDP
=> Add missing trigger plugin to kernel-crawler

config/org.yaml
=> update(config/org.yaml): add jasondellaluce to github-maintainers team

config/plugins.yaml
This PR takes advantage of https://github.com/kubernetes/test-infra/pull/25495 to finally fix #430.
=> Set correct `CONTRIBUTING.md` path for DCO plugin

config/config.yaml
Currently, the CI is waiting for jobs that somehow do not match GitHub action names running in CI. This PR aligns the names with what we can see in the UI, hopefully that is the correct name that is required to update the GitHub configuration.
=> update(config): update status check names

config/config.yaml
The first commit fixes https://github.com/falcosecurity/falcoctl/issues/151
The second commit sets up the `gh-pages` branch (we will use it to publish an artifact index, in a similar way we are doing for charts).
=> update(config): falcoctl branches

config/jobs/build-plugins/build-plugins.yaml, images/build-plugins/on-registry-changed.sh
Fix for: 
```shell
[gh-pages 86141c5] update(index.yaml): new plugins registry data
1 file changed, 182 insertions(+), 1 deletion(-)
rewrite index.yaml (100%)
fatal: could not read Username for 'https://github.com/': No such device or address
```
Plus various minor improvements.
=> fix and improvements to build plugins

config/jobs/update-kernels/update-kernels.yaml, images/update-kernels/Dockerfile, images/update-kernels/entrypoint.sh
Note: this requires https://github.com/falcosecurity/kernel-crawler/pull/46 and a kernel-crawler tag before being useful.
=> fix(images,config): properly use kernel-crawler docker image as base image for update-kernels

driverkit/config/2.0.0+driver/aarch64/amazonlinux2_5.4.209-116.367.amzn2.aarch64_1.yaml, driverkit/config/2.0.0+driver/x86_64/amazonlinux2_5.4.209-116.367.amzn2.x86_64_1.yaml, driverkit/config/39ae7d40496793cf3d3e7890c9bbdc202263836b/amazonlinux2_5.4.209-116.367.amzn2.x86_64_1.yaml, driverkit/config/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/amazonlinux2_5.4.209-116.367.amzn2.x86_64_1.yaml
Hi,
I recently updated my EKS AMI to fix some CVE but now Falco is failing since it miss a kernel module version.
Here are the new version, using [this tutorial](https://www.anycodings.com/1questions/1031057/linux-kernel-headers-are-missing-on-eks-cluster) to find the kernelUrls.
Please let me know if this PR misses something !
Signed-off-by: Julen Dixneuf <julend@padok.fr>
=> adding new configuration files for amazonlinux2_5.4.209-116.367.amzn2

driverkit/config/2.0.0+driver/x86_64/rocky_4.18.0-348.12.2.el8_5.x86_64_1.yaml, driverkit/config/39ae7d40496793cf3d3e7890c9bbdc202263836b/rocky_4.18.0-348.12.2.el8_5.x86_64_1.yaml, driverkit/config/b7eb0dd65226a8dc254d228c8d950d07bf3521d2/rocky_4.18.0-348.12.2.el8_5.x86_64_1.yaml
And whose correct name config is already in place.
=> cleanup(driverkit): dropped a rocky config whose name was wrong

config/config.yaml
This PR protects the libs release branch `release/0.9.0`
=> update(config.yaml): protect libs `0.9.0` release branch

config/clusters/ecr.tf, config/jobs/build-prow-images/build-images.yaml, config/jobs/build-prow-images/publish-images.yaml, config/jobs/update-drivers-website/update-drivers-website.yaml, images/update-drivers-website/Dockerfile, images/update-drivers-website/Makefile, images/update-drivers-website/entrypoint.sh, images/update-drivers-website/index.html, images/update-drivers-website/updateDriversWebsite.go
Signed-off-by: Thomas Labarussias <issif+github@gadz.org>
To allow people to easy search among available drivers, I propose to upload into the [S3 bucket](https://download.falco.org/?prefix=driver/) a website which looks like:
To work, we need to generate json files listing all drivers with their details, this is done by a go script. This go script should be run after each merge into /driverkit/config.
=> Drivers website

images/update-drivers-website/index.html
Signed-off-by: Thomas Labarussias <issif+github@gadz.org>
enforce the encoding of `lib` only. should fix the #878
=> encode only a component

driverkit/utils/generate, images/build-drivers/Dockerfile
Moreover, dropped some useless checks for output-module and output probe in `generate` script: now driverkit(since 0.10.2) is smart enough to disable (with a warning) unsupported outputs.
=> update(images): bumped build-drivers driverkit to 0.10.2

driverkit/README.md, driverkit/utils/generate, driverkit/utils/scrape_and_generate, images/update-kernels/Dockerfile
Instead, pass it through a file.
Env variables have size limit of 32KB.
Moreover, dropped replacement of ubuntu-gke with ubuntu-generic now that we support ubuntu-gke.
=> fix(dbg): avoid passing a huge kernelconfigdata (see: flatcar) as env variable

.vscode/settings.json, images/update-drivers-website/index.html
Signed-off-by: Thomas Labarussias <issif+github@gadz.org>
This PR just updates the drivers website [https://download.falco.org/driver/site/index.html](https://download.falco.org/driver/site/index.html) to show the latest version of libs as default
=> set default driver for the website to the lastest release

config/jobs/build-plugins/build-plugins.yaml, images/build-plugins/build-and-publish.sh
For example, this prevents the new `k8saudit-eks` plugin from being released as table
=> fix: support plugin names containing dashes

config/jobs/build-drivers/build-drivers.local, config/jobs/build-drivers/build-new-amazonlinux.yaml, config/jobs/build-drivers/build-new-centos.yaml, config/jobs/build-drivers/build-new-debian.yaml, config/jobs/build-drivers/build-new-minikube.yaml, config/jobs/build-drivers/build-new-ubuntu-aws.yaml, config/jobs/build-drivers/build-new-ubuntu-azure.yaml, config/jobs/build-drivers/build-new-ubuntu-gcp.yaml, config/jobs/build-drivers/build-new-ubuntu-generic.yaml, config/jobs/build-drivers/build-new-ubuntu-gke.yaml, images/build-drivers/build-drivers.sh
Since our dbg is best-effort, there is no need to spend time in building drivers in presubmit jobs since they won't be uploaded anywhere.
Just validate them.
=> new(driverkit): validate only presubmit build drivers jobs

OWNERS
I would like to propose myself as a test-infra maintainer.
I was highly involved in multiple stuff, like: arm64 Falco support, dbg fixes and improvements, like the kernel-crawler automation pipeline, and i helped as much as i could with fixing issues here and there.
According to our [governance](https://github.com/falcosecurity/evolution/blob/main/GOVERNANCE.md#maintainership), we need a majority vote to take a decision.
Here you can find the rules for the majority vote: point_down
https://github.com/falcosecurity/evolution/blob/main/GOVERNANCE.md#majority-vote
EDIT:
* Vote starts today, 6th of december, 2022
* Vote ends 13th of december, 2022
=> vote: propose fededp as a test-infra maintainer

config/config.yaml, config/org.yaml, config/plugins.yaml
A new repo was born today! https://github.com/falcosecurity/rules becomes a new home for the Falco rules, with big plans for proper versioning, CI/CD and more!
=> new(config): add falcosecurity/rules repository config

config/org.yaml
As a Falco core maintainer, I would like to volunteer as an admin to help other maintainers manage the GitHub organization. In addition, there are several things I'm working on or will be working on in the near future where I would like to help with GH administration tasks:
* Assisting in the development of OCI artifact repositories that we're introducing for rules and plugins. Admin permissions are helpful to troubleshoot and clean up such repositories;
* CI secret configuration and permission setup, e.g. related to the new rules and plugin repos;
* I have proposed a new WG for improving the Falco Software Supply Chain Security, starting this month. That work will require secret updates to enable additional signing and related configuration. I …
=> new(org): add LucaGuerra as admin

config/clusters/ecr.tf, config/jobs/build-prow-images/build-images.yaml, config/jobs/build-prow-images/publish-images.yaml, config/jobs/update-rules-index/update-rules-index.yaml, images/update-rules-index/Dockerfile, images/update-rules-index/Makefile, images/update-rules-index/on-registry-changed.sh
I wish to replicate the same process that we have to update the index file with plugin registry data. Therefore, this PR introduces a new job with a new image that should react to the any registry file change in the rules repo and call the index update program. The program exists in the rules repo and can work on the same falcosecurity index file that we use for plugins, plus the rules registry.
=> new(build): add job to update the main artifact index with rules from the rules repo

images/update-rules-index/on-registry-changed.sh
As per title, since the index update option requires it.
=> fix(update-rules-index): add OCI_REPO_PREFIX

config/clusters/iam.tf
This PR adds the necessary terraform configuration to allow the GHA workflows in the rules repository to upload versioned rulefiles directly to S3 in the `falco-distribution` bucket at release time.
See: https://github.com/falcosecurity/rules/issues/4
=> new(tf): add S3 permissions for GitHub Actions on rules repo

config/clusters/iam.tf
As per title. Sadly we use a version of Terraform that is incompatible with `"terraform-aws-modules/iam/aws//modules/iam-github-oidc-provider"` :sob: . I can't fix it straight away and I don't want to leave test-infra in a broken state so I'm going to revert it and think about a solution
=> fix(tf): temporarily revert PR#947

config/jobs/build-drivers/build-new-amazonlinux.yaml, config/jobs/build-drivers/build-new-bottlerocket.yaml, config/jobs/build-drivers/build-new-centos.yaml, config/jobs/build-drivers/build-new-debian.yaml, config/jobs/build-drivers/build-new-minikube.yaml, config/jobs/build-drivers/build-new-ubuntu-aws.yaml, config/jobs/build-drivers/build-new-ubuntu-azure.yaml, config/jobs/build-drivers/build-new-ubuntu-gcp.yaml, config/jobs/build-drivers/build-new-ubuntu-generic.yaml, config/jobs/build-drivers/build-new-ubuntu-gke.yaml
Since `nodeSelector` directives have been placed under the wrong section of jobs configuration files, they are moved out from `- command` directives in order to be correctly recognized.
=> fix(config/jobs/build-drivers): corrected nodeSelector position

config/config.yaml
This PR removes the required job "build-and-test-modern-bpf-x86 😇 (bundled_deps)", and adds a new required job "test-drivers-x86 😇 (bundled_deps)".
/hold until we have 2 approves on https://github.com/falcosecurity/libs/pull/832
=> update(config): change a required libs job

config/clusters/iam.tf
Since now Terraform has been updated to a newer version we can add the GitHub OIDC provider as I tried to do before. See https://github.com/falcosecurity/test-infra/pull/947 , https://github.com/falcosecurity/test-infra/pull/948, https://github.com/falcosecurity/rules/issues/4
=> new(tf): add S3 permissions for GitHub Actions on rules repo (take 2)

driverkit/Makefile, driverkit/README.md
Every time the dbg gets updated, config files are deleted and generated again in order to always get fresh configurations. In this way there will not be attempts to build old (unbuildable) versions.
Old and already builded drivers will still remain in the bucket.
An alternative would be to delete only configurations older than six months (as in #917 ).
=> new(driverkit): configs regenerated after each dbg update

config/clusters/ecr.tf, config/jobs/build-prow-images/build-images.yaml, config/jobs/build-prow-images/publish-images.yaml
This PR removes update-syscalls build/publish jobs from prow configuration files (see [https://github.com/falcosecurity/test-infra/pull/976](https://github.com/falcosecurity/test-infra/pull/976)).
=> cleanup(prow): removed build/publish update-syscalls jobs

config/clusters/ecr.tf
This PR allows force delete of the `update-syscalls` ECR repository, before deleting it (next PR).
=> chore(config/clusters/ecr): allow force delete on update-syscalls repo

config/jobs/build-prow-images/build-images.yaml, config/jobs/build-prow-images/publish-images.yaml
This PR removes update-kernels build and publish jobs from prow configuration files.
Job ported to GHA (see [here](https://github.com/falcosecurity/kernel-crawler/actions/workflows/update-kernels.yml)).
=> cleanup(prow): removed build/publish update-kernels job

config/clusters/ecr.tf
This PR allows force delete of the `update-kernels` ECR repository, before deleting it (see #988).
=> cleanup(config/clusters/ecr): force delete on update-kernels repo

config/clusters/ecr-iam.tf
This PR carries a little fix on `update-kernels` job removal form ecr config.
=> chore(config/clusters/ecr-iam): removed update-kernels resource.

config/org.yaml
Signed-off-by: Melissa Kilby <melissa.kilby.oss@gmail.com>
add incertum (Melissa Kilby) to libs-maintainer
=> update: add incertum to libs-maintainer

config/config.yaml
According to this change in libs https://github.com/falcosecurity/libs/pull/864 we can remove the required GHA jobs for arm64
=> update(config): remove required arm64 jobs

config/config.yaml, config/org.yaml, config/plugins.yaml
I didn't add any prow jobs, as the current tests use github actions. Not sure if that is preferred to prow or not.
Added all the other configs using falco-aws-terraform as a template.
Signed-off-by: Mark Stemm <mark.stemm@gmail.com>
=> Add flycheck-falco-rules to test-infra

config/plugins.yaml
Prow milestone plugin [checks](https://github.com/kubernetes/test-infra/blob/master/prow/plugins/milestone/milestone.go#L116) if the user to be in the milestone maintainer team.
`repo_milestone` Prow config field should fix the issue and allow `falcoctl-maintainers` Github team to apply milestone, chatops-way, with `/milestone` command.
Fixes #1001
=> fix(config/plugins.yaml): add missing milestone maintainers team setting

config/config.yaml, config/org.yaml, config/plugins.yaml
see: https://github.com/falcosecurity/evolution/issues/251
see: https://github.com/falcosecurity/evolution/issues/246
=> update(config): add entries for new pigeon and testing repos

config/prow/monitoring/grafana_expose.yaml
This PR configures temporarily the exposition of Prow Monitoring stack's Grafana dashboard at:
- http only
- AWS application load balancer DNS name
/cc @jasondellaluce @FedeDP
=> chore(config/prow/monitoring: temporarily expose grafana http only

config/org.yaml
What type of PR is this?
/kind documentation
Any specific area of the project related to this PR?
/area governance
What this PR does / why we need it:
As my proposition to become a falcosecurity/driverkit maintainers has been accepted (https://github.com/falcosecurity/driverkit/pull/259), I added myself to the organizatiuon file as requested.
Which issue(s) this PR fixes:
None
=> chore(config/org.yaml): add myself (Lowaiz) as driverkit maintainer

config/config.yaml, config/jobs/branchprotector/branchprotector.yaml, config/jobs/check-prow-config/check-prow-config.yaml, config/jobs/lifecycle-bot/periodic-close.yaml, config/jobs/lifecycle-bot/periodic-rotten.yaml, config/jobs/lifecycle-bot/periodic-stale.yaml, config/jobs/peribolos/peribolos.yaml, config/prow/crier.yaml, config/prow/deck.yaml, config/prow/ghproxy.yaml, config/prow/hook.yaml, config/prow/horologium.yaml, config/prow/needs-rebase.yaml, config/prow/prow-controller-manager.yaml, config/prow/sinker.yaml, config/prow/statusreconciler.yaml, config/prow/tide.yaml
Reverts falcosecurity/test-infra#1071
Seems like it is causing issues to the prow-controller-manager, since no prow job could be scheduled after that PR was merged: https://prow.falco.org/
=> revert: "Bump prow from v20230315-6d54c174f4 to v20230324-8697ff4d24"

config/prow/runner.yaml, tools/deploy_prow.sh
For reference, see https://github.com/actions/actions-runner-controller/.
Basically, we introduce a new resource `RunnerDeployment` that will manage github self-hosted runners requests from the falcosecurity/falco repository.
/cc @maxgio92 
/hold
=> new(config,tools): add Github actions runner controller support.

tools/deploy_prow.sh
This is needed to avoid
> Error from server (Invalid): error when creating "https://github.com/actions/actions-runner-controller/releases/download/v0.27.1/actions-runner-controller.yaml": CustomResourceDefinition.apiextensions.k8s.io "runnerdeployments.actions.summerwind.dev" is invalid: metadata.annotations: Too long: must have at most 262144 bytes
Errors.
https://github.com/actions/actions-runner-controller/issues/1317
=> fix(tools): force server-side flag when applying ARC resources.

tools/deploy_prow.sh
As per title, follow the same pattern used in the rest of the repo
=> fix(prow): do not fail if the secret already exists

.github/workflows/update-drivers-website.yml, config/clusters/iam.tf
This PR adds the policy to allow update-driver-website workflow to upload to S3
=> fix(config/clusters): added policies for S3 access update-driver-website workflow

config/jobs/build-prow-images/build-images.yaml, config/jobs/build-prow-images/publish-images.yaml
This PR removes the `update-drivers-website` job from the prow image (see #1013)
=> cleanup(config/jobs): remove update-drivers-website build/publish image trigger 

config/jobs/build-drivers/build-new-centos.yaml, config/jobs/build-drivers/build-new-ubuntu-aws.yaml, config/jobs/build-drivers/build-new-ubuntu-azure.yaml, config/jobs/build-drivers/build-new-ubuntu-gcp.yaml, config/jobs/build-drivers/build-new-ubuntu-generic.yaml, config/jobs/build-drivers/build-new-ubuntu-gke.yaml
This PR introduces the configurations for build-driver jobs of `ubuntu 6.x` and `centos 6.x` kernel versions.
Fixes #931
=> update(config/jobs/build-drivers): added jobs for ubuntu 6.x and centos 6.x kernel versions

config/clusters/iam.tf
This PR adds the policy to allow access to the S3 bucket to GHA in [plugins](https://github.com/falcosecurity/plugins) repo.
=> new(config/clusters/iam.tf): added policies for S3 access plugins repo GHA

config/jobs/build-drivers/build-new-amazonlinux.yaml, config/jobs/build-drivers/build-new-bottlerocket.yaml, config/jobs/build-drivers/build-new-centos.yaml, config/jobs/build-drivers/build-new-debian.yaml, config/jobs/build-drivers/build-new-fedora.yaml, config/jobs/build-drivers/build-new-minikube.yaml, config/jobs/build-drivers/build-new-ubuntu-aws.yaml, config/jobs/build-drivers/build-new-ubuntu-azure.yaml, config/jobs/build-drivers/build-new-ubuntu-gcp.yaml, config/jobs/build-drivers/build-new-ubuntu-generic.yaml, config/jobs/build-drivers/build-new-ubuntu-gke.yaml
This PR tunes the resource allocation to pods responsible for build-driver jobs.
The requested CPU and memory have been decreased and limits have been set to try to schedule two pods on the same node.
Since build processes are not very memory intensive, pods should not be affected by OOM kills.
On the other hand, requests and limits on the CPU might be not sufficient and cause throttling.
Also, the range between CPU requests and limits may be too small resulting in pods being unable to be scheduled.
WDYT @FedeDP @maxgio92?
=> update(config/jobs/build-drivers): tuning pods resources allocation

config/clusters/iam.tf
This PR completes #1103 and #1104 by removing the `build-plugins` job S3 policy in favor of gha (see #1098).
=> cleanup(config/clusters/iam.tf): removed policy for build-plugins job S3 access.

config/clusters/iam.tf
I decided to split dev and release so that the master CI is not able to push anything to the release packages.
See https://github.com/falcosecurity/falco/pull/2501
=> new(config): added iam s3 access roles for Falco (dev and release).

config/jobs/update-github-teams/peribolos-syncer.yaml
The post-submit Prow Job runs on changes on OWNERS files - i.e. in the evolution repository.
It synchronizes the Peribolos config - in the test-infra repository - updating the specified evolution-maintainers GitHub Team, with the additional approvers specified in the OWNERS file.
More [here](https://github.com/maxgio92/peribolos-syncer/blob/v0.1.0/docs/peribolos-syncer_sync_github.md#peribolos-syncer-sync-github).
Closes #777
=> Add postsubmit job to sync Peribolos GitHub Teams from OWNERS

config/config.yaml
This PR removes a  no more required job on libs, instead of `build-modern-bpf-s390x 😁 (system_deps)`  no we use `build-libs-s390x 😁 (system_deps)`
=> update(config): remove a no more required job for libs

config/clusters/iam.tf
When this role was set up we could only write to the `-dev` bucket from the master branch in Falco. This has since changed because prerelease support has been added which allow us to use development tags that will ultimately end up in the `-dev` bucket. Meaning that we need to add the appropriate permission here.
=> update(iam): allow dev role for prerelease tags

config/jobs/autobump/autobump.yaml
This PR is needed to fix the [`autobump`](https://github.com/falcosecurity/test-infra/blob/master/config/jobs/autobump/autobump.yaml) Prow Job since it gets stuck in trying to mount an inexistent volume containing an unnecessary ssh key.
=> fix(config/jobs/autobump/autobump.yaml): removed unused ssh key volume mount.

config/jobs/build-drivers/build-new-amazonlinux.yaml
=> new(config): added amazonlinux2023 build-drivers jobs.

config/jobs/build-drivers/build-new-talos.yaml
WIP because i first want to test that the kernelconfigdata we are fetching can correctly build a working driver.
=> new(config): added talos build-drivers jobs.

config/clusters/eks.tf
This is a quick solution to avoid horizontal scaling not working on the jobs on ARM's node group.
It needs a better implementation then.
Fixes #1164 
/cc @FedeDP
=> refactor(config/clusters): move jobs on arm to different subnet

driverkit/Makefile, driverkit/utils/scrape_and_generate
This leverage new `last_run_distro` file present in kernels branch of kernel-crawler.
See https://github.com/falcosecurity/kernel-crawler/pull/151 and https://github.com/falcosecurity/kernel-crawler/pull/150
=> chore(dbg): allow distro specific driverkit configs generation.

config/autobump-config/prow-autobump-config.yaml, config/jobs/autobump/autobump.yaml
This PR updates the autobumper image and configuration to make Poiana signing its commits (see [#29591](https://github.com/kubernetes/test-infra/pull/29591)) and to exclude from the analysis the `driverkit` path.
=> update(config): updated autobump image version and configuration.

config/clusters/ecr.tf
This PR forces delete `autobump` ecr resource.
=> cleanup(config/clusters/ecr.tf): autobump ecr force delete.

config/clusters/TERRAFORM.md, config/clusters/ecr-iam.tf, config/clusters/ecr.tf, docs/update-cluster.md, tools/create_ecr.sh
=> cleanup(config/clusters/ecr.tf): removed old autobumper ecr resource.

config/config.yaml
The `test-dev-packages-arm64` is not existent when running workflows on PRs for Falco.
=> update(config.yaml): drop non-existent required job from falco

config/distribution/containers.tf
The Terraform distribution configuration was missing entries for `falco` and `falco-driver-loader`.
In addition, add the following images:
* falco-driver-loader-legacy for the older driver loader image
* falco-distroless for the experimental distroless/minimal image
=> new(tf): add Falco ECR public repositories

images/build-plugins/Dockerfile, images/update-dbg/Dockerfile, images/update-falco-k8s-manifests/Dockerfile, images/update-maintainers/Dockerfile, images/update-rules-index/Dockerfile
As per title. This is preventing some jobs from running, see e.g. https://prow.falco.org/view/s3/falco-prow-logs/logs/build-plugins-on-registry-changed-postsubmit/1704176676482584576
```
go: downloading github.com/rivo/uniseg v0.4.4
/home/prow/go/pkg/mod/github.com/pterm/pterm@v0.12.67/slog_handler.go:5:2: package log/slog is not in GOROOT (/usr/local/go/src/log/slog)
make[1]: *** [Makefile:25: registry] Error 1
make[1]: Leaving directory '/home/prow/go/src/github.com/falcosecurity/plugins/build/registry'
make: *** [Makefile:119: build/registry/registry] Error 2
> moving on since there are no changes...
> cloning distribution index repository (https://github.com/falcosecurity/falcoctl.git)...
/tmp /home/prow/go/src/github.com/falcosecurity/plugins
Cloning into 'falcoctl'...
/tmp/falcoctl …
```
=> update(docker): update Golang base image to 1.21

config/distribution/containers.tf, config/distribution/distribution.tf, config/distribution/terraform_state.tf, config/distribution/terraform_versions.tf
This updates terraform for distribution:
* The tf version is updated, the same we use for Prow
* I removed the three repos that were apparently created without tf as terraform refuses to touch those. I wonder if we can fix it?
* I added encryption configuration to the buckets to reflect what is already live (those configs result in no change when applied)
=> update(tf): update distribution config to be consistent with the current state

config/org.yaml
Following https://github.com/falcosecurity/kernel-testing/pull/72 this adds me as maintainer of kernel-testing repository. 🥳
=> update(config/org.yaml): add therealbobo as kernel-testing maintainer

config/config.yaml
xref: https://github.com/falcosecurity/charts/pull/554
/assign @leogr @LucaGuerra
=> update chart status checks

config/jobs/build-drivers/build-new-photon.yaml, config/jobs/update-dbg/update-dbg.yaml, images/build-drivers/Dockerfile, images/build-drivers/build-drivers.sh, images/update-dbg/Dockerfile
Moreover:
* bumped dbg-go to 0.12.1 (for photon support + a fix)
* use `=` instead of the bash specific `==` for string comparison in build-drivers.sh
* Move `update-dbg` cron to 8am
=> new: photonOS support for prebuilt drivers

config/config.yaml
This is in preparation for https://github.com/falcosecurity/libs/pull/1685 . That PR changes the name of the ASan job (which becomes `sanitizers`) and adds its ARM64 counterpart. After libs#1685 is merged we'll be able to add the new jobs as required.
=> update(config): temporarily remove required from asan build

config/distribution/containers.tf
I believe this wasn't applying cleanly because it was counting the bytes and we had emojis in the text. I removed a few more bytes to make sure.
=> fix(tf): reduce falcoctl about field length

config/clusters/eks.tf, config/clusters/eks_variables.tf
As per title. GitHub Actions needs permission in order to update the EKS cluster.
=> new(tf): add EKS permissions for GitHub Actions

config/clusters/iam.tf
The https://github.com/falcosecurity/falco-playground repo needs to access the falco-playground S3 bucket created for the occasion and its accompanying CloudFront distribution.
=> new(config): add S3 and CloudFront permissions for falco-playground repo

config/clusters/iam.tf
This allows the release job on Falco Playground to list the bucket contents during the sync operation
=> fix(tf): add S3 list access to Falco Playground

config/prow/aws-auth-config-rbac.yaml
This PR contains the following RBAC setup:
- one `Role` that allows to read (`GET`) the _aws-auth_ `ConfigMap` that contains the AWS identity mappings to the Kubernetes Groups.
- one `RoleBinding` that binds the Role above to the `Group` _aws-config-readers_.
**Use cases**
The first use case for that is the GitHub Actions identity that will run the Terraform Plan that in our case needs to:
- read over AWS resources.
- read (get) the _aws-auth_ `ConfigMap` because it's part of the EKS setup managed via Terraform ([here](https://github.com/falcosecurity/test-infra/blob/f5a4efaafd32564f7261dc3b9515b45e03240722/config/clusters/eks.tf#L10) and [here](https://github.com/falcosecurity/test-infra/blob/f5a4efaafd32564f7261dc3b9515b45e03240722/config/clusters/eks_variables.tf#L148)).
The mapping of …
=> chore(k8s): add role binding to read aws-auth configmap

config/clusters/iam.tf
As for official Github [documentation](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#filtering-for-pull_request-events), the OIDC subject for pull requests needs to be updated AWS side to allow Github Actions to assume the AWS IAM Role needed to read resources during Terraform Plan.
In example, when the authentication is made during a workflow triggered by a pull request, the subject is structured like below:
`repo:<orgName/repoName>:pull_request`
=> fix(clusters/iam): set correct oidc subject for prs

config/jobs/update-github-teams/peribolos-syncer-client-go.yaml, config/jobs/update-github-teams/peribolos-syncer-driverkit.yaml, config/jobs/update-github-teams/peribolos-syncer-falco-website.yaml, config/jobs/update-github-teams/peribolos-syncer-falco.yaml, config/jobs/update-github-teams/peribolos-syncer-falcosidekick-ui.yaml, config/jobs/update-github-teams/peribolos-syncer-falcosidekick.yaml, config/jobs/update-github-teams/peribolos-syncer-libs.yaml, config/jobs/update-github-teams/peribolos-syncer-test-infra.yaml
This PR fixes errors on the update-github-teams jobs trigger branches, that erroneously were set to _main_.
=> fix(config/jobs/update-github-teams): set correct trigger branch

config/jobs/update-github-teams/peribolos-syncer-test-infra-pre-test.yaml
This is a temporary test for presubmit to test trigger
=> chore(config/jobs): add test peribolos-syncer presubmit

config/jobs/update-github-teams/peribolos-syncer-test-infra-pre-test.yaml
This PR explicitely sets the job command to `peribolos-syncer` to the test presubmit syncer job.
/cc @FedeDP
=> chore(config/jobs): set the test presubmit syncer job command

config/jobs/update-github-teams/peribolos-syncer-test-infra-pre-test.yaml
This PR bumps peribolos-syncer for the presubmit update-github-teams test job.
/cc @FedeDP
=> chore(config/jobs): bump syncer for test job

config/org.yaml
Hi everyone!
I'd like to get admin privileges in the org, in the spirit of serving the entire falcosecurity organization.
Working on CIs around the falcosecurity org, i often would love to check eg: the env variables shared with the actions, or just install a self-hosted runner (eg: kernel-testing uses one, libs is going to use one for ppc64le).
For all of the above, i propose myself as an admin in the falcosecurity org.
/cc @leogr
=> update(config): let FedeDP become an admin on the falcosecurity.

config/OWNERS, config/org.yaml
The following account (of an emeritus maintainer) no longer exists, and https://github.com/markyjackson-taulia doesn't either. So, thus PR is just cleaning it up.
Note: Marky, if you read this, I wanted just to let you know that you will always be welcome here :hugs:
=> chore(config): cleaning up unexisting user

config/clusters/eks_variables.tf
After a discussion with @alacuku (Falco Core Maintainer) I learned that he is interested in helping with maintenance of our cluster, incl. adding monitoring and other things. Given his expertise with Kubernetes I'm very happy about that interest 😁 . Also, considering that he is a core maintainer he can be a cluster admin (see [governance](https://github.com/falcosecurity/test-infra/blob/master/proposals/20200925-admins.md#proposal))
Please confirm @alacuku 🙏
=> update(config): add Aldo Lacuku to cluster maintainers

.github/workflows/ci.yml
Kubeval is no longer maintained since 2021: https://github.com/instrumenta/kubeval
Use the proposed replacement tool: https://github.com/yannh/kubeconform
=> chore(ci): switch to kubeconform since kubeval is deprecated.

config/config.yaml, config/jobs/branchprotector/branchprotector.yaml, config/jobs/check-prow-config/check-prow-config.yaml, config/jobs/lifecycle-bot/periodic-close.yaml, config/jobs/lifecycle-bot/periodic-rotten.yaml, config/jobs/lifecycle-bot/periodic-stale.yaml, config/jobs/peribolos/peribolos.yaml, config/prow/crier.yaml, config/prow/deck.yaml, config/prow/ghproxy.yaml, config/prow/hook.yaml, config/prow/horologium.yaml, config/prow/needs-rebase.yaml, config/prow/prow-controller-manager.yaml, config/prow/sinker.yaml, config/prow/statusreconciler.yaml, config/prow/tide.yaml
gcr.io/k8s-prow/ changes: https://github.com/kubernetes/test-infra/compare/6d54c174f4...f1101a8b4e (2023&#x2011;03&#x2011;15 → 2024&#x2011;04&#x2011;03)
/cc
=> Update Prow to v20240403-f1101a8b4e

config/prow/pod-identity-webhook/auth.yaml, config/prow/pod-identity-webhook/deployment-base.yaml, config/prow/pod-identity-webhook/mutatingwebhook.yaml, config/prow/pod-identity-webhook/namespace.yaml, config/prow/pod-identity-webhook/service.yaml, tools/deploy_prow.sh
Now the service accounts can be annotated with iam roles in order to get the right permissions.
=> new(config/prow): add pod-identity-webhook

config/autobump-config/prow-autobump-config.yaml
Porting of upstream https://github.com/kubernetes/test-infra/pull/32420 to fix autobump prow jobs: https://prow.falco.org/view/s3/falco-prow-logs/logs/ci-test-infra-autobump-prow/1816019406883393536
=> fix(config/autobumper): fixed autobumper config adding `consistentImageExceptions`

config/config.yaml, config/jobs/branchprotector/branchprotector.yaml, config/jobs/check-prow-config/check-prow-config.yaml, config/jobs/lifecycle-bot/periodic-close.yaml, config/jobs/lifecycle-bot/periodic-rotten.yaml, config/jobs/lifecycle-bot/periodic-stale.yaml, config/jobs/peribolos/peribolos.yaml, config/prow/crier.yaml, config/prow/deck.yaml, config/prow/ghproxy.yaml, config/prow/hook.yaml, config/prow/horologium.yaml, config/prow/needs-rebase.yaml, config/prow/prow-controller-manager.yaml, config/prow/sinker.yaml, config/prow/statusreconciler.yaml, config/prow/tide.yaml
Multiple distinct gcr.io/k8s-prow/ changes:
Commits | Dates | Images
--- | --- | ---
https://github.com/kubernetes/test-infra/compare/f1101a8b4e...47a381b1df | 2024&#x2011;04&#x2011;03&nbsp;&#x2192;&nbsp;2024&#x2011;07&#x2011;19 | commenter
https://github.com/kubernetes/test-infra/compare/f1101a8b4e...dbbd2d86b | 2024&#x2011;04&#x2011;03&nbsp;&#x2192;&nbsp;2024&#x2011;07&#x2011;23 | branchprotector, checkconfig, clonerefs, crier, deck, entrypoint, ghproxy, hook, horologium, initupload, needs-rebase, peribolos, prow-controller-manager, sidecar, sinker, status-reconciler, tide
/cc
=> Update Prow to v20240723-dbbd2d86b

config/config.yaml, config/jobs/branchprotector/branchprotector.yaml, config/jobs/check-prow-config/check-prow-config.yaml, config/jobs/lifecycle-bot/periodic-close.yaml, config/jobs/lifecycle-bot/periodic-rotten.yaml, config/jobs/lifecycle-bot/periodic-stale.yaml, config/jobs/peribolos/peribolos.yaml, config/prow/crier.yaml, config/prow/deck.yaml, config/prow/ghproxy.yaml, config/prow/hook.yaml, config/prow/horologium.yaml, config/prow/needs-rebase.yaml, config/prow/prow-controller-manager.yaml, config/prow/sinker.yaml, config/prow/statusreconciler.yaml, config/prow/tide.yaml
Multiple distinct gcr.io/k8s-prow/ changes:
Commits | Dates | Images
--- | --- | ---
https://github.com/kubernetes/test-infra/compare/47a381b1df...a5d9345e59 | 2024&#x2011;07&#x2011;19&nbsp;&#x2192;&nbsp;2024&#x2011;07&#x2011;31 | commenter
https://github.com/kubernetes/test-infra/compare/dbbd2d86b...37a08f946 | 2024&#x2011;07&#x2011;23&nbsp;&#x2192;&nbsp;2024&#x2011;08&#x2011;05 | branchprotector, checkconfig, clonerefs, crier, deck, entrypoint, ghproxy, hook, horologium, initupload, needs-rebase, peribolos, prow-controller-manager, sidecar, sinker, status-reconciler, tide
/cc
=> Update Prow to v20240805-37a08f946

config/config.yaml
Due to a necessary patch release in libs we need to disable required checks for zig builds since that is not enabled on the release branch. Partially reverts https://github.com/falcosecurity/test-infra/pull/1635 (we know what we doing).
=> update(config): (re)move zig

config/config.yaml, config/org.yaml, config/plugins.yaml
See https://github.com/falcosecurity/evolution/issues/403
Depends on https://github.com/falcosecurity/test-infra/pull/1639
/hold
=> update(config): add falco-talon

config/config.yaml, config/org.yaml, config/plugins.yaml
See https://github.com/falcosecurity/evolution/issues/405
Depends on #1661 and https://github.com/gnosek/falco-plugin-rs/pull/1
/hold
=> update(config): add plugin-sdk-rs

config/config.yaml
as per title, since our new runners are not stable yet
=> temporarily disable required arm64 tests

config/config.yaml, config/org.yaml, config/plugins.yaml
See https://github.com/falcosecurity/evolution/issues/412
/hold we first need to transfer the repo under our org
=> update(config): add falco-actions

config/config.yaml, config/org.yaml, config/plugins.yaml
See: https://github.com/falcosecurity/evolution/issues/421
=> new(config): add falcosecurity/elftoolchain repo

images/build-plugins/Dockerfile
This is required to satisfy latest build tools requirements and aligns with the golang version used in falcosecurity/plugins repo.
=> update(images/build-plugins): bump base image to golang:1.23-bullseye

images/build-plugins/Dockerfile
Trying to fix:
```
> creating pull-request to merge poiana:docs/update-readme-registry-table into main...
pr-creator: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by pr-creator)
pr-creator: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by pr-creator)
```
=> fix(images/build-plugins): fix pr-creator

config/applications/falco.yaml
k8smeta and container plugin automatically mark some output fields as suggested. Use them.
=> chore(config): enable Falco suggested_output config key.

config/org.yaml
See
- https://github.com/falcosecurity/rules/pull/304
- https://github.com/falcosecurity/falco-website/pull/1491
=> docs(org.yaml): add `ekoops` to rules and falco-website

config/org.yaml
Required by https://github.com/falcosecurity/libs/pull/2631.
=> update(members): add Tero Kauppinen (terror96) as member of libs.
